//! Standard AGS4 data dictionary access.
//!
//! The dictionary *content* is ©AGS published reference data (see
//! `data/PROVENANCE.md`). It's compiled into the binary at build time
//! by `build.rs` as `phf` perfect-hash maps — zero startup cost, no
//! runtime parse. This module owns the public value types the generated
//! tables instantiate, plus the version selector + lookup surface the
//! rule modules (V3+) will use.
//!
//! phf does not implement `PhfHash` for tuples, so heading keys are the
//! composite string `"GROUP\u{1f}HEADING"` (US — unit separator, never
//! valid inside an AGS4 name). Build it via [`heading_key`].

/// One heading's dictionary definition. All `&'static str` so the phf
/// tables live entirely in the binary's read-only segment and the
/// linker dedups the many repeated `"OTHER"` / `"m"` / `""` literals.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DictEntry {
    pub ags_type: &'static str,
    pub unit: &'static str,
    pub status: &'static str,
    pub desc: &'static str,
}

/// One group's dictionary metadata (from the DICT group's `GROUP` rows).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct GroupMeta {
    /// Parent group code; `""` for a root group (e.g. PROJ).
    pub parent: &'static str,
    pub desc: &'static str,
}

// `DictVersion` (the bundled-edition enum) + `as_str` / `ALL` / `from_edition` /
// `tables` / `FALLBACK` are GENERATED from ags_dictionary.json by build.rs — see
// the `include!` below. Add an edition to the official source dictionaries +
// regenerate the union, never here.

/// *How* `resolve_dict_version` arrived at the edition — so a caller
/// (the corpus-QA harness) can REPORT it without re-deriving the
/// policy. The dogfood blind spot this fixes: a genuine `TRAN_AGS`
/// edition and the O-30 fallback both resolve to `4.1.1`, so a plain
/// version string can't tell "294 real 4.1.1 files" from "294 files
/// with no parseable TRAN_AGS". Cross-ref O-30.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DictResolution {
    /// Explicit `CheckOptions::dict_version` override.
    Forced,
    /// `TRAN_AGS` exactly matched a bundled edition (python-parity).
    ExactTranAgs,
    /// Newest bundled patch of the `TRAN_AGS` major.minor (O-30).
    GuessedPatch,
    /// Missing / unparsable / unrecognised 4.x / future → FALLBACK.
    Fallback,
}

impl DictResolution {
    pub fn as_str(self) -> &'static str {
        match self {
            DictResolution::Forced => "forced",
            DictResolution::ExactTranAgs => "exact",
            DictResolution::GuessedPatch => "guessed",
            DictResolution::Fallback => "fallback",
        }
    }
}

// Generated by build.rs into OUT_DIR from ags_dictionary.json. Defines:
//   pub enum DictVersion { … } + as_str / ALL / from_edition / tables
//   pub const FALLBACK: DictVersion   (the python-parity auto-select fallback,
//                                       sourced from the union's fallback_edition)
//   per version: DICT_<v>_HEADINGS / _GROUPS / _GROUP_HEADINGS / _ABBRS / _TRAN_AGS
include!(concat!(env!("OUT_DIR"), "/dict_data.rs"));

/// Composite key for a heading lookup. Group + heading joined by U+001F.
pub fn heading_key(group: &str, heading: &str) -> String {
    let mut k = String::with_capacity(group.len() + 1 + heading.len());
    k.push_str(group);
    k.push('\u{1f}');
    k.push_str(heading);
    k
}

/// Read-only handle onto one bundled standard dictionary. Cheap to copy
/// (just two static map refs + a str).
#[derive(Debug, Clone, Copy)]
pub struct Dictionary {
    headings: &'static phf::Map<&'static str, DictEntry>,
    groups: &'static phf::Map<&'static str, GroupMeta>,
    /// Per-group heading names in dictionary order (Rule 7). The
    /// `headings` map is unordered, so canonical order is a separate
    /// table.
    group_headings: &'static phf::Map<&'static str, &'static [&'static str]>,
    /// `(ABBR_HDNG, ABBR_CODE) → ABBR_DESC` from the bundled standard
    /// dict's own ABBR group. Used by Rule 16's FYI variant to flag
    /// abbreviations whose description differs from the canonical
    /// standard. Stage 7e.
    abbrs: &'static phf::Map<&'static str, &'static str>,
    tran_ags: &'static str,
    version: DictVersion,
}

impl Dictionary {
    pub fn bundled(version: DictVersion) -> Self {
        // `tables()` (generated by build.rs) maps the edition to its five
        // compiled lookup tables — so the edition set lives in ONE place.
        let (headings, groups, group_headings, abbrs, tran_ags) = version.tables();
        Dictionary {
            headings,
            groups,
            group_headings,
            abbrs,
            tran_ags,
            version,
        }
    }

    /// Canonical description for an abbreviation in the bundled
    /// standard ABBR table. Returns `None` if the (heading, code)
    /// isn't listed in the standard — rule_16's main check already
    /// handles "abbreviation not defined anywhere" so this FYI
    /// variant only fires when both the file and the standard
    /// define the same (heading, code) but with different descs.
    pub fn abbr_desc(&self, heading: &str, code: &str) -> Option<&'static str> {
        // Key shape mirrors `heading_key` — composite "H\u{1f}C".
        let mut k = String::with_capacity(heading.len() + 1 + code.len());
        k.push_str(heading);
        k.push('\u{1f}');
        k.push_str(code);
        self.abbrs.get(k.as_str()).copied()
    }

    /// Every `ABBR_CODE` the bundled standard ABBR table lists for
    /// `heading` (the picklist), in the map's iteration order; empty if
    /// the heading has no picklist. The keys are the `heading\u{1f}code`
    /// composites [`abbr_desc`](Self::abbr_desc) looks up. Exposed so a
    /// generator (ags4-forge) can sample realistic, *valid* PA values
    /// from the single-source dictionary rather than a hardcoded list.
    pub fn abbr_codes(&self, heading: &str) -> Vec<&'static str> {
        self.abbrs
            .keys()
            .filter_map(|k| {
                let (h, code) = k.split_once('\u{1f}')?;
                (h == heading).then_some(code)
            })
            .collect()
    }

    pub fn version(&self) -> DictVersion {
        self.version
    }

    /// The TRAN_AGS value this dictionary edition expects (Rule 14).
    pub fn tran_ags(&self) -> &'static str {
        self.tran_ags
    }

    /// Definition for `GROUP.HEADING`, or `None` if the heading isn't in
    /// the standard dictionary (Rule 9 / 17 territory).
    pub fn heading(&self, group: &str, heading: &str) -> Option<&'static DictEntry> {
        self.headings.get(heading_key(group, heading).as_str())
    }

    /// Metadata for a group code, or `None` if not a standard group.
    pub fn group(&self, code: &str) -> Option<&'static GroupMeta> {
        self.groups.get(code)
    }

    /// Every standard group code in this edition (unordered — the phf map
    /// iteration order). Callers that need a stable order should sort. Used to
    /// serialise the whole per-edition dictionary out to the web reference UI.
    pub fn group_codes(&self) -> impl Iterator<Item = &'static str> + '_ {
        self.groups.keys().copied()
    }

    /// This group's standard headings, in the canonical dictionary
    /// order Rule 7 enforces. Empty slice for an unknown group (its
    /// headings then fall to Rule 9 / the file's own DICT group).
    pub fn group_headings(&self, code: &str) -> &'static [&'static str] {
        self.group_headings.get(code).copied().unwrap_or(&[])
    }

    /// Every heading name defined anywhere in the standard dictionary
    /// (across all groups, with cross-group borrows repeated). Rule
    /// 19b_3 (V8) needs "is this heading defined under *some* group".
    pub fn all_heading_names(&self) -> impl Iterator<Item = &'static str> + '_ {
        self.group_headings
            .values()
            .flat_map(|hs| hs.iter().copied())
    }
}

// --- Serialisable dictionary snapshot (the `dictionary(edition)` accessor) ----
// One shared `{ags_edition, groups:[{code, contents, parent, headings:[…]}]}`
// view of a bundled edition, so the browser (wasm), `laterite.registry.
// dictionary()` (PyO3) and Node's `registry.dictionary()` render it identically
// from ONE builder instead of three copies (#294 F#6). Serialize only — each
// surface does its own JSON (serde_json / serde_wasm_bindgen).

#[derive(serde::Serialize)]
pub struct DictHeadingDto {
    pub name: String,
    pub status: String,
    #[serde(rename = "type")]
    pub ags_type: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
    pub description: String,
}

#[derive(serde::Serialize)]
pub struct DictGroupDto {
    pub code: String,
    /// The group's standard description (its "contents"/name).
    pub contents: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parent: Option<String>,
    pub headings: Vec<DictHeadingDto>,
}

#[derive(serde::Serialize)]
pub struct DictionaryDto {
    pub ags_edition: String,
    pub groups: Vec<DictGroupDto>,
}

/// Build the serialisable snapshot of one bundled standard-dictionary edition:
/// groups sorted by code, each group's headings in canonical dictionary order.
/// The single source the wasm / PyO3 / Node `dictionary(edition)` accessors share.
pub fn dictionary_dto(version: DictVersion) -> DictionaryDto {
    let d = Dictionary::bundled(version);
    let mut codes: Vec<&'static str> = d.group_codes().collect();
    codes.sort_unstable();
    let groups = codes
        .into_iter()
        .map(|code| {
            let gm = d.group(code);
            let headings = d
                .group_headings(code)
                .iter()
                .map(|&h| {
                    let e = d.heading(code, h);
                    DictHeadingDto {
                        name: h.to_string(),
                        status: e.map(|x| x.status).unwrap_or("").to_string(),
                        ags_type: e.map(|x| x.ags_type).unwrap_or("").to_string(),
                        unit: e
                            .map(|x| x.unit)
                            .filter(|u| !u.is_empty())
                            .map(str::to_string),
                        description: e.map(|x| x.desc).unwrap_or("").to_string(),
                    }
                })
                .collect();
            DictGroupDto {
                code: code.to_string(),
                contents: gm.map(|m| m.desc).unwrap_or("").to_string(),
                parent: gm
                    .map(|m| m.parent)
                    .filter(|p| !p.is_empty())
                    .map(str::to_string),
                headings,
            }
        })
        .collect();
    DictionaryDto {
        ags_edition: version.as_str().to_string(),
        groups,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bundled_dicts_load_and_have_plausible_size() {
        for v in [
            DictVersion::V4_0_3,
            DictVersion::V4_0_4,
            DictVersion::V4_1,
            DictVersion::V4_1_1,
            DictVersion::V4_2,
        ] {
            let d = Dictionary::bundled(v);
            // Every bundled AGS4 edition has >50 groups and >1000
            // headings; assert a floor so an empty/broken codegen
            // fails loudly.
            assert!(
                d.groups.len() > 50,
                "{:?}: only {} groups",
                v,
                d.groups.len()
            );
            assert!(
                d.headings.len() > 1000,
                "{:?}: only {} headings",
                v,
                d.headings.len()
            );
        }
    }

    #[test]
    fn known_headings_resolve() {
        let d = Dictionary::bundled(DictVersion::V4_2);
        let proj_id = d.heading("PROJ", "PROJ_ID").expect("PROJ.PROJ_ID");
        assert_eq!(proj_id.ags_type, "ID");
        assert!(proj_id.status.contains("KEY"));
        // LOCA is a real group with a parent in the dictionary.
        assert!(d.group("LOCA").is_some());
        // A heading that doesn't exist returns None.
        assert!(d.heading("PROJ", "NOT_A_HEADING").is_none());
    }

    #[test]
    fn tran_ags_matches_version() {
        for v in [
            DictVersion::V4_0_3,
            DictVersion::V4_0_4,
            DictVersion::V4_1,
            DictVersion::V4_1_1,
            DictVersion::V4_2,
        ] {
            // The dictionary's own embedded TRAN_AGS must equal the
            // variant's canonical string (Rule 14 / auto-selection).
            assert_eq!(Dictionary::bundled(v).tran_ags(), v.as_str(), "{v:?}");
        }
    }

    #[test]
    fn group_headings_are_in_dictionary_order() {
        let d = Dictionary::bundled(DictVersion::V4_2);
        let proj = d.group_headings("PROJ");
        // PROJ_ID is the KEY and must precede PROJ_NAME in the dict.
        let id = proj.iter().position(|h| *h == "PROJ_ID").expect("PROJ_ID");
        let name = proj
            .iter()
            .position(|h| *h == "PROJ_NAME")
            .expect("PROJ_NAME");
        assert!(id < name, "PROJ order wrong: {proj:?}");
        // Every ordered name must also resolve in the membership map
        // (the two tables are built from the same rows).
        for h in proj {
            assert!(
                d.heading("PROJ", h).is_some(),
                "{h} missing from headings map"
            );
        }
        // Unknown group → empty slice, never a panic.
        assert!(d.group_headings("ZZZZ").is_empty());
    }

    #[test]
    fn dict_resolution_as_str_round_trips() {
        // The harness serialises the resolution kind; every variant must
        // map to its stable token.
        assert_eq!(DictResolution::Forced.as_str(), "forced");
        assert_eq!(DictResolution::ExactTranAgs.as_str(), "exact");
        assert_eq!(DictResolution::GuessedPatch.as_str(), "guessed");
        assert_eq!(DictResolution::Fallback.as_str(), "fallback");
    }

    #[test]
    fn version_and_group_codes_expose_the_edition() {
        let d = Dictionary::bundled(DictVersion::V4_1);
        assert_eq!(d.version(), DictVersion::V4_1);
        // group_codes() is the unordered key view the web reference UI
        // serialises; it must include the well-known groups and agree in
        // length with the group count.
        let codes: Vec<&str> = d.group_codes().collect();
        assert_eq!(codes.len(), d.groups.len());
        assert!(codes.contains(&"PROJ"));
        assert!(codes.contains(&"LOCA"));
    }

    #[test]
    fn all_heading_names_includes_cross_group_borrows() {
        // Rule 19b_3 keys off this: a borrowed heading (LOCA_ID under
        // SAMP) must appear because it's "defined somewhere".
        let d = Dictionary::bundled(DictVersion::V4_2);
        let names: std::collections::HashSet<&str> = d.all_heading_names().collect();
        assert!(names.contains("LOCA_ID"));
        assert!(names.contains("PROJ_ID"));
    }

    #[test]
    fn abbr_desc_resolves_a_standard_abbreviation() {
        // The FYI-16 path looks up canonical ABBR descriptions keyed by
        // (ABBR_HDNG, ABBR_CODE). `ARTW_TYPE/DRY → "Dry test"` is a
        // verbatim row in the bundled 4.2 ABBR group (data/
        // Standard_dictionary_v4_2.ags). An unknown pair → None.
        let d = Dictionary::bundled(DictVersion::V4_2);
        assert_eq!(d.abbr_desc("ARTW_TYPE", "DRY"), Some("Dry test"));
        assert!(d.abbr_desc("NOPE_HDNG", "ZZ").is_none());
    }

    #[test]
    fn abbr_codes_enumerates_a_picklist() {
        let d = Dictionary::bundled(DictVersion::V4_2);
        // SAMP_TYPE is a substantial picklist; every enumerated code must
        // round-trip through abbr_desc (same composite key), and "U"
        // (Undisturbed) is a verbatim row.
        let codes = d.abbr_codes("SAMP_TYPE");
        assert!(codes.len() > 1, "SAMP_TYPE should have several codes");
        assert!(
            codes.contains(&"U"),
            "SAMP_TYPE should include U, got {codes:?}"
        );
        for c in &codes {
            assert!(
                d.abbr_desc("SAMP_TYPE", c).is_some(),
                "{c} must resolve a desc"
            );
        }
        assert!(d.abbr_codes("NOPE_HDNG").is_empty());
    }
}
