/* "Pick your stack" (#395) — the page's most concretely useful section.
 *
 * Five surfaces exist and not one of them is discoverable from a landing page
 * today. Every card here names a package a stranger is about to type, which is
 * why NONE of these names is written in this file: they come from
 * installChannels.ts, generated by tools/gen_install_channels.py out of the
 * manifests that decide them, and cross-checked against a second record before
 * the file is written. A landing page advertising a package name the registry
 * does not have is worse than no landing page.
 *
 * Commands wrap rather than overflow. `npm install @laterite/ags4-wasm` is
 * longer than a phone's content column, and a card that scrolls sideways to
 * reveal the end of the one string the reader came for has failed at its only
 * job.
 */

import { createSignal, For, type Component } from "solid-js";
import { Button } from "@shared/components";
import { INSTALL_CHANNELS, type InstallChannel } from "../installChannels";

const CopyButton: Component<{ command: string; label: string }> = (props) => {
  const [copied, setCopied] = createSignal(false);
  return (
    <Button
      variant="ghost"
      size="sm"
      aria-label={`Copy the ${props.label} install command`}
      onClick={() => {
        // No fallback path: a browser without the clipboard API (or one that
        // refuses the write over plain http) still shows the command as
        // selectable text, which is what the button is a shortcut for. Failing
        // quietly beats a second, worse copy mechanism — so the rejection is
        // swallowed rather than surfaced.
        navigator.clipboard.writeText(props.command).then(
          () => {
            setCopied(true);
            setTimeout(() => setCopied(false), 1600);
          },
          () => {},
        );
      }}
    >
      {copied() ? "copied" : "copy"}
    </Button>
  );
};

const Card: Component<{ channel: InstallChannel }> = (props) => (
  <li
    class="flex flex-col rounded-lg border bg-surface p-4"
    classList={{
      // The highlighted card. A border and a tint, never a fill: the CTA is the
      // only rust mass on the page and a filled card would compete with it.
      "border-cta bg-cta-quiet": props.channel.primary,
      "border-line": !props.channel.primary,
    }}
  >
    <p class="flex items-baseline gap-2 font-mono text-micro uppercase tracking-[--track-micro] text-fg-muted">
      {props.channel.label}
      {props.channel.registry ? (
        <span class="text-fg-faint">· {props.channel.registry}</span>
      ) : null}
    </p>

    <a
      href={props.channel.href}
      class="mt-2 font-mono text-body font-semibold break-all text-accent no-underline hover:underline"
    >
      {props.channel.package}
    </a>

    <div class="mt-3 flex items-start gap-2 rounded-md border border-line-subtle bg-surface-code px-3 py-2">
      <code class="min-w-0 flex-1 font-mono text-caption break-words whitespace-pre-wrap text-fg">
        {props.channel.command}
      </code>
      <CopyButton command={props.channel.command} label={props.channel.label} />
    </div>

    <p class="mt-3 text-caption text-fg-muted">{props.channel.note}</p>
  </li>
);

export const InstallGrid: Component = () => (
  <div>
    <h2 class="font-display text-h2 font-extrabold tracking-[--track-tight] text-accent">
      Pick your stack
    </h2>
    <p class="mt-2 max-w-[60ch] text-fg-soft">
      One engine behind every one of these. Scriptable output is byte-identical
      across them, so a CI gate and a notebook cannot disagree.
    </p>

    <ul class="mt-6 grid list-none grid-cols-1 gap-3 p-0 min-[38rem]:grid-cols-2 min-[64rem]:grid-cols-3">
      <For each={INSTALL_CHANNELS}>
        {(channel) => <Card channel={channel} />}
      </For>
    </ul>

    <p class="mt-6 text-caption text-fg-muted">
      <a
        class="font-semibold text-cta no-underline hover:underline"
        href="https://docs.laterite.dev/learn/install/"
      >
        Full install guide
      </a>{" "}
      — extras, the dependency shape, and a first validate in three lines.
      laterite is in beta: the AGS4 surface is stable and covered, and the
      version numbers still move quickly.
    </p>
  </div>
);
