/* "Pick your stack" (#395) — the page's most concretely useful section.
 *
 * Five surfaces exist and not one of them is discoverable from a landing page
 * today. Every card here names a package a stranger is about to type, which is
 * why NONE of these names is written in this file: they come from
 * installChannels.ts, generated by tools/gen_install_channels.py out of the
 * manifests that decide them, and cross-checked against a second record before
 * the file is written. A landing page advertising a package name the registry
 * does not have is worse than no landing page.
 *
 * The desktop presentation is the TAB STRIP (#641, retiring #395's grid by
 * recorded decision): every surface name stays visible — the discoverability
 * job survives — while one detail card shows, at roughly half the grid's
 * height. At the demo sections' two-column breakpoint the section splits
 * text-left / panel-right, keeping the page's left-right-left progression;
 * between the phone break and that width the same tabs stack under the text.
 * Below 38rem the #595 deck is untouched.
 *
 * Commands wrap rather than overflow. `npm install @laterite/ags4-wasm` is
 * longer than a phone's content column, and a card that scrolls sideways to
 * reveal the end of the one string the reader came for has failed at its only
 * job.
 */

import { createSignal, Index, Show, type Component } from "solid-js";
import { Button } from "@shared/components";
import { Carousel } from "./Carousel";
import { INSTALL_CHANNELS, type InstallChannel } from "../installChannels";
import { phoneViewport } from "../viewport";

const CopyButton: Component<{ command: string; label: string }> = (props) => {
  const [copied, setCopied] = createSignal(false);
  return (
    <Button
      variant="ghost"
      size="sm"
      aria-label={`Copy the ${props.label} install command`}
      onClick={() => {
        // No fallback path: a browser without the clipboard API (or one that
        // refuses the write over plain http) still shows the command as
        // selectable text, which is what the button is a shortcut for. Failing
        // quietly beats a second, worse copy mechanism — so the rejection is
        // swallowed rather than surfaced.
        navigator.clipboard.writeText(props.command).then(
          () => {
            setCopied(true);
            setTimeout(() => setCopied(false), 1600);
          },
          () => {},
        );
      }}
    >
      {copied() ? "copied" : "copy"}
    </Button>
  );
};

const Card: Component<{ channel: InstallChannel }> = (props) => (
  <div
    /* Every card in its surface's own hue (#595): the border is the hue, the
       fill is the hue washed into the surface — landing.css's .install-card
       owns the mix and the per-theme switch, this element only carries the
       data. The old primary highlight retired with the flag: five surfaces
       in five dresses reads as a family, one bordered card read as
       unexplained favouritism. The `li` belongs to the callers — the grid
       and the phone deck each bring their own. */
    class="install-card flex h-full flex-col rounded-lg border p-4"
    style={{
      "--hue-light": props.channel.hue.light,
      "--hue-dark": props.channel.hue.dark,
    }}
  >
    <p class="flex items-baseline gap-2 font-mono text-micro uppercase tracking-(--track-micro) text-fg-muted">
      {props.channel.label}
      {props.channel.registry ? (
        <span class="text-fg-faint">· {props.channel.registry}</span>
      ) : null}
    </p>

    <a
      href={props.channel.href}
      class="mt-2 font-mono text-body font-semibold break-all text-accent no-underline transition-colors hover:underline"
    >
      {props.channel.package}
    </a>

    {/* A channel with no install command (#533: the CLI — the standalone
        binary IS the thing) gets the download as its action instead of an
        empty code box with a copy button that copies nothing. */}
    <Show
      when={props.channel.command}
      fallback={
        <div class="mt-3">
          <Button variant="outline" size="sm" href={props.channel.href}>
            Download from GitHub releases
          </Button>
        </div>
      }
    >
      <div class="mt-3 flex items-start gap-2 rounded-md border border-line-subtle bg-surface-code px-3 py-2">
        <code class="min-w-0 flex-1 font-mono text-caption break-words whitespace-pre-wrap text-fg">
          {props.channel.command}
        </code>
        <CopyButton
          command={props.channel.command}
          label={props.channel.label}
        />
      </div>
    </Show>

    <p class="mt-3 text-caption text-fg-muted">{props.channel.note}</p>

    {/* The way onward (#619): a reader sold by a card gets a path to "how
        do I start with THIS surface" — the generator derives the target
        from the docs page's own repo path and refuses a page that is not
        there. `mt-auto` pins the link to the card's floor, so five cards
        with five note lengths still read as one row of doors. */}
    <p class="mt-auto pt-3 text-caption">
      <a
        class="font-semibold text-cta no-underline transition-colors hover:underline"
        href={props.channel.docs}
      >
        Get started
      </a>
    </p>
  </div>
);

export const InstallGrid: Component = () => (
  <div class="min-[64rem]:grid min-[64rem]:grid-cols-[minmax(0,26rem)_minmax(0,1fr)] min-[64rem]:items-start min-[64rem]:gap-8">
    <div>
      <h2 class="font-display text-h2 font-extrabold tracking-(--track-tight) text-accent">
        Pick your stack
      </h2>
      {/* The claim below is scoped to the surfaces the nightly output-value
        gate actually walks — #536 records the leg-by-leg check. DuckDB is a
        read-only surface, so it has no AGS4 writer for the gate to compare:
        don't re-widen the sentence to all five cards.

        The intro's tail carries what two retired fixtures used to say
        (#617): the transport aside collapsed to one sentence with its docs
        link, and the install-guide line moved up from below the grid. */}
      <p class="mt-2 max-w-[60ch] text-fg-soft">
        One engine behind every one of these. Every surface that writes AGS4
        (Python, Node, the CLI, the browser) emits byte-identical scriptable
        output, gate-checked nightly, so a CI job and a notebook cannot
        disagree. DuckDB is the read-only surface: there is no writer to
        diverge. The engine also packs deliveries for sending, zstd compressed
        and optionally passphrase encrypted:{" "}
        <a
          class="font-semibold text-cta no-underline transition-colors hover:underline"
          href="https://docs.laterite.dev/cookbook/transport/"
        >
          Pack / encrypt for transport
        </a>
        .{" "}
        <a
          class="font-semibold text-cta no-underline transition-colors hover:underline"
          href="https://docs.laterite.dev/learn/install/"
        >
          Full install guide
        </a>
        : extras, the dependency shape, and a first validate in three lines.
        laterite is in beta: the AGS4 surface is stable and covered, and the
        version numbers still move quickly.
      </p>
    </div>

    {/* Below the phone break the five cards are the one-card looping deck
        (#595) — same cards, paged with dots. Everywhere else the tab strip
        carries them (#641). */}
    <Show
      when={!phoneViewport()}
      fallback={
        <Carousel
          label="Install channels"
          items={INSTALL_CHANNELS}
          chrome="dots"
          noun="card"
          class="mt-6"
          card={(c) => <Card channel={c()} />}
        />
      }
    >
      <StackTabs />
    </Show>
  </div>
);

/* The tab strip (#641): five always-visible surface names, one detail card.
 * The panel is a one-cell grid stack — the #622 parking pattern — so every
 * card stays in the DOM (countable, computed-styles readable, the e2e
 * contract) and the panel holds the tallest card's height: switching tabs
 * reflows nothing below. Roving tabindex + arrows, the tablist grammar. */
const StackTabs: Component = () => {
  const [at, setAt] = createSignal(0);
  const tabEls: HTMLButtonElement[] = [];
  const move = (delta: number) => {
    const n = INSTALL_CHANNELS.length;
    const next = (at() + delta + n) % n;
    setAt(next);
    tabEls[next]?.focus();
  };
  return (
    <div class="mt-6 min-[64rem]:mt-0">
      <div
        role="tablist"
        aria-label="Install channels"
        class="flex flex-wrap items-center gap-2"
      >
        <Index each={INSTALL_CHANNELS}>
          {(channel, i) => (
            <button
              type="button"
              role="tab"
              id={`stack-tab-${channel().id}`}
              aria-selected={at() === i}
              aria-controls={`stack-panel-${channel().id}`}
              tabIndex={at() === i ? 0 : -1}
              ref={(el) => {
                tabEls[i] = el;
              }}
              class="rounded-md border px-3 py-1.5 font-mono text-caption transition-colors focus-visible:outline-hidden focus-visible:[box-shadow:var(--focus-ring)]"
              classList={{
                "border-accent bg-accent-quiet text-accent": at() === i,
                "border-line text-fg-soft hover:text-accent": at() !== i,
              }}
              onClick={() => setAt(i)}
              onKeyDown={(e) => {
                // preventDefault: a handled arrow walks the strip; letting
                // it also nudge the page scroll reads as a glitch.
                if (e.key === "ArrowRight") {
                  e.preventDefault();
                  move(1);
                }
                if (e.key === "ArrowLeft") {
                  e.preventDefault();
                  move(-1);
                }
              }}
            >
              {channel().label}
            </button>
          )}
        </Index>
      </div>
      <div class="mt-3 grid">
        <Index each={INSTALL_CHANNELS}>
          {(channel, i) => (
            <div
              role="tabpanel"
              id={`stack-panel-${channel().id}`}
              aria-labelledby={`stack-tab-${channel().id}`}
              class="col-start-1 row-start-1"
              classList={{ invisible: at() !== i }}
            >
              <Card channel={channel()} />
            </div>
          )}
        </Index>
      </div>
    </div>
  );
};
