// @generated by tools/gen_web_editions.py from ags_dictionary.json — DO NOT EDIT.
//
// The web's SINGLE source for the AGS dictionary editions the UI can target.
// Every editions list on the web reads THIS module — settings validation, the
// validate/export dropdowns, the `DictVersionOpt` type — replacing what used to
// be four hand-maintained copies (settings.ts, validator.ts, Controls.tsx,
// ExportPane.tsx), edited in lockstep by hand (laterite-dev#529, the web remainder of laterite-dev#509's
// edition single-sourcing for the Rust/Python/Node surfaces).
//
// The values are `ags_dictionary.json`'s own `editions` array (the union
// generated from the official AGS `.ags` files by tools/gen_dictionary.py) plus
// the web-only `"auto"` sentinel. Web needs the list SYNCHRONOUSLY — settings
// validation runs before the union JSON is fetched and before wasm loads — so it
// is a committed generated file, not a runtime read. Re-run
// `uv run --no-sync python tools/gen_web_editions.py` after a dictionary edit;
// the drift gate `tests/test_web_editions_match_generator.py` fails if it is stale.

/** The AGS4 dictionary editions, in the union's canonical order. */
export const EDITIONS = ["4.0.3", "4.0.4", "4.1", "4.1.1", "4.2"] as const;

/** A concrete AGS4 dictionary edition. */
export type Edition = (typeof EDITIONS)[number];

/** The editions plus the `"auto"` sentinel (resolve the edition from TRAN_AGS) —
 *  the selectable dictionary-version vocabulary for settings and the UI dropdowns. */
export const DICT_VERSIONS = ["auto", ...EDITIONS] as const;

/** A selectable dictionary version: a concrete edition or `"auto"`. */
export type DictVersionOpt = (typeof DICT_VERSIONS)[number];
