/* What the other engine says here (#660).
 *
 * The demo claims laterite and python-ags4 answer differently in places. This
 * is where that claim is cashed, at the moment a reader meets one — and it is
 * READ, never computed. `divergence-notes.json` is generated by
 * `tools/gen_demo_state_map.py` from the swept state map, so a difference the
 * sweep cannot demonstrate cannot be asserted here, and one it finds cannot be
 * quietly dropped: a shape with no note fails the generator.
 *
 * Two matching strategies, because the two cases are not symmetrical.
 *
 * `ours` and `tier` match on the RULE KEY. The finding is already on the page
 * carrying that key, so the note hangs off it. This generalises past the swept
 * states for free — any state raising the key gets the explanation, including
 * ones the sweep never enumerated.
 *
 * `theirs` has no finding to hang off, which IS the case: the other engine
 * reported something and we did not, so the page has nothing of ours to
 * annotate. It matches on the cell the state was reached by, against the
 * literal value the enumerator wrote. One cell, one string comparison. The
 * alternative — deciding "is this value non-ASCII for its declared type" in
 * the browser — would put a second validator on the page to disagree with the
 * first, which is the failure this whole demo exists to avoid.
 */

import notes from "./divergence-notes.json";
import type { Delivery } from "./delivery";

export type DivergenceSide = "ours" | "theirs" | "tier";

export type DivergenceNote = {
  /** The O-N record in `OBSERVATIONS.md` this explanation is drawn from. */
  readonly observation: string;
  readonly side: DivergenceSide;
  readonly text: string;
  /** How many swept states carry this difference — provenance, not a claim
   *  about the state on screen. */
  readonly states: number;
  readonly rules?: readonly string[];
  readonly whenCellIs?: readonly {
    readonly group: string;
    readonly row: number;
    readonly heading: string;
    readonly value: string;
  }[];
};

const ALL: readonly DivergenceNote[] = notes.notes.map((n) => ({
  observation: n.observation,
  side: n.side as DivergenceSide,
  text: n.text,
  states: n.states,
  rules: "rules" in n ? (n.rules as readonly string[]) : undefined,
  whenCellIs:
    "when_cell_is" in n
      ? (n.when_cell_is as DivergenceNote["whenCellIs"])
      : undefined,
}));

const BY_RULE = new Map<string, DivergenceNote>();
for (const note of ALL) for (const r of note.rules ?? []) BY_RULE.set(r, note);

const THEIRS = ALL.filter((n) => n.side === "theirs");

/** The note for a finding's rule key, or undefined where the two engines agree.
 *  Most findings have none — that is the ordinary case, and the silent one. */
export function divergenceForRule(rule: string): DivergenceNote | undefined {
  return BY_RULE.get(rule);
}

/** The notes for things the OTHER engine reports about this delivery and we do
 *  not. Empty in all but one reachable state, which is the point: a panel that
 *  appeared often would stop being read. */
export function divergencesTheyRaise(
  delivery: Delivery,
): readonly DivergenceNote[] {
  return THEIRS.filter((note) =>
    (note.whenCellIs ?? []).some((cell) => {
      const group = delivery.find((g) => g.code === cell.group);
      const col = group?.headings.indexOf(cell.heading) ?? -1;
      if (!group || col < 0) return false;
      return group.rows[cell.row]?.[col] === cell.value;
    }),
  );
}

/** The version of python-ags4 every note above is a claim about. Carried so the
 *  page can name it rather than saying "the other tool" and leaving a reader to
 *  guess which release we measured. */
export const PYTHON_AGS4_VERSION: string = notes.python_ags4_version;
