/* What the other engine says here (#660).
 *
 * The demo claims laterite and python-ags4 answer differently in places. This
 * is where that claim is cashed, at the moment a reader meets one — and it is
 * READ, never computed. `divergence-notes.json` is generated by
 * `tools/gen_demo_state_map.py` from the swept state map, so a difference the
 * sweep cannot demonstrate cannot be asserted here, and one it finds cannot be
 * quietly dropped: a shape with no note fails the generator.
 *
 * Two matching strategies, because the two cases are not symmetrical.
 *
 * `ours` and `tier` match on the RULE KEY. The finding is already on the page
 * carrying that key, so the note hangs off it. This generalises past the swept
 * states for free — any state raising the key gets the explanation, including
 * ones the sweep never enumerated.
 *
 * `theirs` has no finding to hang off, which IS the case: the other engine
 * reported something and we did not, so the page has nothing of ours to
 * annotate. It matches on the cell the state was reached by, against the
 * literal value the enumerator wrote. One cell, one string comparison. The
 * alternative — deciding "is this value non-ASCII for its declared type" in
 * the browser — would put a second validator on the page to disagree with the
 * first, which is the failure this whole demo exists to avoid.
 */

import notes from "./divergence-notes.json";
import counts from "./python-counts.json";
import type { Delivery } from "./delivery";
import type { Finding } from "./engine";

export type DivergenceSide = "ours" | "theirs" | "tier";

/** The one trigger a browser can evaluate without a second opinion about the
 *  rules: this exact value, in this exact cell. Declared once because both the
 *  notes and the count below match on it, and three copies of a shape is three
 *  chances for one of them to drift. */
export type CellMatch = {
  readonly group: string;
  readonly row: number;
  readonly heading: string;
  readonly value: string;
};

export type DivergenceNote = {
  /** The O-N record in `OBSERVATIONS.md` this explanation is drawn from. */
  readonly observation: string;
  readonly side: DivergenceSide;
  readonly text: string;
  /** How many swept states carry this difference — provenance, not a claim
   *  about the state on screen. */
  readonly states: number;
  readonly rules?: readonly string[];
  readonly whenCellIs?: readonly CellMatch[];
};

const ALL: readonly DivergenceNote[] = notes.notes.map((n) => ({
  observation: n.observation,
  side: n.side as DivergenceSide,
  text: n.text,
  states: n.states,
  rules: "rules" in n ? (n.rules as readonly string[]) : undefined,
  whenCellIs:
    "when_cell_is" in n
      ? (n.when_cell_is as DivergenceNote["whenCellIs"])
      : undefined,
}));

const BY_RULE = new Map<string, DivergenceNote>();
for (const note of ALL) for (const r of note.rules ?? []) BY_RULE.set(r, note);

const THEIRS = ALL.filter((n) => n.side === "theirs");

/** The note for a finding's rule key, or undefined where the two engines agree.
 *  Most findings have none — that is the ordinary case, and the silent one. */
export function divergenceForRule(rule: string): DivergenceNote | undefined {
  return BY_RULE.get(rule);
}

/** The notes for things the OTHER engine reports about this delivery and we do
 *  not. Empty in all but one reachable state, which is the point: a panel that
 *  appeared often would stop being read. */
export function divergencesTheyRaise(
  delivery: Delivery,
): readonly DivergenceNote[] {
  return THEIRS.filter((note) => (note.whenCellIs ?? []).some(holds(delivery)));
}

/** Does the delivery hold this exact value in this exact cell? Shared by the
 *  notes above and the count below, which match on the same thing for the same
 *  reason. */
const holds = (delivery: Delivery) => (cell: CellMatch) => {
  const group = delivery.find((g) => g.code === cell.group);
  const col = group?.headings.indexOf(cell.heading) ?? -1;
  if (!group || col < 0) return false;
  return group.rows[cell.row]?.[col] === cell.value;
};

/** The version of python-ags4 every note above is a claim about. Carried so the
 *  page can name it rather than saying "the other tool" and leaving a reader to
 *  guess which release we measured. */
export const PYTHON_AGS4_VERSION: string = notes.python_ags4_version;

/* How many findings python-ags4 reports about THIS delivery (#673).
 *
 * Read, never computed: python-ags4 is a dev-only dependency and is not in the
 * browser. `python-counts.json` is generated by `tools/gen_demo_state_map.py`
 * from the swept states, keyed by laterite's own finding signature — the rule
 * key to count map the demo already has from its own run.
 *
 * That key is legitimate because the sweep measured it to be: the swept states
 * collapse to far fewer signatures than states, and python's answer is constant
 * across all but one of them. The exception is carried as an explicit cell
 * override rather than smoothed over — clearing `PROJ_ID` or any of several
 * `TRAN` cells leaves laterite saying exactly the same thing, and only a blank
 * `TRAN_AGS` earns python's extra FYI (O-53).
 *
 * Two designs were measured and rejected, so they do not get retried. Hashing
 * the delivery text is exact but over-strict: typing a project name changes the
 * bytes while changing neither engine's findings. Per-lever addition is simply
 * wrong: levers do not compose, and orphaning a SAMP row then deleting the LOCA
 * group predicts more findings than the measured answer, because deleting the
 * parent changes what the first edit meant.
 */

type CountEntry = {
  readonly signature: string;
  readonly python: number;
  readonly states: number;
  readonly when_cell_is?: readonly (CellMatch & { readonly python: number })[];
};

const BY_SIGNATURE = new Map<string, CountEntry>(
  (counts.signatures as readonly CountEntry[]).map((e) => [e.signature, e]),
);

/** laterite's finding signature, in the form the sweep recorded it.
 *
 *  FYI-tier findings are excluded because the sweep excludes them: it measures
 *  both engines with every tier on so a difference means something, and then
 *  keys this table on the subset the demo's own `validate` call surfaces, which
 *  takes the wasm default of FYI off. The generator refuses to write the table
 *  at all if a swept state ever raises one, so the two cannot drift apart
 *  quietly — this filter is the browser's half of that agreement. */
function signatureOf(findings: readonly Finding[]): string {
  const tally = new Map<string, number>();
  for (const f of findings) {
    // TWO discriminators on purpose. The generator sees forge's report and
    // drops on the rule key's tier prefix; this sees the wasm engine's and has
    // a real severity to read. They describe the same tier through different
    // producers, and nothing gates that those two producers name a tier the
    // same way — so this drops on either, and a disagreement between them
    // costs a state's lookup rather than every state's.
    if (f.severity === "fyi" || f.rule.startsWith("FYI")) continue;
    tally.set(f.rule, (tally.get(f.rule) ?? 0) + 1);
  }
  return [...tally.keys()]
    .sort()
    .map((rule) => `${rule}=${tally.get(rule)}`)
    .join("|");
}

/** `null` where the sweep never measured this state. The page must SAY that
 *  rather than render nothing: an absent number is indistinguishable from the
 *  two engines agreeing, which is the confusion this whole feature exists to
 *  remove. */
export function pythonFindingCount(
  findings: readonly Finding[],
  delivery: Delivery,
): number | null {
  const entry = BY_SIGNATURE.get(signatureOf(findings));
  if (!entry) return null;
  const override = (entry.when_cell_is ?? []).find(holds(delivery));
  return override ? override.python : entry.python;
}
