// GENERATED by web/scripts/sync-demo-schema.mjs — DO NOT EDIT.
// Source: rust-packages/laterite-ags4-reference/data/ags_dictionary.json
// (edition 4.2). Regenerate: npm run sync-demo-schema

export type DemoHeading = {
  /** The AGS4 heading, e.g. `SAMP_TOP`. */
  readonly name: string;
  /** True when the dictionary marks it KEY — the ◆ marker and the pinned
   *  column edge both key off this, and so does the parent-match tuple. */
  readonly key: boolean;
  /** The AGS TYPE the file declares, e.g. `2DP`. */
  readonly type: string;
  /** The unit, or "" where the dictionary gives none. */
  readonly unit: string;
  readonly description: string;
};

export type DemoGroup = {
  readonly code: string;
  /** The dictionary's parent, which is what draws the chain. */
  readonly parent: string | null;
  readonly description: string;
  readonly headings: readonly DemoHeading[];
};

export const DEMO_GROUPS: readonly DemoGroup[] = [
  {
    code: "PROJ",
    parent: null,
    description: "Project Information",
    headings: [
      { name: "PROJ_ID", key: true, type: "ID", unit: "", description: "Project identifier" },
      { name: "PROJ_NAME", key: false, type: "X", unit: "", description: "Project title" },
      { name: "PROJ_CLNT", key: false, type: "X", unit: "", description: "Client organisation name" },
    ],
  },
  {
    code: "LOCA",
    parent: "PROJ",
    description: "Location Details",
    headings: [
      { name: "LOCA_ID", key: true, type: "ID", unit: "", description: "Location identifier" },
      { name: "LOCA_TYPE", key: false, type: "PA", unit: "", description: "Type of activity" },
      { name: "LOCA_GL", key: false, type: "2DP", unit: "m", description: "Ground level relative to datum of location or start of traverse" },
      { name: "LOCA_REM", key: false, type: "X", unit: "", description: "General remarks" },
      { name: "LOCA_FDEP", key: false, type: "2DP", unit: "m", description: "Final depth" },
    ],
  },
  {
    code: "SAMP",
    parent: "LOCA",
    description: "Sample Information",
    headings: [
      { name: "LOCA_ID", key: true, type: "ID", unit: "", description: "Location identifier" },
      { name: "SAMP_TOP", key: true, type: "2DP", unit: "m", description: "Depth to top of sample" },
      { name: "SAMP_REF", key: true, type: "X", unit: "", description: "Sample reference" },
      { name: "SAMP_TYPE", key: true, type: "PA", unit: "", description: "Sample type" },
      { name: "SAMP_ID", key: true, type: "ID", unit: "", description: "Sample unique identifier" },
    ],
  },
  {
    code: "LLPL",
    parent: "SAMP",
    description: "Liquid and Plastic Limit Tests",
    headings: [
      { name: "LOCA_ID", key: true, type: "ID", unit: "", description: "Location identifier" },
      { name: "SAMP_TOP", key: true, type: "2DP", unit: "m", description: "Depth to top of sample" },
      { name: "SAMP_REF", key: true, type: "X", unit: "", description: "Sample reference" },
      { name: "SAMP_TYPE", key: true, type: "PA", unit: "", description: "Sample type" },
      { name: "SAMP_ID", key: true, type: "ID", unit: "", description: "Sample unique identifier" },
      { name: "SPEC_REF", key: true, type: "X", unit: "", description: "Specimen reference" },
      { name: "SPEC_DPTH", key: true, type: "2DP", unit: "m", description: "Depth to top of test specimen" },
      { name: "LLPL_LL", key: false, type: "0DP", unit: "%", description: "Liquid limit" },
      { name: "LLPL_PL", key: false, type: "XN", unit: "%", description: "Plastic limit" },
    ],
  },
  {
    code: "TRAN",
    parent: null,
    description: "Data File Transmission Information / Data Status",
    headings: [
      { name: "TRAN_ISNO", key: true, type: "X", unit: "", description: "Issue sequence reference" },
      { name: "TRAN_DATE", key: false, type: "DT", unit: "yyyy-mm-dd", description: "Date of production of data file" },
      { name: "TRAN_PROD", key: false, type: "X", unit: "", description: "Data file producer" },
      { name: "TRAN_STAT", key: false, type: "X", unit: "", description: "Status of data within submission" },
      { name: "TRAN_AGS", key: false, type: "X", unit: "", description: "AGS Edition Reference" },
      { name: "TRAN_RECV", key: false, type: "X", unit: "", description: "Data file recipient" },
    ],
  },
] as const;

/** The KEY headings of `code`, in dictionary order — the tuple Rule 10c
 *  matches a child row against its parent by. */
export function keyHeadings(code: string): readonly string[] {
  const g = DEMO_GROUPS.find((x) => x.code === code);
  return g ? g.headings.filter((h) => h.key).map((h) => h.name) : [];
}
