"""Cross-surface version drift-gate (#372, split into two tiers by #153).

There are TWO version numbers, and this asserts each is internally consistent.
It does NOT assert they equal each other — that they are free to differ is the
entire point of the split.

    PRODUCT  the wheel, the umbrella, the compat prefix, the npm package, `lat`.
             What `pip install laterite` and `npm i laterite` resolve.
    ENGINE   the Rust workspace and the crates.io tier. What
             `cargo add laterite-ags4-validator` resolves.

They were one number until 2026-08-01, and the coupling had a cost with a name.
`laterite-ags4-wasm` is `version.workspace = true`, so shipping a browser-only
patch meant bumping the number every surface shared — twice, at 0.8.1 and 0.8.2,
neither of which PyPI ever saw. Those wheel versions exist in git history and on
no registry. See `ags-wiki/design/dec-rust-api-crates-io.md`.

It reads the SOURCE files (no built wheel, no installed package), so a bad bump
fails here before anything is compiled or published.

Deliberately NOT gated (documented so their absence isn't mistaken for a hole):
- `web/src/wasm/package.json` and `web/src/wasm-tokenizer/package.json` —
  BOTH gitignored `wasm-pack` output, regenerated from the crate version at build
  time. Neither is a tracked stamp; a copy in a working tree is whatever was last
  built there and can be arbitrarily stale (one was found at 0.7.0 against a 0.9.0
  tree, which is a build artefact's business and not drift).
- `rust-packages/laterite-node/index.js` — the napi loader's baked-in version
  literals ARE stamped (by `bump-version.sh`), but the authoritative gate is the
  node CI job's own drift guard (`napi build` + `git diff --exit-code`), which
  asserts the committed loader matches a fresh build — a stronger check than a
  string compare here would be.
- `uv.lock` / `Cargo.lock` / `package-lock.json` — regenerated by the bump
  script; not a source of truth.
- `rust-packages/laterite/Cargo.toml` — the facade carries its own 0.1.x on
  purpose. It is outside both tiers until it reaches feature parity with the
  Python and Node surfaces, at which point it joins PRODUCT. Asserted below as an
  explicit, dated exemption rather than left silent.
- The `laterite_ags4` DuckDB extension — a SEPARATE repo (`niko86/laterite-duckdb`)
  that tracks the laterite version but releases on its own tag, so it
  legitimately lags in the window between a laterite release and its own; a hard
  cross-repo equality gate would false-fire. Its unification is enforced instead
  by `scripts/release.sh <version>` (version is a required arg) + that repo's CI
  asserting its `Cargo.toml` == `description.yml`, per RELEASING.md.

Not yet gated, and it is the one real hole: that every product embeds the SAME
engine. `ENGINE_FINGERPRINT` exists in the validator and is the right value to
assert on, but it is not plumbed through `laterite-py`, `laterite-node` or the
wasm surface yet. Until it is, "same engine everywhere" holds because every
product is built from one tree, which is true and unasserted.
"""

import json
import re
import tomllib
from pathlib import Path

_REPO = Path(__file__).resolve().parents[1]


def _toml(rel: str) -> dict:
    return tomllib.loads((_REPO / rel).read_text())


#: The shipped wheel's version — the value every other PRODUCT stamp mirrors.
PRODUCT = _toml("packages/laterite/pyproject.toml")["project"]["version"]

#: `[workspace.package].version` — inherited by every member crate that says
#: `version.workspace = true`, and declared on the published crates' siblings.
ENGINE = _toml("rust-packages/Cargo.toml")["workspace"]["package"]["version"]


# --- PRODUCT -------------------------------------------------------------


def test_product_is_clean_pep440() -> None:
    # A `+local` segment is rejected by PyPI on upload; guard the release here.
    assert "+" not in PRODUCT, (
        f"shipped version {PRODUCT!r} carries a PEP 440 local segment"
    )


def test_umbrella_pyproject_matches_product() -> None:
    root = _toml("pyproject.toml")
    assert root["project"]["version"] == PRODUCT
    # bump-my-version's own bookkeeping value must not lag either.
    assert root["tool"]["bumpversion"]["current_version"] == PRODUCT


def test_node_package_and_native_deps_match_product() -> None:
    pkg = json.loads((_REPO / "rust-packages/laterite-node/package.json").read_text())
    assert pkg["version"] == PRODUCT, (
        f"npm package version {pkg['version']!r} != shipped wheel {PRODUCT!r}"
    )

    # The `@laterite/native-*` pins are deliberately ABSENT from the committed
    # manifest, and this asserts they stay absent. `napi pre-publish` rewrites
    # the whole optionalDependencies block at publish time from `napi.targets`
    # and the package version, so a committed copy can only be redundant — and
    # it was actively harmful: bump-version.sh regenerates package-lock.json
    # immediately after stamping, when version N is not yet on npm, so npm wrote
    # `{"optional": true}` placeholders that stopped satisfying the manifest the
    # moment N published. That broke `npm ci` on main after 0.8.0 (#155).
    committed = [
        k
        for k in pkg.get("optionalDependencies", {})
        if k.startswith("@laterite/native-")
    ]
    assert not committed, (
        f"{committed} pinned in package.json — remove them. napi writes these at "
        "publish time; committing them makes the lockfile unresolvable until the "
        "version is published, which breaks `npm ci` (#155)"
    )

    # What DOES need guarding is the input napi derives those pins from: every
    # platform the release builds must be a declared napi target, or that
    # platform ships with no addon to resolve.
    targets = set(pkg["napi"]["targets"])
    expected = {
        "x86_64-unknown-linux-gnu",
        "aarch64-apple-darwin",
        "x86_64-pc-windows-msvc",
    }
    assert targets == expected, (
        f"napi.targets {sorted(targets)} != the release build matrix "
        f"{sorted(expected)} — release.yml's build-node matrix and this list "
        "must agree, or a platform publishes without its native addon"
    )


def test_compat_version_prefix_matches_product() -> None:
    # compat.py's __version__ is an f-string literal `"{ver}+compat.python-ags4.…"`
    # — the release prefix is a hardcoded literal a bump must keep current.
    src = (_REPO / "packages/laterite/python/laterite/compat.py").read_text()
    m = re.search(r'__version__ = f"(\d+\.\d+\.\d+[^"+]*)\+compat\.python-ags4\.', src)
    assert m, "could not find compat.__version__ f-string literal"
    assert m.group(1) == PRODUCT, (
        f"compat.py version prefix {m.group(1)!r} != shipped wheel {PRODUCT!r}"
    )


def test_cli_crate_matches_product_not_engine() -> None:
    """`lat` is a product, so the binary carries the number people install by.

    `lat` exists twice — `rust-packages/laterite-cli` and the wheel's `lat`
    console script (`laterite._cli:main`), which is byte-faithful to it. clap
    renders `--version` from `CARGO_PKG_VERSION`, so leaving the crate on
    `version.workspace = true` would make the two report different numbers for
    the same command the first time the tiers diverge.
    """
    cli = _toml("rust-packages/laterite-cli/Cargo.toml")["package"]
    assert cli.get("version") == PRODUCT, (
        f"laterite-cli is {cli.get('version')!r}, not the product {PRODUCT!r} — "
        "`lat --version` would disagree with the wheel's `lat`"
    )


# --- ENGINE --------------------------------------------------------------


def test_engine_dependency_versions_match_engine() -> None:
    """The `[workspace.dependencies]` versions track `[workspace.package]`.

    These exist so `cargo package` will accept the crates at all — publishing strips
    `path`, so a dependency with no version requirement is rejected outright. They
    are inert locally (the path still wins), which is exactly what makes them easy
    to leave behind: nothing in a normal build or test run reads them, so a stale
    one would surface only at publish, as crates pinned to a version that no longer
    matches the engine they shipped with.

    They ride the same `version = "{current_version}"` substitution as
    `workspace.package.version` — same file, and bump-my-version rewrites every
    occurrence, not just the first. This test is what says that out loud, so the
    lockstep is asserted rather than assumed to hold.
    """
    deps = _toml("rust-packages/Cargo.toml")["workspace"].get("dependencies", {})
    ours = {n: s for n, s in deps.items() if n.startswith("laterite")}
    assert ours, "no in-workspace [workspace.dependencies] entries found at all"
    for name, spec in ours.items():
        assert spec.get("version") == ENGINE, (
            f"[workspace.dependencies] {name} is pinned to {spec.get('version')!r}, "
            f"not the engine {ENGINE!r} — a publish would declare a dependency "
            "on a version that is not this engine"
        )
        assert "path" in spec, (
            f"[workspace.dependencies] {name} lost its `path` — the local build "
            "would resolve it from crates.io instead of the tree beside it"
        )


def test_engine_bump_config_tracks_the_workspace() -> None:
    """`tools/release/engine-version.toml` is the engine's bookkeeping value.

    It is a second file holding the same number, which is exactly the shape that
    goes stale — and it goes stale silently, because nothing in a build reads it.
    A wrong value here does not fail until the next engine bump computes the new
    version from the wrong old one.
    """
    cfg = _toml("tools/release/engine-version.toml")["tool"]["bumpversion"]
    assert cfg["current_version"] == ENGINE, (
        f"engine-version.toml says {cfg['current_version']!r} but the workspace is "
        f"{ENGINE!r} — the next `bump-version.sh engine` would bump from the wrong base"
    )


# --- the seam itself -----------------------------------------------------


def test_the_two_tiers_are_stamped_from_different_configs() -> None:
    """Neither bump config may stamp the other tier's files.

    The split is only real if the two stamping paths are disjoint. An entry added
    to the wrong config would silently restore the lockstep — and it would look
    like it was working, because the two numbers are equal today.
    """
    product_files = {
        f["filename"] for f in _toml("pyproject.toml")["tool"]["bumpversion"]["files"]
    }
    engine_files = {
        f["filename"]
        for f in _toml("tools/release/engine-version.toml")["tool"]["bumpversion"][
            "files"
        ]
    }

    assert "rust-packages/Cargo.toml" not in product_files, (
        "the product bump would stamp the Rust workspace — that is the coupling "
        "that produced the phantom 0.8.1/0.8.2"
    )
    assert "rust-packages/Cargo.toml" in engine_files, (
        "nothing stamps the Rust workspace — an engine bump would move no crate"
    )
    assert not (product_files & engine_files), (
        f"both configs stamp {sorted(product_files & engine_files)} — one file "
        "cannot belong to two independent version lines"
    )


def test_the_facade_is_outside_both_tiers() -> None:
    """`rust-packages/laterite` carries its own 0.1.x, on purpose and for now.

    It is independent because it is INCOMPLETE — 0.1 is read/validate/write, with
    diff, merge, typed cells and the indexed scan still to come. When it reaches
    parity with the Python and Node surfaces it joins the PRODUCT line, jumping
    0.1.x straight onto that number. Until then this records the exemption, so
    "not asserted" is a decision in the file rather than an omission.
    """
    facade = _toml("rust-packages/laterite/Cargo.toml")["package"]["version"]
    assert isinstance(facade, str), (
        "the facade must carry a literal version, not inherit one — inheriting "
        "would silently put it back on the engine line"
    )
    assert facade.startswith("0.1."), (
        f"the facade is at {facade!r}. If it has reached parity and joined the "
        "product line, update this test and the design page together — the jump "
        "off 0.1.x is a one-way door and should not happen by accident"
    )
