"""Cross-surface version drift-gate (#372, split into two tiers by #153).

There are TWO version numbers, and this asserts each is internally consistent.
It does NOT assert they equal each other — that they are free to differ is the
entire point of the split.

    PRODUCT  the wheel, the umbrella, the compat prefix, the npm package, `lat`.
             What `pip install laterite` and `npm i laterite` resolve.
    ENGINE   the published crates, versioned PER-CRATE since #781. What
             `cargo add laterite-ags4-validator` resolves.

They were one number until 2026-08-01, and the coupling had a cost with a name.
`laterite-ags4-wasm` is `version.workspace = true`, so shipping a browser-only
patch meant bumping the number every surface shared — twice, at 0.8.1 and 0.8.2,
neither of which PyPI ever saw. Those wheel versions exist in git history and on
no registry. See `ags-wiki/design/dec-rust-api-crates-io.md`.

It reads the SOURCE files (no built wheel, no installed package), so a bad bump
fails here before anything is compiled or published.

Deliberately NOT gated (documented so their absence isn't mistaken for a hole):
- `web/src/wasm/package.json` and `web/src/wasm-tokenizer/package.json` —
  BOTH gitignored `wasm-pack` output, regenerated from the crate version at build
  time. Neither is a tracked stamp; a copy in a working tree is whatever was last
  built there and can be arbitrarily stale (one was found at 0.7.0 against a 0.9.0
  tree, which is a build artefact's business and not drift).
- `rust-packages/laterite-node/index.js` — the napi loader's baked-in version
  literals ARE stamped (by `bump-version.sh`), but the authoritative gate is the
  node CI job's own drift guard (`napi build` + `git diff --exit-code`), which
  asserts the committed loader matches a fresh build — a stronger check than a
  string compare here would be.
- `uv.lock` / `Cargo.lock` / `package-lock.json` — regenerated by the bump
  script; not a source of truth.
- `rust-packages/laterite/Cargo.toml` — the facade carries its own 0.1.x on
  purpose. It is outside both tiers until it reaches feature parity with the
  Python and Node surfaces, at which point it joins PRODUCT. Asserted below as an
  explicit, dated exemption rather than left silent.
- The `laterite_ags4` DuckDB extension — a SEPARATE repo (`niko86/laterite-duckdb`)
  that tracks the laterite version but releases on its own tag, so it
  legitimately lags in the window between a laterite release and its own; a hard
  cross-repo equality gate would false-fire. Its unification is enforced instead
  by `scripts/release.sh <version>` (version is a required arg) + that repo's CI
  asserting its `Cargo.toml` == `description.yml`, per RELEASING.md.

Every product now REPORTS the engine it carries — `engine_fingerprint()` on the
wheel, the npm package and the browser build, from the validator's build-time
digest. What is still missing is a gate that compares those values *across* built
surfaces: within this repo they are trivially equal, because everything compiles
the same crate from one tree. The comparison that would mean something runs
against built artefacts, which is `laterite-ags4-xcheck`'s job, and it lands
there rather than here.
"""

import json
import re
import tomllib
from pathlib import Path

import yaml

_REPO = Path(__file__).resolve().parents[1]


def _toml(rel: str) -> dict:
    return tomllib.loads((_REPO / rel).read_text())


#: The shipped wheel's version — the value every other PRODUCT stamp mirrors.
PRODUCT = _toml("packages/laterite/pyproject.toml")["project"]["version"]

#: `[workspace.package].version` — since #781 inherited only by the UNPUBLISHED
#: members (QA tools, cliutil, censor…); the published crates version per-crate.
WORKSPACE = _toml("rust-packages/Cargo.toml")["workspace"]["package"]["version"]


def _crate_version(crate: str) -> str | None:
    """The crate's OWN `version`, None if it inherits the workspace one."""
    v = _toml(f"rust-packages/{crate}/Cargo.toml")["package"].get("version")
    return None if isinstance(v, dict) else v


#: Every published crate's own version — the per-crate engine tier (#781).
ENGINE_CRATES = {
    name: _crate_version(name)
    for name in sorted(
        d.name
        for d in (_REPO / "rust-packages").iterdir()
        if (d / "Cargo.toml").exists()
        and "publish = false" not in (d / "Cargo.toml").read_text()
        and d.name != "laterite"  # the facade is its own line, asserted separately
    )
}


# --- PRODUCT -------------------------------------------------------------


def test_product_is_clean_pep440() -> None:
    # A `+local` segment is rejected by PyPI on upload; guard the release here.
    assert "+" not in PRODUCT, (
        f"shipped version {PRODUCT!r} carries a PEP 440 local segment"
    )


def test_umbrella_pyproject_matches_product() -> None:
    root = _toml("pyproject.toml")
    assert root["project"]["version"] == PRODUCT
    # bump-my-version's own bookkeeping value must not lag either.
    assert root["tool"]["bumpversion"]["current_version"] == PRODUCT


def test_node_package_and_native_deps_match_product() -> None:
    pkg = json.loads((_REPO / "rust-packages/laterite-node/package.json").read_text())
    assert pkg["version"] == PRODUCT, (
        f"npm package version {pkg['version']!r} != shipped wheel {PRODUCT!r}"
    )

    # The `@laterite/native-*` pins are deliberately ABSENT from the committed
    # manifest, and this asserts they stay absent. `napi pre-publish` rewrites
    # the whole optionalDependencies block at publish time from `napi.targets`
    # and the package version, so a committed copy can only be redundant — and
    # it was actively harmful: bump-version.sh regenerates package-lock.json
    # immediately after stamping, when version N is not yet on npm, so npm wrote
    # `{"optional": true}` placeholders that stopped satisfying the manifest the
    # moment N published. That broke `npm ci` on main after 0.8.0 (#155).
    committed = [
        k
        for k in pkg.get("optionalDependencies", {})
        if k.startswith("@laterite/native-")
    ]
    assert not committed, (
        f"{committed} pinned in package.json — remove them. napi writes these at "
        "publish time; committing them makes the lockfile unresolvable until the "
        "version is published, which breaks `npm ci` (#155)"
    )

    # What DOES need guarding is the input napi derives those pins from: every
    # platform the release builds must be a declared napi target, or that
    # platform ships with no addon to resolve.
    # READ the matrix; do not restate it. This used to compare against a literal
    # set written here, while its own message claimed it compared against
    # release.yml — a third hand-maintained copy of the list, checked against
    # nothing. Adding aarch64-linux for the beta is what exposed it: the target
    # went into package.json AND release.yml, and this still failed, because the
    # only list it actually knew about was its own.
    workflow = yaml.safe_load(
        (_REPO / ".github" / "workflows" / "release.yml").read_text(encoding="utf-8")
    )
    expected = {
        entry["target"]
        for entry in workflow["jobs"]["build-node"]["strategy"]["matrix"]["include"]
    }
    assert expected, "no targets parsed from release.yml's build-node matrix"

    targets = set(pkg["napi"]["targets"])
    assert targets == expected, (
        f"napi.targets {sorted(targets)} != release.yml's build-node matrix "
        f"{sorted(expected)} — they must agree, or a platform publishes without "
        "its native addon (or napi declares an optional dep nobody publishes)"
    )


def test_compat_version_prefix_matches_product() -> None:
    # compat.py's __version__ is an f-string literal `"{ver}+compat.python-ags4.…"`
    # — the release prefix is a hardcoded literal a bump must keep current.
    src = (_REPO / "packages/laterite/python/laterite/compat/_impl.py").read_text()
    m = re.search(r'__version__ = f"(\d+\.\d+\.\d+[^"+]*)\+compat\.python-ags4\.', src)
    assert m, "could not find compat.__version__ f-string literal"
    assert m.group(1) == PRODUCT, (
        f"compat.py version prefix {m.group(1)!r} != shipped wheel {PRODUCT!r}"
    )


#: Crates that SHIP AS A PRODUCT and therefore carry the product number, not the
#: engine's. Each is a product wearing a crate; none is on crates.io. The value is
#: what breaks if it is wrong, because "it should match" is not a reason anyone
#: can act on at 2am.
PRODUCT_CRATES = {
    "laterite-cli": (
        "`lat --version` (clap reads CARGO_PKG_VERSION) would disagree with the "
        "wheel's `lat` console script, which is the same command"
    ),
    "laterite-py": (
        "maturin takes the wheel version from packages/laterite/pyproject.toml, so "
        "the cdylib would carry a different number than the wheel containing it"
    ),
    "laterite-node": (
        "its `version()` export is CARGO_PKG_VERSION, so npm callers would be told "
        "a version that is not the package they installed"
    ),
    "laterite-ags4-wasm": (
        "wasm-pack writes the published manifest FROM this line and release.yml "
        "asserts the `wasm-v<tag>` matches it — the release fails its own tag check"
    ),
}


def test_product_crates_are_on_the_product_number() -> None:
    """A crate that ships as a product carries the number people install by.

    All four were left on `version.workspace = true` when the tiers split (#202),
    which was harmless for exactly as long as the two numbers stayed equal — and
    would have broken at the first product-only release, starting with the wasm
    tag check.
    """
    for crate, consequence in PRODUCT_CRATES.items():
        got = _toml(f"rust-packages/{crate}/Cargo.toml")["package"].get("version")
        assert got == PRODUCT, (
            f"{crate} is {got!r}, not the product {PRODUCT!r}"
            + (" (it inherits the workspace version)" if got is None else "")
            + f" — {consequence}"
        )


def test_doc_example_outputs_carry_no_superseded_product_version() -> None:
    """A docs example that PRINTS the version pins it in its committed `.out`.

    `web/docs-site/examples/wasm/ex01_init.mjs` ends in `console.log(version())`,
    so its `.out` is a version stamp in all but name — and `bump-version.sh` did
    not touch it. The `gen_doc_outputs --check` gate caught it, but that gate
    lives in the `ts-lint` job, so 0.10.1 (#242) went red on a TypeScript check
    for a reason that had nothing to do with TypeScript or with the release's
    content. It surfaced then and not earlier only because the gate landed in
    #225/#228, after 0.10.0 — 0.10.1 was the first bump to meet it (#243).

    Asserted by SUPERSEDED version rather than by naming the file: any example on
    any surface that starts printing the version is covered the day it lands, and
    nobody has to remember a list. Past releases come from changelog.json, which
    `bump-version.sh` rolls BEFORE it runs this test, so the version just stamped
    is already current and only genuinely stale outputs match.

    Deliberately not "every X.Y.Z equals PRODUCT": the AGS edition `4.1.1` is an
    X.Y.Z and appears in five of these outputs. This asks whether a LATERITE
    version is stale, which is the actual question.
    """
    superseded = {
        r["version"]
        for r in json.loads((_REPO / "changelog.json").read_text())["releases"]
        if r["version"] != PRODUCT
    }
    stale: list[str] = []
    for out in sorted((_REPO / "web" / "docs-site" / "examples").rglob("*.out")):
        text = out.read_text(encoding="utf-8")
        stale.extend(
            f"{out.relative_to(_REPO)} still says {old}"
            for old in sorted(superseded)
            # Bounded so `0.1.0` cannot match inside `0.1.01` or `v0.1.0-rc`.
            if re.search(rf"(?<![\w.]){re.escape(old)}(?![\w.])", text)
        )
    assert not stale, (
        "docs example output pins a superseded product version:\n  "
        + "\n  ".join(stale)
        + f"\n\nThe current product version is {PRODUCT}. `bump-version.sh product` "
        "restamps these; if you bumped by hand, re-run it or regenerate with\n"
        "    uv run --no-project python tools/gen_doc_outputs.py --surface <surface>"
    )


#: A docs example's PEP 723 header, and the laterite pin inside it. The header is
#: what makes an example `uv run`-able by a reader who has not cloned anything —
#: it declares its own interpreter floor and dependencies, so the file installs
#: what it needs and runs.
_PEP723 = re.compile(r"^# /// script\n(?P<body>(?:^#.*\n)*?)^# ///$", re.M)
#: A laterite requirement in a PEP 723 dependency list, whatever shape it takes:
#: the extras group and the version specifier are both captured rather than
#: assumed, so `>=`, `~=` and a bare `"laterite"` are all VISIBLE to the gate
#: instead of simply not matching it. Matching `laterite==(version)` was the first
#: cut and it could not see the one file that motivated the gate.
#:
#: The extras group is not decoration either. `pip install laterite` is polars +
#: duckdb; pandas lives behind `[compat]`, so an example that imports pandas or
#: touches `laterite.compat` must ask for `laterite[compat]` or die under
#: `uv run` with ModuleNotFoundError — the very failure the header prevents.
_LATERITE_DEP = re.compile(r'"laterite(?P<extras>\[[\w,]+\])?(?P<spec>[^"]*)"')
_REQUIRES_PY = re.compile(r'requires-python\s*=\s*"(?P<spec>[^"]+)"')

#: Both example trees. `web/docs-site/examples` is the docs corpus; the root
#: `examples/` holds the marimo tour, which is where this rot was first seen —
#: it asked for `laterite>=0.5.0` at product 0.10.1, five minors of compatibility
#: it claimed and nobody had tested.
_EXAMPLE_TREES = ("web/docs-site/examples", "examples")


def _example_headers() -> list[tuple[Path, str]]:
    return [
        (p, m.group("body"))
        for tree in _EXAMPLE_TREES
        for p in sorted((_REPO / tree).rglob("*.py"))
        if (m := _PEP723.search(p.read_text(encoding="utf-8")))
    ]


def test_example_pep723_pins_track_the_product() -> None:
    """A `uv run`-able example pins the laterite it is known to run at.

    The pin is the point — it says "this example was green against THIS wheel",
    which is worth more than a floating requirement that silently starts resolving
    something the snippet was never checked against. But a pin is also a version
    site, and version sites in documentation are exactly what rots: `COMPAT.md`
    sat at 0.1.0 for nine releases, and `examples/laterite_tour.py` asked for
    `laterite>=0.5.0` at product 0.10.1 — five minors of compatibility it claimed
    and nobody had ever tested.

    THE ASSERTION IS ON THE WHOLE SPECIFIER, not on the version inside a `==`.
    The first cut of this gate matched `laterite==(version)` and compared the
    version, which quietly passes anything that is not an exact pin at all: the
    tour's own `>=0.5.0` produced no match and therefore no finding, so the one
    file that motivated the gate was the one file it could not see. A bare
    `"laterite"` escaped the same way. Now the specifier must be exactly
    `==<PRODUCT>`, so `>=`, `~=` and no-specifier are failures rather than
    absences.

    Discovery, not a list: any example that grows a header is covered the day it
    lands, across both example trees. `tools/release/bump-version.sh` restamps
    them, and this is what says so.

    Falsify by loosening any header to `laterite>=…`, by dropping the specifier,
    or by pinning a version that is not the shipped one.
    """
    headers = _example_headers()
    assert headers, "no PEP 723 headers found — the discovery pattern has gone stale"
    wrong = [
        f"{p.relative_to(_REPO)} requires laterite{m.group('extras') or ''}"
        f"{m.group('spec') or ' (no specifier)'}"
        for p, body in headers
        if (m := _LATERITE_DEP.search(body)) and m.group("spec") != f"=={PRODUCT}"
    ]
    assert not wrong, (
        "a runnable docs example pins a laterite that is not the shipped one:\n  "
        + "\n  ".join(wrong)
        + f"\n\nThe product version is {PRODUCT}. `bump-version.sh product` restamps "
        "these; if you edited one by hand, put it back."
    )


def test_example_pep723_python_floor_matches_the_wheel() -> None:
    """…and the interpreter floor it declares is the wheel's real floor.

    The same defect `test_wheel_claims_faithful.py` was written for, one tree
    along: a header claiming `>=3.14` would send a 3.12 reader — for whom the
    abi3-py312 wheel installs perfectly — away with a resolver error.
    """
    floor = _toml("packages/laterite/pyproject.toml")["project"]["requires-python"]
    wrong = [
        f"{p.relative_to(_REPO)} declares requires-python {m.group('spec')!r}"
        for p, body in _example_headers()
        if (m := _REQUIRES_PY.search(body)) and m.group("spec") != floor
    ]
    assert not wrong, (
        "a runnable docs example declares an interpreter floor the wheel does not:\n  "
        + "\n  ".join(wrong)
        + f"\n\nThe wheel's own requires-python is {floor!r}."
    )


#: READMEs that ride out with a published artifact: the crates.io tarballs
#: (`include` carries `/README.md`), the npm package wasm-pack assembles, and
#: the PyPI wheel. Scoped to these deliberately rather than to every tracked
#: `.md`, which was the first design and is wrong — Markdown in this repo is
#: FULL of legitimately superseded versions. `CHANGELOG.md` is nothing else;
#: `ags-wiki/design/` records what shipped when; `RELEASING*.md` uses past
#: releases as worked examples. Measured before choosing the scope: across every
#: tracked `.md`, 21 files carry a superseded version and 20 of them are correct
#: history. Only the shipped READMEs are a claim about NOW, made to someone who
#: cannot see this repo, on a page that cannot be corrected once they have read it.
def _shipped_readmes() -> list[Path]:
    return sorted(
        [
            *(_REPO / "rust-packages").glob("*/README.md"),
            *(_REPO / "packages").glob("*/README.md"),
        ]
    )


def test_shipped_readmes_carry_no_superseded_version() -> None:
    """A README that ships to a registry must not name a version that has moved.

    `laterite-ags4-wasm/README.md` showed `version(); // "0.8.2"` at product
    0.10.1 — three releases stale, in a code block presented as what the API
    returns, on a page wasm-pack copies into the published npm package. Nothing
    caught it: `bump-version.sh product` restamps manifests, `compat.py` and the
    docs-site `.out` files, and the sibling gate above scans only `**/*.out`.

    Asserted by SUPERSEDED version, matching that sibling: any README that starts
    naming a version is covered the day it lands, with no list to maintain.

    A live tier's number is never "superseded", even when it collides with a past
    product release — an engine README citing its own crate's current version is
    correct, and a gate that flagged it would be wrong in the direction that gets
    gates deleted. Since #781 the engine is not one number: every published
    crate's own version is live.
    """
    facade = _toml("rust-packages/laterite/Cargo.toml")["package"]["version"]
    live = {PRODUCT, WORKSPACE, facade} | {v for v in ENGINE_CRATES.values() if v}
    superseded = {
        r["version"]
        for r in json.loads((_REPO / "changelog.json").read_text())["releases"]
        if r["version"] not in live
    }
    stale: list[str] = []
    for readme in _shipped_readmes():
        text = readme.read_text(encoding="utf-8")
        stale.extend(
            f"{readme.relative_to(_REPO)} still says {old}"
            for old in sorted(superseded)
            # Bounded so `0.1.0` cannot match inside `0.1.01` or `v0.1.0-rc`.
            if re.search(rf"(?<![\w.]){re.escape(old)}(?![\w.])", text)
        )
    assert not stale, (
        "a README that ships to a registry names a superseded version:\n  "
        + "\n  ".join(stale)
        + f"\n\nLive: product {PRODUCT}, facade {facade}, engine crates {sorted({v for v in ENGINE_CRATES.values() if v})}. "
        "These pages are permanent once published — fix before the next release."
    )


# --- ENGINE --------------------------------------------------------------


def test_engine_dependency_versions_match_engine() -> None:
    """Each `[workspace.dependencies]` version equals THAT crate's own version.

    The entries exist so `cargo package` will accept the crates at all —
    publishing strips `path`, so a dependency with no version requirement is
    rejected outright. They are inert locally (the path still wins), which is
    exactly what makes them easy to leave behind: nothing in a normal build or
    test run reads them, so a stale one would surface only at publish, as a
    crate pinned to a sibling version that is not what the tree beside it holds.

    Under lockstep this asserted one shared number. Since #781 it asserts the
    per-crate PAIR: `bump_crate.py` rewrites a crate's manifest and its
    workspace entry together, and this is the gate that fires if either is
    ever moved alone.
    """
    deps = _toml("rust-packages/Cargo.toml")["workspace"].get("dependencies", {})
    ours = {n: s for n, s in deps.items() if n.startswith("laterite")}
    assert ours, "no in-workspace [workspace.dependencies] entries found at all"
    for name, spec in ours.items():
        own = _crate_version(name)
        assert own is not None, (
            f"{name} is in [workspace.dependencies] but inherits the workspace "
            "version — a published crate carries its OWN version since #781"
        )
        assert spec.get("version") == own, (
            f"[workspace.dependencies] {name} is pinned to {spec.get('version')!r} "
            f"but the crate's own manifest says {own!r} — a publish would declare "
            "a dependency on a version that is not what ships. bump_crate.py "
            "moves the pair together; something moved one alone"
        )
        assert "path" in spec, (
            f"[workspace.dependencies] {name} lost its `path` — the local build "
            "would resolve it from crates.io instead of the tree beside it"
        )


def test_surface_engine_pins_record_what_ships() -> None:
    """Each product surface pins its published engine deps: `{ path, version }`.

    #781 step 5, and the last of its sequence. The surfaces compile engine
    SOURCE (the path always wins locally), so before these pins the engine
    version was invisible at the consuming edge: "which engines did wheel X
    ship?" had no answer in the manifest that built it. With the pin, the
    manifest at any product tag IS the record — and cargo enforces the honest
    half by itself, refusing to resolve a path crate the pin no longer admits.

    Three assertions, because each fails differently:
    * a published engine dep with NO version records nothing — the gap this
      test exists to close;
    * a pin unequal to the crate's own version is drift — `bump_crate.py`
      rewrites every member pin when it moves a crate, so an unequal pin means
      something was moved by hand;
    * an UNPUBLISHED laterite dep (excel, censor, cliutil) must NOT carry a
      version — there is no published version to record, so a number there
      would be an invention that starts lying at its first divergence.
    """
    published = {**ENGINE_CRATES}
    for surface in PRODUCT_CRATES:
        deps = _toml(f"rust-packages/{surface}/Cargo.toml").get("dependencies", {})
        ours = {n: s for n, s in deps.items() if n.startswith("laterite")}
        assert ours, f"{surface}: no laterite deps parsed — the discovery went stale"
        for name, spec in ours.items():
            assert isinstance(spec, dict), (
                f"{surface}: {name} is a bare string dep — engine deps here are "
                "path deps into the tree beside them"
            )
            if name in published:
                own = published[name]
                assert spec.get("version") == own, (
                    f"{surface}: {name} pins {spec.get('version')!r} but the crate "
                    f"is {own!r} — the manifest would record engine versions the "
                    "product did not ship. bump_crate.py moves every member pin "
                    "with the crate; something was edited alone"
                )
                assert "path" in spec, (
                    f"{surface}: {name} lost its `path` — the surface would compile "
                    "the crates.io copy instead of the tree beside it"
                )
            else:
                assert "version" not in spec, (
                    f"{surface}: {name} is not a published crate, so its "
                    f"version pin {spec.get('version')!r} records nothing that "
                    "exists on a registry — remove it"
                )


# --- the seam itself -----------------------------------------------------


def test_the_two_tiers_are_stamped_from_different_configs() -> None:
    """The product bump may not reach the engine crates, nor the workspace.

    The split is only real if the stamping paths are disjoint. Under lockstep
    the other half of this test held `engine-version.toml` to the same
    discipline; that file is retired (#781) and the engine side is now
    `bump_crate.py`, whose write set is the crate manifest plus its
    `[workspace.dependencies]` entry — asserted per crate by
    `test_engine_dependency_versions_match_engine` above. What is left to hold
    HERE is the product config's reach: an engine path added to it would
    silently restore the lockstep, and it would look like it was working
    whenever the numbers happened to be equal.
    """
    product_files = {
        f["filename"] for f in _toml("pyproject.toml")["tool"]["bumpversion"]["files"]
    }
    for crate in PRODUCT_CRATES:
        assert f"rust-packages/{crate}/Cargo.toml" in product_files, (
            f"{crate} is asserted to carry the product version but nothing stamps "
            "it — a bump would leave it behind at the old number"
        )

    assert "rust-packages/Cargo.toml" not in product_files, (
        "the product bump would stamp the Rust workspace — that is the coupling "
        "that produced the phantom 0.8.1/0.8.2"
    )
    engine_manifests = {f"rust-packages/{name}/Cargo.toml" for name in ENGINE_CRATES}
    reached = sorted(product_files & engine_manifests)
    assert not reached, (
        f"the product bump stamps published engine crate manifest(s) {reached} — "
        "engine crates version per-crate (#781); a product entry there restores "
        "the lockstep by the back door"
    )


def test_the_facade_is_outside_both_tiers() -> None:
    """`rust-packages/laterite` carries its own 0.1.x, on purpose and for now.

    It is independent because it is INCOMPLETE — 0.1 is read/validate/write, with
    diff, merge, typed cells and the indexed scan still to come. When it reaches
    parity with the Python and Node surfaces it joins the PRODUCT line, jumping
    0.1.x straight onto that number. Until then this records the exemption, so
    "not asserted" is a decision in the file rather than an omission.
    """
    facade = _toml("rust-packages/laterite/Cargo.toml")["package"]["version"]
    assert isinstance(facade, str), (
        "the facade must carry a literal version, not inherit one — inheriting "
        "would silently put it back on the engine line"
    )
    assert facade.startswith("0.1."), (
        f"the facade is at {facade!r}. If it has reached parity and joined the "
        "product line, update this test and the design page together — the jump "
        "off 0.1.x is a one-way door and should not happen by accident"
    )
