"""Cross-surface version drift-gate (#372).

Every published surface ships one version. `bump-my-version` (driven by
`tools/release/bump-version.sh`) stamps them all in lockstep — this test is the
net that turns a *missed* surface red, the same "the release can't lie" role
`test_compat_python_ags4_pin_stays_in_sync` plays for the compat pin.

It reads the SOURCE files (no built wheel, no installed package), so a bad bump
fails here before anything is compiled or published. The canonical version is
the shipped wheel's `packages/laterite/pyproject.toml` `[project].version`;
every other tracked surface must equal it.

Deliberately NOT gated (documented so their absence isn't mistaken for a hole):
- `web/src/wasm/package.json` — gitignored; wasm-pack regenerates it from the
  crate version at build time, so it tracks the workspace version for free.
- `rust-packages/laterite-node/index.js` — the napi loader's baked-in version
  literals ARE stamped (by `bump-version.sh`), but the authoritative gate is the
  node CI job's own drift guard (`napi build` + `git diff --exit-code`), which
  asserts the committed loader matches a fresh build — a stronger check than a
  string compare here would be.
- `uv.lock` / `Cargo.lock` / `package-lock.json` — regenerated by the bump
  script; not a source of truth.
- The `laterite_ags4` DuckDB extension — a SEPARATE repo (`niko86/laterite-duckdb`)
  that tracks the laterite version but releases on its own tag, so it
  legitimately lags in the window between a laterite release and its own; a hard
  cross-repo equality gate would false-fire. Its unification is enforced instead
  by `scripts/release.sh <version>` (version is a required arg) + that repo's CI
  asserting its `Cargo.toml` == `description.yml`, per RELEASING.md.
"""

import json
import re
import tomllib
from pathlib import Path

_REPO = Path(__file__).resolve().parents[1]


def _toml(rel: str) -> dict:
    return tomllib.loads((_REPO / rel).read_text())


# The shipped wheel's version is the one true value everything else mirrors.
CANONICAL = _toml("packages/laterite/pyproject.toml")["project"]["version"]


def test_canonical_is_clean_pep440() -> None:
    # A `+local` segment is rejected by PyPI on upload; guard the release here.
    assert "+" not in CANONICAL, (
        f"shipped version {CANONICAL!r} carries a PEP 440 local segment"
    )


def test_umbrella_pyproject_matches() -> None:
    root = _toml("pyproject.toml")
    assert root["project"]["version"] == CANONICAL
    # bump-my-version's own bookkeeping value must not lag either.
    assert root["tool"]["bumpversion"]["current_version"] == CANONICAL


def test_rust_workspace_matches() -> None:
    ws = _toml("rust-packages/Cargo.toml")["workspace"]["package"]["version"]
    assert ws == CANONICAL, (
        f"Rust workspace version {ws!r} != shipped wheel {CANONICAL!r} — "
        "every crate inherits this (version.workspace = true), incl. lat"
    )


def test_node_package_and_native_deps_match() -> None:
    pkg = json.loads((_REPO / "rust-packages/laterite-node/package.json").read_text())
    assert pkg["version"] == CANONICAL, (
        f"npm package version {pkg['version']!r} != shipped wheel {CANONICAL!r}"
    )
    # The three platform addons must move with the package — a lag makes
    # `laterite` resolve a stale native binary.
    native = {
        k: v
        for k, v in pkg.get("optionalDependencies", {}).items()
        if k.startswith("@laterite/native-")
    }
    assert native, "no @laterite/native-* optionalDependencies found"
    for name, ver in native.items():
        assert ver == CANONICAL, (
            f"{name} pinned at {ver!r} != shipped wheel {CANONICAL!r}"
        )


def test_compat_version_prefix_matches() -> None:
    # compat.py's __version__ is an f-string literal `"{ver}+compat.python-ags4.…"`
    # — the release prefix is a hardcoded literal a bump must keep current.
    src = (_REPO / "packages/laterite/python/laterite/compat.py").read_text()
    m = re.search(r'__version__ = f"(\d+\.\d+\.\d+[^"+]*)\+compat\.python-ags4\.', src)
    assert m, "could not find compat.__version__ f-string literal"
    assert m.group(1) == CANONICAL, (
        f"compat.py version prefix {m.group(1)!r} != shipped wheel {CANONICAL!r}"
    )
