//! Synthesize a **realistic, spec-valid** AGS4 file.
//!
//! The file is a typed [`model`] the [`emit`]ter walks. The model is
//! generated by [`model::varied_model`]: realistic by default (no "fixed
//! vs varied" mode), with a `seed` controlling only reproducibility —
//! same seed → byte-identical bytes (a determinism test pins this).
//!
//! Realism without sacrificing the safety net: the group/heading/type
//! structure is the proven-clean v4.2 shape and every value is
//! type-correct (picklist codes sampled from the bundled dictionary's
//! ABBR table, the ABBR group emitting exactly the codes used), so the
//! un-injected output is `RustResult::Clean` across seeds — that
//! `varied_baseline_is_rust_clean` guard (in `pipeline`) is what makes
//! the parity-matrix blind-spot rules single-rule-injectable: a finding
//! means a real divergence, never a generator bug.

pub mod breadth;
pub mod bs5930;
pub mod depth;
pub mod emit;
pub mod generic;
pub mod geotech;
pub mod model;

/// The relational scaffold a strategy asked for. `Minimal` is PROJ/TRAN
/// only (a valid minimal file); `LocaSamp` adds the varied LOCA→SAMP→GEOL
/// boreholes + ABBR — the base the relational injectors (10a/10b/10c, 16)
/// need; `Wide` additionally fills every safe LOCA-child group **and** the
/// depth below SAMP (the lab-test-result groups + the LBSG/LBST testing
/// schedule) from the dictionary, with ABBR/UNIT/TYPE covering whatever
/// those groups use.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Scaffold {
    /// PROJ/TRAN prologue only (no relational base).
    Minimal,
    /// PROJ/TRAN + varied LOCA→SAMP→GEOL boreholes + ABBR/UNIT/TYPE.
    LocaSamp,
    /// `LocaSamp` + every dictionary-driven safe LOCA-child group + the
    /// SAMP-child lab-test-result depth + the LBSG/LBST schedule — a
    /// *wide-and-deep* file for the perf/compliance surface.
    Wide,
}

impl Scaffold {
    pub fn parse(s: &str) -> Option<Self> {
        match s {
            "minimal" => Some(Scaffold::Minimal),
            "loca-samp" | "LOCA->SAMP" | "loca->samp" => Some(Scaffold::LocaSamp),
            "wide" => Some(Scaffold::Wide),
            _ => None,
        }
    }
}

/// Synthesize a realistic AGS4 file for `scaffold`, seeded by `seed`
/// (same seed → byte-identical output).
pub fn synth(scaffold: Scaffold, seed: u64) -> String {
    emit::emit_to_string(&model::varied_model(scaffold, seed))
}

/// Lowercase hex, for the byte pins in this module and in `bs5930`.
///
/// A `map(format!).collect()` reads better and is what clippy's
/// `format_collect` exists to stop: it allocates a `String` per byte.
#[cfg(test)]
pub(crate) fn hex(bytes: &[u8]) -> String {
    use std::fmt::Write as _;
    bytes
        .iter()
        .fold(String::with_capacity(bytes.len() * 2), |mut acc, b| {
            let _ = write!(acc, "{b:02x}");
            acc
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn synth_has_expected_groups_and_is_crlf_terminated() {
        let s = synth(Scaffold::LocaSamp, 7);
        assert!(s.ends_with("\r\n"));
        for g in [
            "PROJ", "TRAN", "LOCA", "SAMP", "GEOL", "ABBR", "UNIT", "TYPE",
        ] {
            assert!(s.contains(&format!("\"GROUP\",\"{g}\"")), "missing {g}");
        }
        // Minimal omits the relational base.
        let m = synth(Scaffold::Minimal, 7);
        assert!(!m.contains("\"GROUP\",\"SAMP\""));
        assert!(m.contains("\"GROUP\",\"PROJ\""));
    }

    /// `Wide` synthesizes many more group types than `LocaSamp` (the
    /// dictionary-driven breadth), every group code is unique (no group
    /// emitted twice), and SAMP/GEOL come only from the hand-built core.
    #[test]
    fn wide_adds_breadth_with_no_duplicate_groups() {
        let s = synth(Scaffold::Wide, 3);
        let codes: Vec<&str> = s
            .lines()
            .filter_map(|l| l.strip_prefix("\"GROUP\",\""))
            .map(|r| r.trim_end_matches('"'))
            .collect();
        let uniq: std::collections::HashSet<_> = codes.iter().collect();
        assert_eq!(codes.len(), uniq.len(), "no group code repeats: {codes:?}");
        assert!(codes.len() > 30, "Wide should be wide, got {}", codes.len());
        // The core groups are present exactly once.
        for core in [
            "PROJ", "TRAN", "LOCA", "SAMP", "GEOL", "ABBR", "UNIT", "TYPE",
        ] {
            assert_eq!(
                codes.iter().filter(|&&c| c == core).count(),
                1,
                "{core} must appear exactly once"
            );
        }
        // LocaSamp is the narrower base.
        let narrow = synth(Scaffold::LocaSamp, 3).matches("\"GROUP\"").count();
        assert!(
            codes.len() > narrow,
            "Wide must exceed LocaSamp's group count"
        );
    }

    /// The synthesizer's OUTPUT BYTES, pinned.
    ///
    /// Nothing pinned them before, and that absence is what makes a silent
    /// re-roll possible: `describe()` opens with a coarse/fine `rng.below(2)`,
    /// so adding a vocabulary lane shifts that draw and every draw after it —
    /// every seed then produces a different file, and nothing fails.
    ///
    /// The two tests that look like they would catch it cannot:
    ///
    /// * `synth_is_deterministic_per_seed_and_varies_across_seeds` compares one
    ///   binary against itself. It is trivially true either side of a re-roll.
    /// * `scaffolds_reach_a_pinned_set_of_ags_types` reads only `TYPE`
    ///   descriptor rows. A description lands in a `GEOL_DESC` DATA cell, whose
    ///   declared type is `X` either way, so the pinned set never moves.
    ///
    /// What DOES break is comparability: `tools/gen-bench-fixtures.sh`,
    /// `tools/bench-vs-python-ags4.py` and `tools/bench-cert-parse-share.py`
    /// all draw fixtures from this engine, so numbers taken either side of an
    /// unannounced content change stop measuring the same file.
    ///
    /// Same ratchet as the type pin: a DELIBERATE re-roll is an edit here that
    /// a reviewer sees, and regenerating the bench fixtures belongs in the same
    /// change. An accidental one is a red test.
    ///
    /// The length is asserted alongside the hash on purpose — a mismatch in
    /// both says the content moved, a mismatch in the hash alone would point at
    /// the encoding rather than the draw.
    #[test]
    fn synth_output_bytes_are_pinned() {
        use sha2::{Digest, Sha256};
        for (scaffold, seed, sha, len) in [
            (
                Scaffold::Minimal,
                0u64,
                "a9a314972f1101b80bfb60258d725c039ee6a4208eb09733eaaf805f8290cb4c",
                717usize,
            ),
            (
                Scaffold::Minimal,
                1,
                "db2ebc485e61a606aa106f2ba26ccc02b8abf425142ce4565bdb61fb7044852d",
                717,
            ),
            (
                Scaffold::Minimal,
                2,
                "68b3b576d9377c17826749998046ef16fe47d90676ec8b9bd5100b9b3904b0cd",
                713,
            ),
            (
                Scaffold::LocaSamp,
                0,
                "9ba41962016792aea4e864901c54fbce00958ff8cd476d25a4578433234c7667",
                3184,
            ),
            (
                Scaffold::LocaSamp,
                1,
                "024335aa10eb8e6c6ea9b008c0cef3e2be75a2aba69873d50e04cf20a56e1666",
                2780,
            ),
            (
                Scaffold::LocaSamp,
                2,
                "34a01519060f5c3688da4ff951b1c4a8bd5ad65b47e923b428b4e083719f9368",
                3054,
            ),
            (
                Scaffold::Wide,
                0,
                "6153b01623ca9618f65791f3c452890488a6be249ff1f9c303ecc9a3ec7c2eeb",
                63913,
            ),
            (
                Scaffold::Wide,
                1,
                "0a279fbd0f5ac291da9d659a475bbd3d2fc78c9f677e780040f8c46fe49e8a6c",
                45106,
            ),
            (
                Scaffold::Wide,
                2,
                "a9682a3b4c9ed908c24a0f6392e6b3302fb71cf229f61cd5062797d0e871881d",
                41347,
            ),
        ] {
            let out = synth(scaffold, seed);
            let got = hex(&Sha256::digest(out.as_bytes()));
            assert_eq!(
                (got.as_str(), out.len()),
                (sha, len),
                "{scaffold:?} seed {seed}: the synthesizer's output moved. If that \
                 was deliberate, update these pins AND regenerate the bench \
                 fixtures in the same change — the benches draw from here."
            );
        }
    }

    /// The determinism contract: a seed pins the bytes exactly, and
    /// different seeds genuinely diverge (the realism is real variety,
    /// not a constant).
    #[test]
    fn synth_is_deterministic_per_seed_and_varies_across_seeds() {
        assert_eq!(
            synth(Scaffold::LocaSamp, 42),
            synth(Scaffold::LocaSamp, 42),
            "same seed must be byte-identical"
        );
        assert_ne!(
            synth(Scaffold::LocaSamp, 1),
            synth(Scaffold::LocaSamp, 2),
            "different seeds must produce different files"
        );
    }

    /// The **type axis**: which AGS TYPEs a scaffold can put in front of
    /// an injector at all. The design names two search axes — rule and
    /// placement — and this is a third that nothing recorded, so nothing
    /// noticed it bounding the search. `catalog` gives the Rule 8
    /// injector as "a non-date into a DT-typed cell": a clean-room AGREE
    /// on Rule 8 is therefore earned over the types a scaffold happens to
    /// emit, never over the dictionary's full set.
    ///
    /// Pinned as an **exact set**, not a floor. The reach is a property
    /// of the scaffold's heading set rather than of the values drawn into
    /// it, so it is seed-stable and an exact pin costs no flakiness —
    /// and it makes widening the reach an edit a reviewer sees. Raise the
    /// pin when a type becomes reachable; never relax it to quiet a
    /// failure, which would retire the axis instead of measuring it.
    #[test]
    fn scaffolds_reach_a_pinned_set_of_ags_types() {
        fn reached(scaffold: Scaffold, seed: u64) -> std::collections::BTreeSet<String> {
            synth(scaffold, seed)
                .lines()
                .map(laterite_ags4_parse::split_ags_line)
                .filter(|f| f.first().is_some_and(|h| h.as_str() == "TYPE"))
                .flat_map(|f| f.into_iter().skip(1))
                .filter(|t| !t.is_empty())
                .collect()
        }

        for (scaffold, pinned) in [
            (Scaffold::Minimal, ["DT", "ID", "X"].as_slice()),
            (
                Scaffold::LocaSamp,
                ["2DP", "DT", "ID", "PA", "X"].as_slice(),
            ),
            (
                Scaffold::Wide,
                ["0DP", "2DP", "DT", "ID", "PA", "X"].as_slice(),
            ),
        ] {
            let want: std::collections::BTreeSet<String> =
                pinned.iter().map(|s| (*s).to_string()).collect();
            for seed in 0..4 {
                assert_eq!(
                    reached(scaffold, seed),
                    want,
                    "{scaffold:?} seed {seed}: the reachable AGS type set moved — \
                     raise the pin if a type became reachable, investigate if one was lost"
                );
            }
        }
    }
}
