//! Synthesize a **realistic, spec-valid** AGS4 file.
//!
//! The file is a typed [`model`] the [`emit`]ter walks. The model is
//! generated by [`model::varied_model`]: realistic by default (no "fixed
//! vs varied" mode), with a `seed` controlling only reproducibility —
//! same seed → byte-identical bytes (a determinism test pins this).
//!
//! Realism without sacrificing the safety net: the group/heading/type
//! structure is the proven-clean v4.2 shape and every value is
//! type-correct (picklist codes sampled from the bundled dictionary's
//! ABBR table, the ABBR group emitting exactly the codes used), so the
//! un-injected output is `RustResult::Clean` across seeds — that
//! `varied_baseline_is_rust_clean` guard (in `pipeline`) is what makes
//! the parity-matrix blind-spot rules single-rule-injectable: a finding
//! means a real divergence, never a generator bug.

pub mod breadth;
pub mod bs5930;
pub mod depth;
pub mod emit;
pub mod generic;
pub mod geotech;
pub mod model;

/// The relational scaffold a strategy asked for. `Minimal` is PROJ/TRAN
/// only (a valid minimal file); `LocaSamp` adds the varied LOCA→SAMP→GEOL
/// boreholes + ABBR — the base the relational injectors (10a/10b/10c, 16)
/// need; `Wide` additionally fills every safe LOCA-child group **and** the
/// depth below SAMP (the lab-test-result groups + the LBSG/LBST testing
/// schedule) from the dictionary, with ABBR/UNIT/TYPE covering whatever
/// those groups use.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Scaffold {
    /// PROJ/TRAN prologue only (no relational base).
    Minimal,
    /// PROJ/TRAN + varied LOCA→SAMP→GEOL boreholes + ABBR/UNIT/TYPE.
    LocaSamp,
    /// `LocaSamp` + every dictionary-driven safe LOCA-child group + the
    /// SAMP-child lab-test-result depth + the LBSG/LBST schedule — a
    /// *wide-and-deep* file for the perf/compliance surface.
    Wide,
}

impl Scaffold {
    pub fn parse(s: &str) -> Option<Self> {
        match s {
            "minimal" => Some(Scaffold::Minimal),
            "loca-samp" | "LOCA->SAMP" | "loca->samp" => Some(Scaffold::LocaSamp),
            "wide" => Some(Scaffold::Wide),
            _ => None,
        }
    }
}

/// Synthesize a realistic AGS4 file for `scaffold`, seeded by `seed`
/// (same seed → byte-identical output).
pub fn synth(scaffold: Scaffold, seed: u64) -> String {
    emit::emit_to_string(&model::varied_model(scaffold, seed))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn synth_has_expected_groups_and_is_crlf_terminated() {
        let s = synth(Scaffold::LocaSamp, 7);
        assert!(s.ends_with("\r\n"));
        for g in [
            "PROJ", "TRAN", "LOCA", "SAMP", "GEOL", "ABBR", "UNIT", "TYPE",
        ] {
            assert!(s.contains(&format!("\"GROUP\",\"{g}\"")), "missing {g}");
        }
        // Minimal omits the relational base.
        let m = synth(Scaffold::Minimal, 7);
        assert!(!m.contains("\"GROUP\",\"SAMP\""));
        assert!(m.contains("\"GROUP\",\"PROJ\""));
    }

    /// `Wide` synthesizes many more group types than `LocaSamp` (the
    /// dictionary-driven breadth), every group code is unique (no group
    /// emitted twice), and SAMP/GEOL come only from the hand-built core.
    #[test]
    fn wide_adds_breadth_with_no_duplicate_groups() {
        let s = synth(Scaffold::Wide, 3);
        let codes: Vec<&str> = s
            .lines()
            .filter_map(|l| l.strip_prefix("\"GROUP\",\""))
            .map(|r| r.trim_end_matches('"'))
            .collect();
        let uniq: std::collections::HashSet<_> = codes.iter().collect();
        assert_eq!(codes.len(), uniq.len(), "no group code repeats: {codes:?}");
        assert!(codes.len() > 30, "Wide should be wide, got {}", codes.len());
        // The core groups are present exactly once.
        for core in [
            "PROJ", "TRAN", "LOCA", "SAMP", "GEOL", "ABBR", "UNIT", "TYPE",
        ] {
            assert_eq!(
                codes.iter().filter(|&&c| c == core).count(),
                1,
                "{core} must appear exactly once"
            );
        }
        // LocaSamp is the narrower base.
        let narrow = synth(Scaffold::LocaSamp, 3).matches("\"GROUP\"").count();
        assert!(
            codes.len() > narrow,
            "Wide must exceed LocaSamp's group count"
        );
    }

    /// The determinism contract: a seed pins the bytes exactly, and
    /// different seeds genuinely diverge (the realism is real variety,
    /// not a constant).
    #[test]
    fn synth_is_deterministic_per_seed_and_varies_across_seeds() {
        assert_eq!(
            synth(Scaffold::LocaSamp, 42),
            synth(Scaffold::LocaSamp, 42),
            "same seed must be byte-identical"
        );
        assert_ne!(
            synth(Scaffold::LocaSamp, 1),
            synth(Scaffold::LocaSamp, 2),
            "different seeds must produce different files"
        );
    }
}
