//! Stage F2b-1+: typed-graph codegen.
//!
//! Reads the canonical multi-edition `ags_dictionary.json` (the union of all
//! editions) at Rust build time and emits one `#[pyclass]` struct per AGS group into
//! `$OUT_DIR/typed_groups.rs`. The `typed_graph::groups` module
//! `include!`s the generated file.
//!
//! Why include! over a proc-macro: see
//! [[dec-rust-typed-graph]] — the generated file is mechanically
//! generated and humans rarely need to read it; `include!` keeps the
//! build pipeline single-crate and the generated output is
//! inspectable for debugging.
//!
//! Status:
//! - F2b-1: scalar fields with `Option<T>` + kwargs constructor.
//! - F2b-2: `Py<PyList>` child fields (`locas`, `samps`, ...) with
//!   defaults to empty list, plus a `walk(code)` recursive-descent
//!   helper that yields every instance of the named group code from
//!   the subtree (a generator-like flat-list result).
//!
//! Still pending (later F2b sub-stages): passthrough runtime classes;
//! `read_db`/`write_db`; `.pyi` stubs; parity probe.

use std::env;
use std::fs;
use std::path::PathBuf;

use serde_json::Value;

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let dict_path = manifest.join("../laterite-ags4-core/data/ags_dictionary.json");

    // Cargo will re-run build.rs only when the file we name here
    // changes (or build.rs itself).
    println!("cargo:rerun-if-changed={}", dict_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let dict_text = fs::read_to_string(&dict_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", dict_path.display()));
    let root: Value = serde_json::from_str(&dict_text).expect("ags_dictionary.json: parse");
    // Heading-local schema: `groups` is a {CODE: group} map. The typed graph
    // wants the UNION of every heading across editions, each at its
    // latest-edition definition — which is exactly the flat heading fields here
    // (`by_ed`/`eds` per-edition variation is ignored for the union). The
    // typed-class *set* is what matters; emit in a deterministic order (by code)
    // for stable generated output.
    let groups = root
        .get("groups")
        .and_then(Value::as_object)
        .expect("ags_dictionary.json: groups{}");
    let mut codes: Vec<&str> = groups.keys().map(String::as_str).collect();
    codes.sort_unstable();

    // Build parent → children map so each parent class can emit a
    // `Py<PyList>` field per child group. Child field name is `{code.lower()}s`.
    let mut children_of: std::collections::BTreeMap<String, Vec<String>> =
        std::collections::BTreeMap::new();
    for &code in &codes {
        if let Some(parent) = groups[code].get("parent").and_then(Value::as_str) {
            children_of
                .entry(parent.to_string())
                .or_default()
                .push(code.to_string());
        }
    }
    for kids in children_of.values_mut() {
        kids.sort(); // deterministic child-field order
    }

    let mut out = String::new();
    out.push_str(
        "// AUTO-GENERATED by build.rs from rust-packages/laterite-ags4-core/data/\n\
         // ags_dictionary.json. Do not edit by hand.\n\
         //\n\
         // Each AGS group becomes one `#[pyclass]` struct with scalar\n\
         // headings as Option<T> fields, plus a Py<PyList> per child\n\
         // group. The `walk(code)` method does a recursive descent\n\
         // and returns a flat list of every matching descendant.\n\n",
    );
    out.push_str("use pyo3::prelude::*;\n");
    out.push_str("use pyo3::types::PyList;\n");
    // Only NaiveDateTime is emitted today (AGS `DT` is the sole datetime
    // form; no AGS code maps to Date or Time canonical types). If a
    // future dictionary entry maps to Date / Time, re-add those imports.
    out.push_str("#[allow(unused_imports)]\n");
    out.push_str("use chrono::{NaiveDate, NaiveDateTime, NaiveTime};\n\n");

    let mut registrations = String::new();
    registrations.push_str(
        "/// Add every codegen'd typed-graph class to the given module.\n\
         /// Called from lib.rs at module init.\n\
         pub fn register(m: &Bound<'_, PyModule>) -> PyResult<()> {\n",
    );

    for &code in &codes {
        let headings = groups[code]
            .get("headings")
            .and_then(Value::as_array)
            .expect("group.headings");
        let children: &[String] = children_of.get(code).map(Vec::as_slice).unwrap_or(&[]);
        emit_group(&mut out, code, headings, children);
        registrations.push_str(&format!("    m.add_class::<{code}>()?;\n"));
    }

    registrations.push_str("    Ok(())\n}\n");
    out.push_str(&registrations);

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR set"));
    let dst = out_dir.join("typed_groups.rs");
    fs::write(&dst, out).unwrap_or_else(|e| panic!("write {}: {e}", dst.display()));
}

/// Emit one `#[pyclass]` struct + `#[pymethods]` impl block.
fn emit_group(out: &mut String, code: &str, headings: &[Value], children: &[String]) {
    // Scalar field list for the struct body + constructor signature.
    let scalars: Vec<(String, &'static str)> = headings
        .iter()
        .map(|h| {
            let name = h.get("name").and_then(Value::as_str).expect("heading.name");
            let ags_type = h.get("type").and_then(Value::as_str).unwrap_or("X");
            (py_name(name), rust_type(ags_type))
        })
        .collect();

    // Child field names follow the ags5_models convention:
    // `{child_code.lower()}s` (e.g. PROJ.locas, LOCA.samps).
    let child_fields: Vec<(String, &String)> = children
        .iter()
        .map(|c| (format!("{}s", c.to_lowercase()), c))
        .collect();

    // ---- struct definition ----
    // F2b-4: `dict` enables per-instance __dict__ so `read_db` can
    // attach passthrough children via setattr. ~16 bytes per instance
    // overhead; required for the dynamic-class-on-read policy
    // (see dec-rust-typed-graph.md, *Custom groups & passthrough*).
    out.push_str(&format!(
        "#[pyclass(name = \"{code}\", module = \"laterite._laterite_native\", dict)]\n\
         pub struct {code} {{\n",
    ));
    for (field, ty) in &scalars {
        out.push_str(&format!(
            "    #[pyo3(get, set)]\n    pub {field}: Option<{ty}>,\n"
        ));
    }
    for (field, _) in &child_fields {
        // `get` only — mutation is via `.append()` on the list itself,
        // which `Py<PyList>` supports natively without `set`. The
        // shared Python list identity (same object each access) is the
        // contract that makes `proj.locas.append(loca)` work — `set`
        // would let users reassign the list reference but that breaks
        // identity if a caller holds an old reference.
        out.push_str(&format!("    #[pyo3(get)]\n    pub {field}: Py<PyList>,\n"));
    }
    out.push_str("}\n\n");

    // ---- pymethods ----
    out.push_str(&format!("#[pymethods]\nimpl {code} {{\n"));

    // #[new] signature: every field keyword-only with None default.
    // Children take Option<Py<PyList>>; None → empty PyList created
    // here (so each instance gets its own list).
    out.push_str("    #[new]\n    #[pyo3(signature = (*");
    for (field, _) in &scalars {
        out.push_str(&format!(", {field}=None"));
    }
    for (field, _) in &child_fields {
        out.push_str(&format!(", {field}=None"));
    }
    out.push_str("))]\n");
    out.push_str("    #[allow(clippy::too_many_arguments, unused_variables)]\n");
    // py: Python<'_> is a special PyO3 arg; not visible from Python.
    // It's unused on leaf groups (no children → no PyList::empty calls)
    // and on groups whose every child is passed by the caller — keep
    // the signature uniform across all 174 classes and silence the lint.
    out.push_str("    fn new(\n");
    out.push_str("        py: Python<'_>,\n");
    for (field, ty) in &scalars {
        out.push_str(&format!("        {field}: Option<{ty}>,\n"));
    }
    for (field, _) in &child_fields {
        out.push_str(&format!("        {field}: Option<Py<PyList>>,\n"));
    }
    out.push_str("    ) -> Self {\n");
    if !child_fields.is_empty() {
        out.push_str("        // Each instance gets its own empty PyList by default.\n");
    }
    out.push_str("        Self {\n");
    for (field, _) in &scalars {
        out.push_str(&format!("            {field},\n"));
    }
    for (field, _) in &child_fields {
        out.push_str(&format!(
            "            {field}: {field}.unwrap_or_else(|| PyList::empty(py).unbind()),\n",
        ));
    }
    out.push_str("        }\n    }\n\n");

    // ---- walk(code) ----
    // Recursive descent across child PyLists. At each level: if the
    // child instance's pyclass name matches the requested code (case-
    // insensitive), push it; then recurse via item.walk(code) and
    // extend with the result. Leaf groups (no children) emit a method
    // that returns an empty Vec — that keeps the contract uniform so
    // the recursion doesn't need to feature-test.
    out.push_str(
        "    /// Recursive descent — return every descendant instance whose\n\
         \x20    /// AGS group code matches `code` (case-insensitive). Includes\n\
         \x20    /// matches at every depth of the subtree.\n",
    );
    out.push_str("    #[allow(unused_variables, unused_mut)]\n");
    out.push_str("    fn walk(&self, py: Python<'_>, code: &str) -> PyResult<Vec<Py<PyAny>>> {\n");
    out.push_str("        let mut out: Vec<Py<PyAny>> = Vec::new();\n");
    for (field, child_code) in &child_fields {
        out.push_str(&format!(
            "        // descend into self.{field} ({child_code})\n"
        ));
        out.push_str("        {\n");
        out.push_str(&format!(
            "            let matches_self = code.eq_ignore_ascii_case(\"{child_code}\");\n"
        ));
        out.push_str(&format!(
            "            for item in self.{field}.bind(py).try_iter()? {{\n"
        ));
        out.push_str("                let item = item?.unbind();\n");
        out.push_str("                if matches_self {\n");
        out.push_str("                    out.push(item.clone_ref(py));\n");
        out.push_str("                }\n");
        out.push_str("                let nested: Vec<Py<PyAny>> = item.bind(py).call_method1(\"walk\", (code,))?.extract()?;\n");
        out.push_str("                out.extend(nested);\n");
        out.push_str("            }\n");
        out.push_str("        }\n");
    }
    out.push_str("        Ok(out)\n    }\n\n");

    // __repr__: minimal — fuller form arrives when KEY-aware emission lands.
    out.push_str("    fn __repr__(&self) -> String {\n");
    out.push_str(&format!("        \"{code}(...)\".to_string()"));
    out.push_str("\n    }\n");

    out.push_str("}\n\n");
}

/// AGS heading name → Python attribute name (lowercase).
fn py_name(heading: &str) -> String {
    heading.to_ascii_lowercase()
}

/// Mirror `laterite_ags5_db::ags_types::canonical_type` minus the public API —
/// build.rs can't easily call the crate's function (would create a
/// build-dep cycle), so we duplicate the small classification logic.
/// The two MUST stay in lockstep; a parity probe in F2b-6 will catch
/// drift.
fn rust_type(ags_type: &str) -> &'static str {
    let t: String = ags_type.trim().to_ascii_uppercase();
    match t.as_str() {
        // STRING
        "ID" | "X" | "PA" | "PT" | "PU" | "T" | "U" | "DMS" | "MC" | "XN" => "String",
        // INTEGER
        "0DP" => "i64",
        // DATETIME
        "DT" => "NaiveDateTime",
        // BOOL
        "YN" => "bool",
        // RL: record link (always decimal in spec)
        "RL" => "f64",
        _ => {
            // Numeric forms: NDP / NSF / NSCI where N is positive integer.
            for suffix in ["DP", "SF", "SCI"] {
                if let Some(prefix) = t.strip_suffix(suffix)
                    && !prefix.is_empty()
                    && prefix.chars().all(|c| c.is_ascii_digit())
                {
                    return "f64";
                }
            }
            // Unknown → String fallback (matches Rust runtime + Python
            // _modelgen path).
            "String"
        }
    }
}
