// GENERATED by tools/gen_install_channels.py — DO NOT EDIT.
//
// Every package name here is read out of the file that decides it (the wheel's
// pyproject, laterite-node's package.json, prepare-wasm-package.sh, the wheel
// README's surfaces table), and cross-checked against a second record before
// this file is written. Editing it by hand puts a name on laterite.dev that
// nothing in the repo can keep true.
//
// Regenerate: uv run --no-project python tools/gen_install_channels.py

/* eslint-disable design/no-raw-palette -- #595's recorded decision: the card
   hues are per-surface DATA riding the generator, and this file cannot be
   hand-edited — generation overwrites it and `--check` gates the drift. The
   #404 gate exists to stop ad-hoc literals in hand-written surface code, and
   stays in force everywhere else; this scoped disable is the deliberate
   price of colours-as-generated-data, not a reading of the gate's carve-out. */

export type InstallChannel = {
  readonly id: string;
  readonly label: string;
  /** The registry a reader would look on, or "" where there isn't one. */
  readonly registry: string;
  readonly package: string;
  /** The copyable install command, or "" where the card's action is its
   *  href — the grid then renders a download button instead of a copy box
   *  (#533: the CLI, whose install is a release download, not a command). */
  readonly command: string;
  readonly href: string;
  readonly note: string;
  /** The card's surface hue per theme (#595) — the border colour, and the
   *  ingredient of the card wash. The wash percentage is the page's dial
   *  (landing.css), not data. */
  readonly hue: { readonly light: string; readonly dark: string };
};

export const INSTALL_CHANNELS: readonly InstallChannel[] = [
  {
    id: "python",
    label: "Python",
    registry: "PyPI",
    package: "laterite",
    command: "pip install laterite",
    href: "https://pypi.org/project/laterite/",
    note: "polars + duckdb, pyarrow-free",
    hue: { light: "#34689b", dark: "#8db9dd" },
  },
  {
    id: "node",
    label: "Node.js",
    registry: "npm",
    package: "laterite",
    command: "npm install laterite",
    href: "https://www.npmjs.com/package/laterite",
    note: "native addon, four platforms",
    hue: { light: "#3d7d4a", dark: "#90c69c" },
  },
  {
    id: "cli",
    label: "CLI",
    registry: "",
    package: "lat",
    command: "",
    href: "https://github.com/niko86/laterite/releases",
    note: "lat also ships with the Python wheel and the npm package",
    hue: { light: "#5f5761", dark: "#c5c3c2" },
  },
  {
    id: "duckdb",
    label: "DuckDB",
    registry: "community extension",
    package: "laterite_ags4",
    command: "INSTALL laterite_ags4 FROM community;",
    href: "https://community-extensions.duckdb.org/extensions/laterite_ags4.html",
    note: "read AGS4 in place, as SQL table functions",
    hue: { light: "#8f6b12", dark: "#e5cd6a" },
  },
  {
    id: "browser",
    label: "Browser",
    registry: "npm",
    package: "@laterite/ags4-wasm",
    command: "npm install @laterite/ags4-wasm",
    href: "https://www.npmjs.com/package/@laterite/ags4-wasm",
    note: "the same engine as wasm, or open the webapp",
    hue: { light: "#5c50c9", dark: "#ab9ff0" },
  },
];
