// GENERATED by tools/gen_install_channels.py — DO NOT EDIT.
//
// Every package name here is read out of the file that decides it (the wheel's
// pyproject, laterite-node's package.json, prepare-wasm-package.sh, the wheel
// README's surfaces table), and cross-checked against a second record before
// this file is written. Editing it by hand puts a name on laterite.dev that
// nothing in the repo can keep true.
//
// Regenerate: uv run --no-project python tools/gen_install_channels.py

export type InstallChannel = {
  readonly id: string;
  readonly label: string;
  /** The registry a reader would look on, or "" where there isn't one. */
  readonly registry: string;
  readonly package: string;
  /** The copyable install command, or "" where the card's action is its
   *  href — the grid then renders a download button instead of a copy box
   *  (#533: the CLI, whose install is a release download, not a command). */
  readonly command: string;
  readonly href: string;
  readonly note: string;
  /** The one card the grid highlights. */
  readonly primary: boolean;
};

export const INSTALL_CHANNELS: readonly InstallChannel[] = [
  {
    id: "python",
    label: "Python",
    registry: "PyPI",
    package: "laterite",
    command: "pip install laterite",
    href: "https://pypi.org/project/laterite/",
    note: "polars + duckdb, pyarrow-free",
    primary: true,
  },
  {
    id: "node",
    label: "Node.js",
    registry: "npm",
    package: "laterite",
    command: "npm install laterite",
    href: "https://www.npmjs.com/package/laterite",
    note: "native addon, four platforms",
    primary: false,
  },
  {
    id: "cli",
    label: "CLI",
    registry: "",
    package: "lat",
    command: "",
    href: "https://github.com/niko86/laterite/releases",
    note: "lat also ships with the Python wheel and the npm package",
    primary: false,
  },
  {
    id: "duckdb",
    label: "DuckDB",
    registry: "community extension",
    package: "laterite_ags4",
    command: "INSTALL laterite_ags4 FROM community;",
    href: "https://community-extensions.duckdb.org/extensions/laterite_ags4.html",
    note: "read AGS4 in place, as SQL table functions",
    primary: false,
  },
  {
    id: "browser",
    label: "Browser",
    registry: "npm",
    package: "@laterite/ags4-wasm",
    command: "npm install @laterite/ags4-wasm",
    href: "https://www.npmjs.com/package/@laterite/ags4-wasm",
    note: "the same engine as wasm \u2014 or open the webapp",
    primary: false,
  },
];
