// The transforms that carry the shared token layer onto the docs site (#401).
//
// The docs are the one surface with no bundler: MkDocs copies `docs/` verbatim,
// so it cannot follow `@import "@fontsource-variable/figtree/wght.css"` into
// node_modules the way the two Vite builds do. The tokens therefore have to be
// COPIED there — and a copy is a thing that drifts, so it is generated by
// sync-docs-tokens.mjs from `src/shared/styles/` and checked in CI, never
// hand-edited.
//
// Everything that decides WHAT the copy says lives here as a pure function, so
// the rules can be tested without a filesystem. Each one throws rather than
// degrades: a silent no-op would ship a docs site with no dark theme or no
// fonts, and both look enough like "the CSS is still loading" to survive review.

/** Relative stylesheets a token file composes, in source order. */
export function localImports(css) {
  return [...css.matchAll(/@import\s+"\.\/([^"]+)"/g)].map((m) => m[1]);
}

/** Bare package specifiers a token file composes, in source order. */
export function packageImports(css) {
  return [...css.matchAll(/@import\s+"([^".][^"]*)"/g)]
    .map((m) => m[1])
    .filter((spec) => !spec.startsWith("."));
}

// Material puts its colour scheme on `<body data-md-color-scheme>`, server-side
// from mkdocs.yml and then swapped by its own palette toggle. The shared layer
// keys dark off a `.dark` class instead, because that is what the app and the
// apex apply pre-paint. Rewriting the selector is what lets the docs run the
// SAME dark values rather than a second copy of them — and it is why Material's
// toggle keeps working untouched.
const DARK_RULE = /^\.dark(?=\s*\{)/gm;
const SLATE = '[data-md-color-scheme="slate"]';

export function toMaterialScheme(css) {
  // Anchored to the line start so the file's own prose — which says `.dark`
  // several times while explaining this exact hazard — is left as prose.
  const hits = css.match(DARK_RULE) ?? [];
  if (hits.length !== 1) {
    throw new Error(
      `expected exactly one \`.dark\` rule to rewrite, found ${hits.length}. ` +
        `The shared dark set moved or was split; the docs would render light-only.`,
    );
  }
  return css.replace(DARK_RULE, SLATE);
}

// Fontsource writes every face as `url(./files/<name>)` relative to the package
// stylesheet. The docs bundle sits one directory above `fonts/`, so the urls are
// repointed and the named files copied — which keeps the unicode-range split
// that IS the subsetting (a latin reader still fetches only the latin file).
const FILE_URL = /url\(\.\/files\/([^)]+)\)/g;
const ANY_URL = /url\(([^)]+)\)/g;

export function rewriteFontUrls(css, prefix) {
  const foreign = [...css.matchAll(ANY_URL)]
    .map((m) => m[1])
    .filter((u) => !u.startsWith("./files/"));
  if (foreign.length) {
    throw new Error(
      `not a Fontsource file url: ${foreign[0]}. The package layout moved, ` +
        `or the stylesheet points off-origin — which is the one thing this ` +
        `self-hosting exists to prevent.`,
    );
  }
  const files = [];
  const out = css.replace(FILE_URL, (_, name) => {
    if (!files.includes(name)) files.push(name);
    return `url(${prefix}${name})`;
  });
  if (!files.length) {
    throw new Error(
      `no font files in this stylesheet — nothing would be copied.`,
    );
  }
  return { css: out, files };
}
