"""``lat`` — the Python face of the Rust ``lat`` binary (the ``uvx`` launcher).

A clap-style subcommand tool whose output, ``--json`` / ``--ndjson`` byte-shape and
exit codes are faithful to ``rust-packages/laterite-ags4-check`` (the JSON/NDJSON
strings are built by the *same* serde_json calls in the native module). A bare
``lat <file>`` is shorthand for ``lat validate <file>``. Exit codes: 0 clean ·
1 findings · 3 not-found/io · 4 not-utf8/not-ags4/unsupported-edition ·
5 bad-dict/bad-args · 6 schema violation.

The verbs are **not listed here, or anywhere else**: :func:`_build_parser` is the
one place they are declared, and :func:`_subcommands` / :func:`census` read them
back off it. That is deliberate. A second hand-written verb table is what let
``lat merge`` ship in the native binary (#494) and never reach this launcher, with
every cross-surface gate still green — they all compared one hand-list to another.
``tools/gen_census.py`` now diffs this parser against clap's; see the wiki's
``concepts/surface-census.md``.
"""

from __future__ import annotations

import argparse
import json
import sys
from importlib import resources
from typing import TYPE_CHECKING, cast

if TYPE_CHECKING:
    from laterite import Edition

from . import _laterite_native as _native

#: `--dict-version` choices — ASKED OF THE DICTIONARY, not hand-listed. The editions
#: come from `DictVersion::ALL`, generated by the reference leaf's build.rs from
#: ags_dictionary.json, so a newly bundled edition is accepted here the moment it
#: lands. The hand-written copy this replaces was one of ~nine across the tree, and
#: the Rust CLI's was worse than stale: its rejection MESSAGE was generated while its
#: match arms were not, so a new edition would have made `lat` reject `4.3` with a
#: message advertising `4.3`.
_DICT_CHOICES = ("auto", *_native.registry_editions())
_CLASH_CHOICES = ("error", "widen", "promote")

#: Encoding labels the surface census resolves on every launcher. Mirrors
#: `ENCODING_PROBES` in `commands/census.rs`; `test_census_probe_lists_agree` pins
#: the two lists equal, so the three launchers cannot end up comparing different
#: questions and calling the agreement meaningful.
_ENCODING_PROBES = (
    "utf-8",
    "utf8",
    "cp1252",
    "windows-1252",
    "latin1",
    "latin-1",
    "iso-8859-1",
    "iso-8859-15",
    "latin9",
    "latin-9",
    "l9",
    "shift_jis",
    "cp1252x",
)


def _print_readme() -> int:
    print(resources.files(__package__).joinpath("README-cli.md").read_text("utf-8"))
    return 0


def _plain(file: str, findings: list[dict], n: int) -> str:
    if n == 0:
        return f"{file}: clean (0 findings)\n"
    w = [4, 4, 5, 11]
    rows = []
    for f in findings:
        short = f["rule"].removeprefix("AGS Format Rule ")
        line = "-" if f["line"] is None else str(f["line"])
        cells = [short, line, f["group"], f["desc"]]
        for i, c in enumerate(cells):
            w[i] = max(w[i], len(c))
        rows.append(cells)
    head = ["Rule", "Line", "Group", "Description"]
    out = [f"{file}: {n} finding(s)"]
    out.append(" | ".join(h.ljust(w[i]) for i, h in enumerate(head)))
    out.append("-+-".join("-" * w[i] for i in range(4)))
    for r in rows:
        out.append(" | ".join(r[i].ljust(w[i]) for i in range(4)))
    return "\n".join(out) + "\n"


def _engine(args) -> dict:
    """A full rules pass — the `run_check` verdict dict every renderer below reads."""
    return _native.run_check(
        path=args.file,
        dict_version=args.dict_version,
        include_warnings=not args.no_warnings,
        include_fyi=args.show_fyi,
        check_files=args.check_files,
        encoding=args.encoding,
    )


def _pin(args) -> Edition | None:
    """The edition pin as the *library* spells it: an edition, or `None` for none.

    `--dict-version` defaults to the string `"auto"`, which is the CLI's sentinel for
    "no pin" — the native `parse_dv` maps `"auto"` to `None`. The library has no such
    sentinel, and handing it straight through does not fail loudly: it makes the
    request look like a FORCED edition, so a certificate minted without one stops
    covering it and every `--index` skip quietly disarms. Which is exactly what this
    flag did the first time it ran.
    """
    dv = args.dict_version
    if dv in (None, "", "auto"):
        return None
    # argparse already enforced `choices=_DICT_CHOICES`, which IS the bundled edition
    # set — so the string is one of them by construction, and the cast states what the
    # parser has already guaranteed.
    return cast("Edition", dv)


def _with_cert(args) -> dict:
    """`--index <cert>`: give a `.ags.idx` certificate first refusal at the verdict.

    The cert POLICY is the library's — :func:`laterite.read` fails fast when the
    cert's bytes don't match the file, and ``.validate()`` decides whether the cert
    may stand in for a rules pass — not a second hand-written copy here. The CLI
    adds only the binary's recovery posture: a cert that cannot be trusted is a
    NOTE, not an error. Re-validating is always safe; refusing to run because a
    cert went stale would not be.

    Imported lazily on purpose. This module is otherwise native-only, and pulling
    polars + duckdb in would tax every `lat validate` for a flag almost nobody
    passes.
    """
    from . import Ags4Error, StaleCertError, read

    try:
        handle = read(args.file, index=args.index, encoding=args.encoding)
    except StaleCertError as e:
        print(f"note: --index not used ({e}); running the full check", file=sys.stderr)
        return _engine(args)
    except Ags4Error as e:
        # Un-validatable input (missing, not AGS4, bad edition) — the same
        # `{ok: False}` shape `run_check` returns, so the caller is none the wiser.
        return {"ok": False, "error": str(e), "exit_code": e.exit_code}

    try:
        report = handle.validate(
            dict_version=_pin(args),
            warnings=not args.no_warnings,
            fyi=args.show_fyi,
            check_files=args.check_files,
        ).report
    except Ags4Error as e:
        return {"ok": False, "error": str(e), "exit_code": e.exit_code}

    if report.certified:
        # "rule engine skipped", not "file not checked": a world check (Rule 20's on-disk
        # half) runs even on a certified read — a certificate cannot vouch for a directory.
        print(
            "note: certified clean by the .ags.idx certificate — rule engine skipped",
            file=sys.stderr,
        )
    return report._r


def _run_validate(args) -> int:
    r = _with_cert(args) if args.index else _engine(args)
    if not r.get("ok"):
        print(f"error: {r.get('error')}", file=sys.stderr)
        return int(r.get("exit_code", 5))

    n = r["count"]
    code = r["exit_code"]

    if args.json:
        active = r["json"] + "\n"
    elif args.ndjson:
        active = r["ndjson"]
    else:
        active = _plain(r["file"], r["findings"], n)

    if args.json_out:
        with open(args.json_out, "w", encoding="utf-8", newline="") as fh:
            fh.write(r["json"] + "\n")
        sys.stdout.write(_plain(r["file"], r["findings"], n))  # tee: plain still to stdout
        return code

    if args.out:
        with open(args.out, "w", encoding="utf-8", newline="") as fh:
            fh.write(active)
        print(f"{r['file']}: {n} finding(s)" if n else f"{r['file']}: clean (0 findings)")
        return code

    sys.stdout.write(active)
    return code


def _run_fix(args) -> int:
    """`lat fix`: mechanically repair the file. Faithful to the Rust `fix`
    (sibling `<file>.fixed.ags` by default; `--in-place` / `--fix-out` redirect).
    Exit 0 clean · 1 residual · 3/4/5 read/parse/dict errors."""
    import json
    from pathlib import Path

    if args.in_place and args.fix_out:
        print("error: --in-place and --fix-out are mutually exclusive", file=sys.stderr)
        return 5

    r = _native.fix_file(
        path=args.file,
        dict_version=args.dict_version,
        include_risky=args.risky,
        encoding=args.encoding,
    )
    if not r.get("ok"):
        print(f"error: {r.get('error')}", file=sys.stderr)
        return int(r.get("exit_code", 5))

    src = Path(args.file)
    if args.in_place:
        dest = src
    elif args.fix_out:
        dest = Path(args.fix_out)
    elif src.suffix:
        dest = src.with_name(f"{src.stem}.fixed{src.suffix}")
    else:
        dest = src.with_name(f"{src.name}.fixed")
    try:
        dest.write_bytes(r["fixed"])
    except OSError as e:
        print(f"error: writing {dest}: {e}", file=sys.stderr)
        return 3

    kinds = sorted({a["kind"] for a in r["applied"]})
    n_applied = r["fixes_applied"]
    if n_applied == 0:
        print(f"no fixes applicable → {dest}")
    else:
        print(f"applied {n_applied} fix(es) [{', '.join(kinds)}] → {dest}")

    by_rule = json.loads(r["findings_json"])
    n_residual = sum(len(v) for v in by_rule.values())
    if n_residual == 0:
        print(f"{dest}: clean (0 findings)")
        return 0
    print(f"{dest}: {n_residual} finding(s) remain (not mechanically fixable)")
    return 1


def _list_rules(as_json: bool) -> int:
    """`lat rules`: print the rule catalogue and exit 0. `--json` emits the raw
    gated `rules_meta.json` (byte-faithful to the Rust binary); otherwise a
    compact Rule | Title | Severity | Fix? table."""
    raw = _native.list_rules()
    if as_json:
        print(raw)
        return 0
    import json

    rules = json.loads(raw)["rules"]
    w = [4, 5, 8, 4]
    rows = []
    for r in rules:
        cells = [
            r["rule"],
            r.get("title", ""),
            r.get("severity", ""),
            "yes" if r.get("fixable") else "",
        ]
        for i, c in enumerate(cells):
            w[i] = max(w[i], len(c))
        rows.append(cells)
    head = ["Rule", "Title", "Severity", "Fix?"]
    out = [" | ".join(h.ljust(w[i]) for i, h in enumerate(head)).rstrip()]
    out.append("-+-".join("-" * w[i] for i in range(4)))
    for r in rows:
        out.append(" | ".join(r[i].ljust(w[i]) for i in range(4)).rstrip())
    print("\n".join(out))
    return 0


def _run_diff(args) -> int:
    """`lat diff <a> <b>`: the KEY-aware/type-aware revision delta. Faithful to
    the Rust `diff`: a per-group summary (or the full delta with `--json`)."""
    import json
    from pathlib import Path

    try:
        a = Path(args.file).read_bytes()
        b = Path(args.other).read_bytes()
    except OSError as e:
        print(f"error: {e}", file=sys.stderr)
        return 3
    r = _native.diff_files(a, b, dict_version=args.dict_version, encoding=args.encoding)
    if not r.get("ok"):
        print(f"error: {r.get('error')}", file=sys.stderr)
        return int(r.get("exit_code", 5))
    delta = json.loads(r["delta_json"])
    if args.json:
        print(json.dumps(delta, indent=2))
        return 0
    print(f"{args.file} → {args.other}")
    for g in delta["groups"]:
        print(f"  {g['code']:<6} +{g['added']} -{g['removed']} ~{g['changed']}")
    if delta["groups_added"]:
        print(f"  groups added:   {', '.join(delta['groups_added'])}")
    if delta["groups_removed"]:
        print(f"  groups removed: {', '.join(delta['groups_removed'])}")
    print(
        f"  total: +{delta['total_added']} added · "
        f"−{delta['total_removed']} removed · ~{delta['total_changed']} changed"
    )
    return 0


def _run_merge(args) -> int:
    """`lat merge <files...> --out <merged.ags>` — reconcile N deliveries into one.

    Faithful to the Rust `merge`: argument order is the authority (the LAST file
    wins a KEY conflict), `--out` is required (never a silent default over an
    input), and the `--json` summary carries the same `{out, bytes, warnings,
    revisions}` shape. Exit 0 merged · 3 read/write · 4 parse · 5 bad args ·
    6 an irreconcilable TYPE/UNIT clash.

    This verb reached the native binary in #494 and did not reach this launcher
    until the surface census caught the omission — the first bug that gate found.
    """
    from pathlib import Path

    import laterite

    if len(args.files) < 2:
        print("error: merge needs at least two files", file=sys.stderr)
        return 5
    for f in args.files:
        if not Path(f).exists():
            print(f"error: {f}: not found", file=sys.stderr)
            return 3

    dv = None if args.dict_version == "auto" else args.dict_version
    try:
        res = laterite.merge(
            *args.files,
            on_type_clash=args.on_type_clash,
            dict_version=dv,
            encoding=args.encoding,
            tran_issue=args.tran_issue,
            tran_date=args.tran_date,
            tran_producer=args.tran_producer,
            tran_recipient=args.tran_recipient,
            tran_status=args.tran_status,
        )
    except laterite.MergeConflictError as e:
        # The library message already carries the full guidance (which modes settle
        # this clash, and — for a UNIT clash — that none of them do, #501), so we do
        # NOT append CLI hints on top: that doubled the advice.
        #
        # It is still not byte-faithful to the Rust `lat merge`, which prints
        # `error: TYPE conflict in <G>.<H>: ...` plus two `hint:` lines in CLI
        # register (`--on-type-clash promote`), where this prints the library's
        # register (`on_type_clash=promote`). Closing that needs structured fields on
        # MergeConflictError (it carries only a message + exit_code today) so this
        # launcher can render the CLI's own wording from the same facts. Tracked with
        # the message-parity findings the value runner is built to catch — not fudged
        # here by re-deriving a second error taxonomy from string matching.
        print(f"error: {e}", file=sys.stderr)
        return 6
    except Exception as e:  # noqa: BLE001 — parse / emit failures surface here
        print(f"error: {e}", file=sys.stderr)
        return 4

    try:
        Path(args.out).write_bytes(res.bytes)
    except OSError as e:
        print(f"error: writing {args.out}: {e}", file=sys.stderr)
        return 3

    if args.json:
        print(
            json.dumps(
                {
                    "out": args.out,
                    "bytes": len(res.bytes),
                    "warnings": res.warnings,
                    "revisions": res.revisions,
                },
                indent=2,
            )
        )
        return 0

    print(f"merged {len(args.files)} files → {args.out} ({len(res.bytes)} bytes)")
    for w in res.warnings:
        print(f"  warning [{w['kind']}]: {w['message']}")
    if res.revisions:
        print(f"  {len(res.revisions)} row revision(s):")
        for r in res.revisions:
            print(
                f"    {r['group']} {r['key']}: changed {r['changed']} "
                f"(from file[{r['winner_file']}])"
            )
    return 0


def _run_certify(args) -> int:
    """`lat certify <file>`: mint the `.ags.idx` for an error-clean file.

    This function used to be the FIFTH place in the codebase that decided what a
    certificate may attest, and it decided differently from the other four: it gated on
    `report.is_valid`, which is zero findings of ANY tier — so this launcher refused to
    certify an error-clean file that carried a single warning, while the native `lat`
    binary happily minted one for the same bytes. Three launchers, one contract, two
    behaviours.

    It no longer decides anything. `certify()` runs the validation itself and refuses a
    file with errors, which is the one rule there has ever been."""
    from . import Ags4Error, read

    dv = None if args.dict_version == "auto" else args.dict_version
    try:
        handle = read(args.file, encoding=args.encoding)
        dest = handle.certify(args.out, dict_version=dv) if args.out else handle.certify(dict_version=dv)
    except FileNotFoundError:
        print(f"error: {args.file}: not found", file=sys.stderr)
        return 3
    except Ags4Error as e:
        # An error-carrying file is refused by the mint, in the mint's own words.
        if "cannot certify" in str(e):
            print(f"{e} (run `lat validate {args.file}` to see them)", file=sys.stderr)
            return 1
        print(f"error: {e}", file=sys.stderr)
        return e.exit_code
    except Exception as e:  # noqa: BLE001 — parse/dict errors surface here
        print(f"error: {e}", file=sys.stderr)
        return 4
    print(f"certificate written to {dest}")
    return 0


def _emit(body: str, out: str | None) -> int:
    if out:
        with open(out, "w", encoding="utf-8", newline="") as fh:
            fh.write(body)
        print(f"note: written to {out}", file=sys.stderr)
    else:
        sys.stdout.write(body)
    return 0


def _csv_row(cells) -> str:
    """One RFC-4180-ish CSV line — byte-identical to the Rust `read` CSV: quote a
    field iff it contains `,` / `"` / CR / LF, doubling internal quotes."""
    out = []
    for c in cells:
        if any(ch in c for ch in ',"\r\n'):
            out.append('"' + c.replace('"', '""') + '"')
        else:
            out.append(c)
    return ",".join(out) + "\n"


def _read_table(headings, rows) -> str:
    """A plain aligned table for `lat read <group>` — the human view (the Rust
    binary renders its own comfy-table box grid; only --json/--csv are byte-coherent)."""
    w = [len(h) for h in headings]
    for row in rows:
        for i, c in enumerate(row):
            w[i] = max(w[i], len(c))
    lines = [" | ".join(h.ljust(w[i]) for i, h in enumerate(headings)).rstrip()]
    lines.append("-+-".join("-" * w[i] for i in range(len(headings))))
    for row in rows:
        lines.append(" | ".join(row[i].ljust(w[i]) for i in range(len(headings))).rstrip())
    return "\n".join(lines) + "\n"


def _run_read(args) -> int:
    """`lat read <file> [group]` — list the file's group codes, or dump a group
    as a table / CSV / JSON. Raw file cells via the native read codec, so the
    Rust binary and this CLI agree byte-for-byte on the group listing and on
    `read --json` / `--csv` (the human --table is each surface's own — #430 PR 2)."""
    import json as _json
    from pathlib import Path

    if not Path(args.file).exists():
        print(f"error: {args.file}: not found", file=sys.stderr)
        return 3
    try:
        raw = _native.read_groups_raw(args.file)
    except Exception as e:  # noqa: BLE001 — parse/dict errors surface here
        print(f"error: {e}", file=sys.stderr)
        return 4

    order = raw["order"]
    if args.group is None:
        if not order:
            print("note: no groups in the file", file=sys.stderr)
            return 0
        body = (
            _json.dumps(order, indent=2, ensure_ascii=False) + "\n"
            if args.json
            else "\n".join(order) + "\n"
        )
        return _emit(body, args.out)

    if args.group not in raw["groups"]:
        present = ", ".join(order) or "none"
        print(
            f"error: group {args.group!r} not found in {args.file} (present: {present})",
            file=sys.stderr,
        )
        return 4

    g = raw["groups"][args.group]
    headings, rows = g["headings"], g["rows"]
    if args.json:
        objs = [dict(zip(headings, row, strict=True)) for row in rows]
        body = _json.dumps(objs, indent=2, ensure_ascii=False) + "\n"
    elif args.csv:
        body = "".join(_csv_row(r) for r in [headings, *rows])
    else:
        body = _read_table(headings, rows)
    return _emit(body, args.out)


def _resolve_password(password_file, prompt: str) -> str:
    """Passphrase precedence — `--password-file` → `$LAT_TRANSPORT_PASSWORD` → an
    interactive prompt (never echoed). NEVER a `--password` flag: argv leaks into
    `ps` and shell history. Mirrors the Rust `lat`'s resolution exactly."""
    import os
    from pathlib import Path

    if password_file:
        return Path(password_file).read_text(encoding="utf-8").rstrip("\r\n")
    env = os.environ.get("LAT_TRANSPORT_PASSWORD")
    if env:
        return env
    import getpass

    return getpass.getpass(prompt)


def _run_pack(args) -> int:
    from pathlib import Path

    from . import transport

    if not Path(args.input).exists():
        print(f"error: {args.input}: not found", file=sys.stderr)
        return 3
    try:
        transport.pack(args.input, dest=args.output, level=args.level)
    except Exception as e:  # noqa: BLE001 — zstd failure surfaces here
        print(f"error: {e}", file=sys.stderr)
        return 6
    print(f"packed {args.input} → {args.output}", file=sys.stderr)
    return 0


def _run_unpack(args) -> int:
    from pathlib import Path

    from . import transport

    if not Path(args.input).exists():
        print(f"error: {args.input}: not found", file=sys.stderr)
        return 3
    try:
        transport.unpack(args.input, dest=args.output)
    except Exception as e:  # noqa: BLE001
        print(f"error: {e}", file=sys.stderr)
        return 6
    print(f"unpacked {args.input} → {args.output}", file=sys.stderr)
    return 0


def _run_lock(args) -> int:
    from pathlib import Path

    from . import transport

    if not Path(args.input).exists():
        print(f"error: {args.input}: not found", file=sys.stderr)
        return 3
    pw = _resolve_password(args.password_file, "Passphrase to lock with: ")
    try:
        transport.lock(args.input, password=pw, level=args.level, log_n=args.log_n, dest=args.output)
    except Exception as e:  # noqa: BLE001 — zstd / age failure surfaces here
        print(f"error: {e}", file=sys.stderr)
        return 6
    print(f"locked {args.input} → {args.output}", file=sys.stderr)
    return 0


def _run_unlock(args) -> int:
    from pathlib import Path

    from . import transport

    if not Path(args.input).exists():
        print(f"error: {args.input}: not found", file=sys.stderr)
        return 3
    pw = _resolve_password(args.password_file, "Passphrase to unlock: ")
    try:
        transport.unlock(args.input, password=pw, dest=args.output)
    except Exception as e:  # noqa: BLE001 — wrong password / corrupt file surfaces here
        print(f"error: {e}", file=sys.stderr)
        return 6
    print(f"unlocked {args.input} → {args.output}", file=sys.stderr)
    return 0


def _run_excel(args) -> int:
    """`lat excel <in> <out>` — AGS4 ↔ Excel. Direction is inferred from the
    output extension (`.xlsx` ⇒ export, `.ags` ⇒ import), or forced with
    `--export` / `--import`. Mirrors the Rust `lat excel`."""
    from pathlib import Path

    import laterite

    if not Path(args.input).exists():
        print(f"error: {args.input}: not found", file=sys.stderr)
        return 3
    if args.export:
        export = True
    elif args.import_:
        export = False
    else:
        ext = Path(args.output).suffix.lower()
        if ext == ".xlsx":
            export = True
        elif ext == ".ags":
            export = False
        else:
            print(
                f"error: can't infer direction from output {args.output} — "
                "pass --export (→ .xlsx) or --import (→ .ags)",
                file=sys.stderr,
            )
            return 5
    try:
        if export:
            laterite.to_excel(args.input, args.output)
        else:
            laterite.from_excel(
                args.input, args.output, format_numeric_columns=not args.no_format_numeric
            )
    except Exception as e:  # noqa: BLE001 — parse / xlsx failure surfaces here
        print(f"error: {e}", file=sys.stderr)
        return 6
    print(f"{'exported' if export else 'imported'} {args.input} → {args.output}", file=sys.stderr)
    return 0


def _global_parent() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(add_help=False)
    p.add_argument("--json", action="store_true")
    p.add_argument("--ndjson", action="store_true")
    p.add_argument("--quiet", action="store_true")
    return p


def _dict_parent() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(add_help=False)
    p.add_argument("--dict-version", choices=_DICT_CHOICES, default="auto")
    p.add_argument("--dict")
    p.add_argument("--encoding")
    return p


def _subcommands(p: argparse.ArgumentParser) -> tuple[str, ...]:
    """The verbs this launcher dispatches — asked of the PARSER, never a list.

    A second hand-written verb table is the failure the surface census exists to
    catch: it is what let `lat merge` ship in the native binary and silently miss
    this launcher. The parser is what actually parses argv, so it is the only
    honest answer to "what verbs are there".
    """
    subs = next((a for a in p._actions if isinstance(a, argparse._SubParsersAction)), None)
    return tuple(subs.choices) if subs else ()


def _with_default_subcommand(argv: list[str], p: argparse.ArgumentParser) -> list[str]:
    """Splice `validate` in when the first non-flag token isn't a known subcommand
    — so `lat <file>` (and `lat <file> --json`) route to validate, mirroring the
    Rust argv pre-scan. Global flags are valueless bools, so a leading run of `-`
    tokens is skipped without consuming a value."""
    verbs = _subcommands(p)
    for i, a in enumerate(argv):
        if a.startswith("-"):
            continue
        if a not in verbs:
            return argv[:i] + ["validate"] + argv[i:]
        return argv
    return argv


def _build_parser() -> argparse.ArgumentParser:
    """The uvx launcher's parser.

    Extracted from ``main`` so :func:`census` can REFLECT the very parser that
    parses the real command line, rather than describing it from a second list.
    That distinction is the whole point of the surface census: ``lat merge``
    shipped in the native binary (#494) and never reached this launcher, and no
    gate saw it, because every gate compared one hand-list against another.
    """
    gp, dp = _global_parent(), _dict_parent()
    p = argparse.ArgumentParser(prog="lat", add_help=False)
    sub = p.add_subparsers(dest="cmd")

    pv = sub.add_parser("validate", add_help=False, parents=[gp, dp])
    pv.add_argument("file")
    pv.add_argument("--no-warnings", action="store_true")
    pv.add_argument("--show-fyi", action="store_true")
    pv.add_argument("--check-files", action="store_true")
    # The door this launcher never had. The binary and npx both take a `.ags.idx`
    # certificate here; uvx simply omitted the flag, so a script portable across the
    # three launchers was not — `--index` was an unknown-argument error on this one.
    # The flags census is what made that visible: every earlier gate compared VERB
    # names, and `validate` was present on all three.
    pv.add_argument("--index")
    pv.add_argument("--out")
    pv.add_argument("--json-out")

    prd = sub.add_parser("read", add_help=False, parents=[gp])
    prd.add_argument("file")
    prd.add_argument("group", nargs="?")
    prd.add_argument("--csv", action="store_true")
    prd.add_argument("--out")

    pf = sub.add_parser("fix", add_help=False, parents=[gp, dp])
    pf.add_argument("file")
    pf.add_argument("--risky", action="store_true")
    pf.add_argument("--in-place", action="store_true")
    pf.add_argument("--fix-out")

    pdf = sub.add_parser("diff", add_help=False, parents=[gp, dp])
    pdf.add_argument("file")
    pdf.add_argument("other")

    pm = sub.add_parser("merge", add_help=False, parents=[gp, dp])
    pm.add_argument("files", nargs="+")
    pm.add_argument("--out", required=True)
    pm.add_argument("--on-type-clash", dest="on_type_clash", choices=_CLASH_CHOICES, default="error")
    pm.add_argument("--tran-issue", dest="tran_issue")
    pm.add_argument("--tran-date", dest="tran_date")
    pm.add_argument("--tran-producer", dest="tran_producer")
    pm.add_argument("--tran-recipient", dest="tran_recipient")
    pm.add_argument("--tran-status", dest="tran_status")

    pc = sub.add_parser("certify", add_help=False, parents=[gp, dp])
    pc.add_argument("file")
    # `--check-files` was here (and on the binary). It recorded, in the certificate, that
    # Rule 20's on-disk half had run — and a later `validate --check-files --index` read
    # that record and skipped the check. Delete the FILE/ tree in between and the file
    # still reported clean. A certificate is a statement about bytes; the directory beside
    # them is not one. Use `lat validate --check-files`, which runs it live.
    pc.add_argument("--out")

    sub.add_parser("rules", add_help=False, parents=[gp])

    pk = sub.add_parser("pack", add_help=False, parents=[gp])
    pk.add_argument("input")
    pk.add_argument("output")
    pk.add_argument("--level", type=int, default=9)

    pup = sub.add_parser("unpack", add_help=False, parents=[gp])
    pup.add_argument("input")
    pup.add_argument("output")

    pl = sub.add_parser("lock", add_help=False, parents=[gp])
    pl.add_argument("input")
    pl.add_argument("output")
    pl.add_argument("--level", type=int, default=9)
    pl.add_argument("--log-n", dest="log_n", type=int, default=None)
    pl.add_argument("--password-file", dest="password_file")

    pul = sub.add_parser("unlock", add_help=False, parents=[gp])
    pul.add_argument("input")
    pul.add_argument("output")
    pul.add_argument("--password-file", dest="password_file")

    pe = sub.add_parser("excel", add_help=False, parents=[gp])
    pe.add_argument("input")
    pe.add_argument("output")
    _exdir = pe.add_mutually_exclusive_group()
    _exdir.add_argument("--export", action="store_true")
    _exdir.add_argument("--import", dest="import_", action="store_true")
    pe.add_argument("--no-format-numeric", dest="no_format_numeric", action="store_true")

    return p


def _arg_json(a: argparse.Action) -> dict:
    """One argparse action as the census's shared arg shape.

    `takes_value` is the load-bearing field — it is what says whether a flag eats the
    next token, and the three launchers are diffed on it. Positionals are reported as
    `<name>` (as clap does), so a launcher that forgets an argument entirely is still
    visible to the diff rather than simply absent from it.
    """
    if a.option_strings:
        name = max(a.option_strings, key=len)  # the long form
        takes_value = a.nargs != 0 and not isinstance(
            a, argparse._StoreTrueAction | argparse._StoreFalseAction
        )
    else:
        name = f"<{a.dest}>"
        takes_value = True
    return {
        "name": name,
        "takes_value": bool(takes_value),
        "required": bool(a.required),
        "values": sorted(a.choices) if a.choices else [],
    }


def census() -> dict:
    """This launcher's parser, as JSON — the shape `lat census` emits.

    Reflected from :func:`_build_parser`, never hand-listed. ``tools/gen_census.py``
    diffs this against the native binary (the authority).
    """
    p = _build_parser()
    subs = next((a for a in p._actions if isinstance(a, argparse._SubParsersAction)), None)
    # argparse types `choices` as an untyped Iterable, but a _SubParsersAction's
    # choices values ARE the per-verb parsers — which is the whole point here: we
    # reflect each real parser rather than describing it from a list.
    choices = cast("dict[str, argparse.ArgumentParser]", dict(subs.choices) if subs else {})

    # The two launchers declare the same globals in opposite directions: clap hangs
    # `--json/--ndjson/--quiet` off the ROOT command, while argparse can only reach a
    # subcommand through `parents=[gp]`, which COPIES them into every verb. Reflecting
    # the shared parent is what lets the census subtract them back out and compare the
    # per-verb tables like for like — rather than reporting three phantom extra flags
    # on all twelve verbs.
    global_args = [_arg_json(a) for a in _global_parent()._actions]
    global_names = {a["name"] for a in global_args}
    global_args.sort(key=lambda d: d["name"])

    verbs = []
    for verb, sp in choices.items():
        args = [j for a in sp._actions if (j := _arg_json(a))["name"] not in global_names]
        args.sort(key=lambda d: d["name"])
        verbs.append({"verb": verb, "args": args})
    verbs.sort(key=lambda d: d["verb"])
    return {
        # See CENSUS_VERSION in the Rust census — bumped when a TABLE is added, so a
        # launcher built before a table existed fails loudly rather than reporting it
        # empty (which would read as "no drift").
        "census_version": 4,
        "surface": "cli-uvx",
        "authority": False,
        "verbs": verbs,
        "global_args": global_args,
        "documented_verbs": list(_subcommands(p)),
        # The editions this launcher accepts for --dict-version, minus the "auto"
        # sentinel (which is not an edition). Derived, so it agrees with the native
        # binary by construction — and the census proves it rather than assuming it.
        "editions": [e for e in _DICT_CHOICES if e != "auto"],
        "fallback_edition": _native.registry_fallback_edition(),
        # What THIS launcher makes of each probe label. `cp1252x` must map to None on
        # every surface — that entry is the policy pin: an unknown label is refused,
        # never quietly decoded as UTF-8 (which is what Node used to do, handing the
        # caller the wrong text with no error at all).
        "encodings": {
            label: _native.resolve_encoding_label(label) for label in _ENCODING_PROBES
        },
    }


def main(argv: list[str] | None = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)

    if "--readme" in argv or "-h" in argv or "--help" in argv:
        return _print_readme()

    if argv[:1] == ["census"]:
        print(json.dumps(census(), indent=2))
        return 0

    p = _build_parser()
    argv = _with_default_subcommand(argv, p)

    try:
        args, extra = p.parse_known_args(argv)
    except SystemExit:
        return 5  # a clap-style "bad args" — argparse would exit 2 otherwise

    if extra:
        print(f"error: unexpected argument {extra[0]!r}", file=sys.stderr)
        return 5
    if getattr(args, "cmd", None) is None:
        print("error: a subcommand or input file is required", file=sys.stderr)
        return 5

    # External --dict is deliberately unimplemented (O-28) — the Rust binary
    # returns BadDict (exit 5) for it too. The edition list is GENERATED: it used to
    # be spelled out here, so bundling a new edition would have left this message
    # telling the user to reach for a set that no longer matched the one the flag
    # accepts. That is the exact trap #509 found in the binary, inverted.
    if getattr(args, "dict", None):
        editions = "/".join(e for e in _DICT_CHOICES if e != "auto")
        print(
            "error: external --dict override is not implemented; use "
            f"--dict-version ({editions}) or omit it",
            file=sys.stderr,
        )
        return 5
    if getattr(args, "json", False) and getattr(args, "ndjson", False):
        print("error: --json and --ndjson are mutually exclusive", file=sys.stderr)
        return 5

    if args.cmd == "rules":
        return _list_rules(args.json)
    if args.cmd == "read":
        return _run_read(args)
    if args.cmd == "pack":
        return _run_pack(args)
    if args.cmd == "unpack":
        return _run_unpack(args)
    if args.cmd == "lock":
        return _run_lock(args)
    if args.cmd == "unlock":
        return _run_unlock(args)
    if args.cmd == "excel":
        return _run_excel(args)
    if args.cmd == "diff":
        return _run_diff(args)
    if args.cmd == "merge":
        return _run_merge(args)
    if args.cmd == "fix":
        return _run_fix(args)
    if args.cmd == "certify":
        return _run_certify(args)
    return _run_validate(args)


if __name__ == "__main__":
    raise SystemExit(main())
