/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * AGS spec type code → canonical category label (`"string"`, `"integer"`,
 * `"decimal"`, `"datetime"`, `"date"`, `"time"`, `"bool"`, `"enum"`), or `null`
 * for unknown codes (the TS wrapper re-raises as an error).
 */
export declare function canonicalType(agsType: string): string | null
/**
 * Presentation hint for a numeric AGS type: `"2DP"` → `"%.2f"`, `"3SF"` →
 * `"%.3g"`, `"1SCI"` → `"%.1e"`; `null` for non-numeric / unknown codes.
 */
export declare function displayHint(agsType: string): string | null
/**
 * Parse an AGS4-shaped raw string into its canonical value — the same engine
 * the read path uses. Permissive: empty / unparseable → `null`. Returns native
 * JS: integer/decimal → number, bool → boolean, string/enum → string,
 * **datetime/date/time → the canonical string** (`"YYYY-MM-DD HH:MM:SS"` /
 * `"YYYY-MM-DD"` / `"HH:MM:SS"`), unknown code → the trimmed input.
 */
export declare function parseValue(raw: string | undefined | null, agsType: string): any
/**
 * Result of `transportPack` / `transportLock`: output size, ratio vs source,
 * elapsed seconds.
 */
export interface PackStats {
  bytes: bigint
  ratio: number
  elapsedS: number
}
/** Result of `transportUnpack` / `transportUnlock`: output size, elapsed seconds. */
export interface UnpackStats {
  bytes: bigint
  elapsedS: number
}
/** zstd-compress `src` → `dest`. `level` is 1–22 (default 9, the AGS sweet spot). */
export declare function transportPack(src: string, dest: string, level?: number | undefined | null): PackStats
/** zstd-decompress `src` → `dest`. */
export declare function transportUnpack(src: string, dest: string): UnpackStats
/**
 * zstd-compress, then age-encrypt with `password` → `dest`. Compress-then-
 * encrypt is load-bearing: zstd needs low-entropy input; ciphertext is random.
 */
export declare function transportLock(src: string, dest: string, password: string, level?: number | undefined | null): PackStats
/**
 * age-decrypt with `password`, then zstd-decompress → `dest`. Wrong passphrase
 * / non-passphrase envelopes surface as an error.
 */
export declare function transportUnlock(src: string, dest: string, password: string): UnpackStats
/** The crate version. */
export declare function version(): string
/** Per-group schema — parallel arrays, one entry per heading. */
export interface GroupMeta {
  headings: Array<string>
  units: Array<string>
  /** AGS TYPE codes from the file's TYPE row (e.g. "2DP", "DT", "ID"). */
  types: Array<string>
  /**
   * The SQL/DuckDB column type each heading lands as ("DOUBLE", "BIGINT",
   * "TIMESTAMP", "VARCHAR", …).
   */
  sqlTypes: Array<string>
  /** 1-indexed source line of each DATA row (parallel to the group's rows). */
  lineNumbers: Array<number>
}
/**
 * Parse an AGS4 file (`path`), in-memory `text`, or raw `data` bytes into a
 * `Reading` handle. `encoding`: `"utf-8"` (default) / `"windows-1252"` / a label
 * — applies to `path` / `data` (text is already decoded). Throws the classified
 * `kind␟code␟message` (see the error-protocol note) on bad input.
 */
export declare function parseArrow(path?: string | undefined | null, text?: string | undefined | null, data?: Uint8Array | undefined | null, encoding?: string | undefined | null): Reading
/** One rule violation (omitting `severity` ⇒ error, matching the engine). */
export interface Finding {
  rule: string
  line?: number
  group: string
  desc: string
  severity?: string
}
/**
 * The validation report — the Node mirror of laterite-py's `run_check` dict.
 * `ok` is **false only for un-validatable input** (the TS `raiseFor` raises
 * then); rule *violations* come back in `findings` with `ok:true`. `Report`'s
 * `isValid` is the separate `count == 0`. `json`/`ndjson` are byte-identical
 * to `lat-check --json` / `--ndjson`.
 */
export interface ValidationReport {
  ok: boolean
  /**
   * Set (with `error`) only when `ok` is false — the failure kind the TS
   * `raiseFor` maps to an exception (`not_ags4`, `unsupported_edition`, …).
   */
  errorKind?: string
  error?: string
  /**
   * Mirrors the `lat-check` binary: 0 valid / 1 findings on success;
   * 3 not-found/io, 4 not-utf8/not-ags4/bad-edition, 5 bad-dict on failure.
   */
  exitCode: number
  file: string
  dictVersion: string
  resolution: string
  count: number
  findings: Array<Finding>
  json: string
  ndjson: string
}
/**
 * Validate an AGS4 file (`path`) or `text` against the AGS4 rules. `dict_version`
 * `None`/`"auto"` auto-detects from `TRAN_AGS`, else forces an edition. Returns
 * the `{ok:false}` failure report (not a throw) for un-validatable input.
 */
export declare function runCheck(path?: string | undefined | null, text?: string | undefined | null, data?: Uint8Array | undefined | null, dictVersion?: string | undefined | null, includeWarnings?: boolean | undefined | null, includeFyi?: boolean | undefined | null, checkFiles?: boolean | undefined | null, encoding?: string | undefined | null): ValidationReport
/**
 * The AGS4 rule catalogue as the gated `rules_meta.json` — byte-identical to
 * laterite-py's `list_rules()` and `lat-check --list-rules --json`. The TS
 * layer parses it into typed `RuleMeta[]`. No input file.
 */
export declare function listRules(): string
/**
 * One applied fix — the Node mirror of laterite-py's `applied[]` entries.
 * `kind`/`risk` are the serde snake_case strings (`strip_bom`, `safe`, …) so
 * the shape is identical across Python / CLI / Node.
 */
export interface AppliedFix {
  kind: string
  label: string
  rule: string
  line?: number
  risk: string
}
/**
 * The repair report — the Node mirror of laterite-py's `fix_file` dict. `ok` is
 * false only for un-fixable input (the TS layer raises then). `fixed` is the
 * repaired bytes (the original verbatim when nothing applied); `residual` is
 * what could *not* be mechanically fixed.
 */
export interface FixReport {
  ok: boolean
  errorKind?: string
  error?: string
  exitCode: number
  fixed: Buffer
  dictVersion: string
  resolution: string
  fixesApplied: number
  applied: Array<AppliedFix>
  residual: Array<Finding>
}
/**
 * Mechanically repair an AGS4 file (`path`) / `text` / `data`: apply the SAFE
 * fixes (plus the risky set when `includeRisky`), re-validate, and return the
 * fixed bytes + residual findings. Mirrors laterite-py's `fix()` /
 * `lat-check --fix`; the single `fix_document` orchestration is shared. The TS
 * layer wraps this into a `FixResult` (`.bytes` / `.text` / `.save(path)`).
 */
export declare function fixFile(path?: string | undefined | null, text?: string | undefined | null, data?: Uint8Array | undefined | null, dictVersion?: string | undefined | null, encoding?: string | undefined | null, includeRisky?: boolean | undefined | null): FixReport
/**
 * One group of columnar input — its code + an Arrow IPC stream (`Buffer`)
 * whose column names are the AGS headings.
 */
export interface GroupIpc {
  code: string
  ipc: Buffer
}
/**
 * The emit result. `bytes` is the AGS4 document; `findingsJson` is the
 * validator's `{rule:[…]}` map on the output; `fixesApplied` counts safe fixes.
 */
export interface EmitResult {
  bytes: Buffer
  findingsJson: string
  fixesApplied: number
}
/**
 * Build valid AGS4 from per-group **Arrow IPC** streams (the columnar
 * producer; the read boundary reversed). = `laterite-ags4-wasm`'s `to_ags4_ipc`.
 */
export declare function emitAgs4FromIpc(groups: Array<GroupIpc>, edition?: string | undefined | null, mode?: string | undefined | null): EmitResult
/**
 * A parsed AGS4 file held native-side — the Node analog of laterite-py's
 * `Reading` handle (and `laterite-ags4-wasm`'s `ParsedDataset`). Each group's typed
 * `RecordBatch` is built lazily on `tableIpc(code)` and dropped after the
 * bytes are returned, so peak residency is one batch.
 */
export declare class Reading {
  /** Group codes in file order (the order to load tables in). */
  groupCodes(): Array<string>
  /** The file's `TRAN_AGS` edition string, if present. */
  get tranAgs(): string | null
  /**
   * `{headings, units, types, sqlTypes}` for one group, or `null` if the
   * code isn't present. No Arrow built — cheap metadata only.
   */
  meta(code: string): GroupMeta | null
  /**
   * One group's rows as an Arrow **IPC stream** (`Buffer`), columns already
   * correctly typed. The Node analog of the pyo3-arrow capsule: the typed
   * columns come from the one shared emitter (`laterite_types::arrow_cols`), the
   * SAME casting Python/wasm use — so a file types byte-identically across
   * hosts. Returns `null` if the code isn't in the file.
   */
  tableIpc(code: string): Buffer | null
  /**
   * Re-emit byte-faithful AGS4 text from the retained parse (the raw DATA
   * values, unchanged). = laterite-py's `Reading::emit`.
   */
  emit(): string
}
