/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A parsed AGS4 file held native-side — the Node analog of laterite-py's
 * `Reading` handle (and `laterite-ags4-wasm`'s `ParsedDataset`). Each group's typed
 * `RecordBatch` is built lazily on `tableIpc(code)` and dropped after the
 * bytes are returned, so peak residency is one batch.
 */
export declare class Reading {
  /** Group codes in file order (the order to load tables in). */
  groupCodes(): Array<string>
  /** The file's `TRAN_AGS` edition string, if present. */
  get tranAgs(): string | null
  /**
   * `{headings, units, types, sqlTypes}` for one group, or `null` if the
   * code isn't present. No Arrow built — cheap metadata only.
   */
  meta(code: string): GroupMeta | null
  /**
   * One group's rows as an Arrow **IPC stream** (`Buffer`), columns already
   * correctly typed. The Node analog of the pyo3-arrow capsule: the typed
   * columns come from the one shared emitter (`laterite_ags4_types::arrow_cols`), the
   * SAME casting Python/wasm use — so a file types byte-identically across
   * hosts. Returns `null` if the code isn't in the file.
   */
  tableIpc(code: string, contentHash?: boolean | undefined | null, withKeys?: boolean | undefined | null): Buffer | null
  /**
   * Re-emit byte-faithful AGS4 text from the retained parse (the raw DATA
   * values, unchanged). = laterite-py's `Reading::emit`.
   */
  emit(): string
}

/**
 * The `.ags.idx` validity certificate — the Node mirror of laterite-py's
 * `Sidecar` pyclass, wrapping the ONE core `laterite_ags4_core::index::Sidecar`
 * so a Node-minted cert is byte-identical + checker-compatible with Python and
 * `lat certify`. `Ags4File.certify()` mints one; `read(file, {index})` consumes
 * it; a fresh + engine-matching cert lets a later `.validate()` skip the rule
 * engine.
 *
 * The DuckDB extension also reads these, but "checker-compatible" is the wrong
 * word for it: it never runs the checker. It consumes only the byte-offset index
 * for a sliced read, gating on size — so it shares the FORMAT with the doors
 * above, not the trust decision.
 */
export declare class Sidecar {
  /**
   * **Mint** a certificate for `data` — validating it here, first.
   *
   * This replaces `assemble`, whose signature was
   * `(data, edition, checkedAt, warnings?, fyi?, …)`: the caller told it what the
   * verdict had been, and the OPTIONAL counts defaulted to zero. Nothing on the TS
   * side ever passed them. So every certificate this addon produced recorded "0
   * warnings, 0 FYI" without anything having looked, and a later warnings request read
   * that zero and skipped the engine.
   *
   * There is no parameter here through which a caller could assert a verdict. `mint`
   * runs the rules itself, with both tiers on, and records what they returned. It
   * refuses a file with ERRORS; warnings and FYI are recorded, not fatal.
   */
  static mint(data: Uint8Array, checkedAt: string, dictVersion?: string | undefined | null, encoding?: string | undefined | null, compat?: string | undefined | null, dictPath?: string | undefined | null, dictBytes?: Uint8Array | undefined | null, dictReplace?: boolean | undefined | null): Sidecar
  /**
   * Parse a certificate from its on-disk `.ags.idx` JSON bytes, rejecting an
   * unknown format version. Throws on malformed / unsupported JSON.
   */
  static fromJson(data: Uint8Array): Sidecar
  /** Serialise to the on-disk `.ags.idx` JSON (pretty). */
  toJson(): Buffer
  /**
   * Is this certificate still current for `data`? Strong check: format version +
   * byte length + SHA-256. A mismatch means the source changed under the cert.
   */
  isFreshFor(data: Uint8Array): boolean
  get version(): number
  /**
   * The certified source's byte length (a JS number; AGS files are well within
   * the 2^53 safe-integer range).
   */
  get size(): number
  get sha256(): string
  /** The AGS edition the rules were run against. */
  get edition(): string
  /**
   * Was that edition FORCED (`dictVersion`), or auto-resolved from `TRAN_AGS`? One
   * fact with the edition string, not two — a forced run and an auto run can name the
   * same edition having applied different dictionaries.
   */
  get editionForced(): boolean
  get validator(): string
  /**
   * The fingerprint of the rule engine that produced this verdict — a hash of the rule
   * sources and the bundled dictionary, NOT the addon's version. A rule can change
   * without a version bump; this cannot.
   */
  get engine(): string
  get compat(): string | null
  get checkedAt(): string
  /**
   * The decoder the certified bytes were READ through (`"UTF-8"`, `"windows-1252"`, …).
   * The rules judge the TEXT the bytes decode to, and two decoders can reach two
   * verdicts on one unchanged file — so a cert minted under one does not answer a
   * request made under another.
   */
  get encoding(): string
  /**
   * Findings of each tier that the validation **measured** — or `null` if it never ran
   * that tier's rules. `null` is the point: the old format stored a plain number that
   * defaulted to 0, so "found none" and "never looked" were the same value.
   */
  get errors(): number | null
  get warnings(): number | null
  get fyi(): number | null
  /**
   * The groups the file's own DICT declares (#768), sorted — or `null` for a
   * cert minted before the field existed (nothing measured; an empty array
   * means measured, the file declares nothing). Names only — the
   * definitions stay in `DICT`, which the byte index locates.
   */
  get defines(): Array<string> | null
}

/**
 * AGS4 bytes → `.xlsx` workbook bytes (one worksheet per group). `orderedKeys`
 * forces the worksheet order; otherwise AGS4 source order. The bytes twin of
 * `ags4ToExcel`.
 */
export declare function ags4BytesToXlsx(data: Uint8Array, orderedKeys?: Array<string> | undefined | null, recoverDuplicateHeadings?: boolean | undefined | null, truncateExcessFields?: boolean | undefined | null): ExcelBytesResult

/**
 * Write an AGS4 file's groups to an `.xlsx` — one worksheet per group.
 * `orderedKeys` forces the worksheet order; otherwise AGS4 source order.
 */
export declare function ags4ToExcel(agsPath: string, xlsxPath: string, orderedKeys?: Array<string> | undefined | null): ExcelStats

/**
 * One applied fix — the Node mirror of laterite-py's `applied[]` entries.
 * `kind`/`risk` are the serde `snake_case` strings (`strip_bom`, `safe`, …) so
 * the shape is identical across Python / CLI / Node.
 */
export interface AppliedFix {
  kind: string
  label: string
  rule: string
  line?: number
  risk: string
}

/**
 * AGS spec type code → canonical category label (`"string"`, `"integer"`,
 * `"decimal"`, `"datetime"`, `"date"`, `"time"`, `"bool"`, `"enum"`), or `null`
 * for unknown codes (the TS wrapper re-raises as an error).
 */
export declare function canonicalType(agsType: string): string | null

/**
 * Compare two AGS4 documents (raw `a` baseline / `b` revision bytes) — the
 * revision diff, mirroring laterite-py's `diff()` and the wasm `diff()`.
 * `dict_version` `None`/`"auto"` resolves the KEY-heading edition from the
 * revision (`b`)'s `TRAN_AGS`, else forces it; `encoding` decodes both sides
 * (default UTF-8). Returns the serialised `RevisionDelta` JSON — the shared
 * `laterite-ags4-diff` leaf's `{groups, groups_added, groups_removed,
 * total_added, total_removed, total_changed}` shape — that the TS `diff()`
 * parses. Parse failure throws the mapped error (`NotAgs4Error`, …).
 */
export declare function diff(a: Uint8Array, b: Uint8Array, dictVersion?: string | undefined | null, encoding?: string | undefined | null): string

/**
 * Presentation hint for a numeric AGS type: `"2DP"` → `"%.2f"`, `"3SF"` →
 * `"%.3g"`, `"1SCI"` → `"%.1e"`; `null` for non-numeric / unknown codes.
 */
export declare function displayHint(agsType: string): string | null

/**
 * The bundled AGS4 editions, oldest first — `["4.0.3", … "4.2"]`.
 *
 * GENERATED all the way down: `DictVersion::ALL` is emitted by the reference leaf's
 * build.rs from `ags_dictionary.json`. Exposed so no JS-side list of editions is
 * hand-written — the CLI's `--dict-version` census reads this, and it is the same
 * const the Rust binary and the Python wheel answer with, so the three launchers
 * cannot disagree about which editions exist.
 */
export declare function editions(): Array<string>

/**
 * Build valid AGS4 from per-group **Arrow IPC** streams (the columnar
 * producer; the read boundary reversed). = `laterite-ags4-wasm`'s `to_ags4_ipc`.
 */
export declare function emitAgs4FromIpc(groups: Array<GroupIpc>, edition?: string | undefined | null, mode?: string | undefined | null, units?: Record<string, Record<string, string>> | undefined | null, types?: Record<string, Record<string, string>> | undefined | null, synthesiseMetadata?: boolean | undefined | null, tran?: TranInput | undefined | null): EmitResult

/**
 * The unchecked door (#881): [`emit_ags4_from_ipc`]'s marshalling handed to
 * the engine's judge-free entry — bytes out, nothing validated, pinned
 * byte-identical to the `report` build (the #858 contract). No mode /
 * synthesis / TRAN parameters on purpose: there is no verdict for a mode to
 * act on, and synthesis fills gaps only a report would surface.
 */
export declare function emitAgs4FromIpcUnchecked(groups: Array<GroupIpc>, edition?: string | undefined | null, units?: Record<string, Record<string, string>> | undefined | null, types?: Record<string, Record<string, string>> | undefined | null): Buffer

/**
 * The emit result. `bytes` is the AGS4 document; `findingsJson` is the
 * validator's `{rule:[…]}` map on the output; `applied` is the safe-fix ledger
 * `AutoFix` made (same shape as `fix()`'s `FixReport.applied`); `fixesApplied`
 * is its length.
 */
export interface EmitResult {
  bytes: Buffer
  findingsJson: string
  applied: Array<AppliedFix>
  fixesApplied: number
}

/**
 * The identity of the engine that produces verdicts — a build-time digest over
 * every rule source, the dictionary, and the rules catalogue.
 *
 * This is what makes "the same engine everywhere" a checkable claim rather than
 * an assumption. Two surfaces reporting the same value ARE running the same
 * rules; two reporting the same `version()` merely shipped together. It is also
 * what an `.ags.idx` certificate stamps, so a verdict can be traced to the
 * engine that produced it.
 */
export declare function engineFingerprint(): string

/**
 * The version of the validation engine underneath — a hand-bumped semver.
 *
 * Useful for humans, and useless as an identity: edit a rule without bumping the
 * crate and this is unchanged. [`engine_fingerprint`] is the value that cannot
 * lie about what produced a verdict.
 */
export declare function engineVersion(): string

/**
 * An in-memory Excel conversion result: the produced `bytes` (an `.xlsx`
 * workbook or an `.ags` document) plus the same conversion stats. The bytes
 * twin of the path functions, so an uploaded workbook / a fixed handle needn't
 * hit disk — the same FS-free cores the browser surface uses.
 */
export interface ExcelBytesResult {
  bytes: Buffer
  sheetsWritten: number
  rowsWritten: number
  warnings: Array<string>
}

/** The outcome of an Excel conversion (mirrors `laterite_ags4_excel::ExcelStats`). */
export interface ExcelStats {
  /** Worksheets written (AGS4→XLSX) or read (XLSX→AGS4). */
  sheetsWritten: number
  /** DATA rows written across all sheets. */
  rowsWritten: number
  /** Non-fatal conversion warnings. */
  warnings: Array<string>
}

/**
 * Read an `.xlsx` back into an AGS4 file. `formatNumericColumns` (default
 * true) re-applies AGS4 numeric formatting to numeric-looking columns.
 */
export declare function excelToAgs4(xlsxPath: string, agsPath: string, formatNumericColumns?: boolean | undefined | null): ExcelStats

/**
 * The edition `auto` falls back to when a file's `TRAN_AGS` is missing or
 * unrecognised (the union's `fallback_edition`, generated).
 */
export declare function fallbackEdition(): string

/** One rule violation (omitting `severity` ⇒ error, matching the engine). */
export interface Finding {
  rule: string
  line?: number
  group: string
  desc: string
  severity?: string
}

/**
 * Mechanically repair an AGS4 file (`path`) / `text` / `data`: apply the SAFE
 * fixes (plus the risky set when `includeRisky`, narrowed by `only` / widened-
 * back by `exclude`), re-validate, and return the fixed bytes + residual
 * findings. Mirrors laterite-py's `fix()` / `lat fix`; the single
 * `fix_document_selective` orchestration is shared. The TS layer wraps this into
 * a `FixResult` (`.bytes` / `.text` / `.save(path)`) and adds `inPlace` / `out`
 * write-back on top.
 */
export declare function fixFile(path?: string | undefined | null, text?: string | undefined | null, data?: Uint8Array | undefined | null, dictVersion?: string | undefined | null, encoding?: string | undefined | null, includeRisky?: boolean | undefined | null, only?: Array<string> | undefined | null, exclude?: Array<string> | undefined | null, dictPath?: string | undefined | null, dictBytes?: Uint8Array | undefined | null, dictReplace?: boolean | undefined | null): FixReport

/**
 * The repair report — the Node mirror of laterite-py's `fix_file` dict. `ok` is
 * false only for un-fixable input (the TS layer raises then). `fixed` is the
 * repaired bytes (the original verbatim when nothing applied); `residual` is
 * what could *not* be mechanically fixed.
 */
export interface FixReport {
  ok: boolean
  errorKind?: string
  error?: string
  exitCode: number
  fixed: Buffer
  dictVersion: string
  resolution: string
  fixesApplied: number
  applied: Array<AppliedFix>
  residual: Array<Finding>
}

/**
 * One group of columnar input — its code + an Arrow IPC stream (`Buffer`)
 * whose column names are the AGS headings.
 */
export interface GroupIpc {
  code: string
  ipc: Buffer
}

/** Per-group schema — parallel arrays, one entry per heading. */
export interface GroupMeta {
  headings: Array<string>
  units: Array<string>
  /** AGS TYPE codes from the file's TYPE row (e.g. "2DP", "DT", "ID"). */
  types: Array<string>
  /**
   * The SQL/DuckDB column type each heading lands as ("DOUBLE", "BIGINT",
   * "TIMESTAMP", "VARCHAR", …).
   */
  sqlTypes: Array<string>
  /** 1-indexed source line of each DATA row (parallel to the group's rows). */
  lineNumbers: Array<number>
}

/**
 * The AGS4 rule catalogue as the gated `rules_meta.json` — byte-identical to
 * laterite-py's `list_rules()` and `lat rules --json`. The TS
 * layer parses it into typed `RuleMeta[]`. No input file.
 */
export declare function listRules(): string

/**
 * Reconcile N AGS4 deliveries of one project into one file (raw `files` bytes,
 * ≥2) — the Node port of laterite-py's `merge()`, over the SAME shared
 * `laterite-ags4-merge` leaf the CLI uses. Files merge in argument order (a
 * later file wins a KEY conflict); rows are identified by their dictionary KEY
 * headings. A heading two files typed differently throws `MergeConflictError`
 * unless `onTypeClash` settles it — `"widen"` falls back to `X` (raw values kept),
 * `"promote"` keeps the greatest nDP precision (zero-padding the coarser values).
 * A complete `tran` stamps a synthesised merge-TRAN; omit it and TRAN is
 * reconciled like any other group — or, with `onMissingTran: "error"`, the
 * merge is refused before any bytes are produced. The edition is the newest file's `TRAN_AGS`
 * unless `dictVersion` forces it. Parse failure throws the mapped error.
 */
export declare function merge(files: Array<Uint8Array>, onTypeClash?: string | undefined | null, onMissingTran?: string | undefined | null, dictVersion?: string | undefined | null, encoding?: string | undefined | null, tran?: TranInput | undefined | null): MergeOutput

export interface MergeOutput {
  bytes: Buffer
  warningsJson: string
  revisionsJson: string
}

/**
 * The `--on-missing-tran` modes merge accepts, in declaration order —
 * `["reconcile", "error"]`.
 *
 * GENERATED for the same reason as [`type_clash_modes`], and the reason is that
 * enum's own history: it was hand-copied into the census values and the CLI's
 * error message, and a fourth mode would have reached neither. The sibling
 * option starts with one authority rather than acquiring one after the fact.
 */
export declare function missingTranModes(): Array<string>

/**
 * Result of `transportPack` / `transportLock`: output size, ratio vs source,
 * elapsed seconds.
 */
export interface PackStats {
  bytes: bigint
  ratio: number
  elapsedS: number
}

/**
 * Parse an AGS4 file (`path`), in-memory `text`, or raw `data` bytes into a
 * `Reading` handle. `encoding`: `"utf-8"` (default) / `"windows-1252"` / a label
 * — applies to `path` / `data` (text is already decoded). Throws the classified
 * `kind␟code␟message` (see the error-protocol note) on bad input.
 */
export declare function parseArrow(path?: string | undefined | null, text?: string | undefined | null, data?: Uint8Array | undefined | null, encoding?: string | undefined | null): Reading

/**
 * Parse an AGS4-shaped raw string into its canonical value — the same engine
 * the read path uses. Permissive: empty / unparseable → `null`. Returns native
 * JS: integer/decimal → number, bool → boolean, string/enum → string,
 * **datetime/date/time → the canonical string** (`"YYYY-MM-DD HH:MM:SS"` /
 * `"YYYY-MM-DD"` / `"HH:MM:SS"`), unknown code → the trimmed input.
 */
export declare function parseValue(raw: string | undefined | null, agsType: string): any

/**
 * Raw group cells for the Node CLI `lat read` — a JSON string
 * `{"order":[...],"groups":{code:{"headings":[...],"rows":[[cell,...]]}}}`,
 * straight from core's read codec (no typing), so `lat read --json` / `--csv`
 * match the Rust binary and Python byte-for-byte (#430).
 */
export declare function readGroupsRaw(path: string, recoverDuplicateHeadings?: boolean | undefined | null, truncateExcessFields?: boolean | undefined | null): string

/**
 * Parent chain from `code` up to the registry root — `[code, parent, …, root]`
 * (a root group returns `[code]`). Raises for an unknown code, so a root is
 * distinguishable from a miss.
 *
 * The walk is `laterite_ags4_core::registry::ancestor_chain`, the ONE Rust
 * definition of the group tree — the same leaf function the Python wheel binds
 * (`registry_fns.rs::registry_ancestor_chain`). Node used to re-walk `.parent`
 * pointers in TypeScript (`ts/registry.ts`), a hand-kept-in-sync copy of that
 * logic; routing through the binding removes it so the tree can't drift from the
 * leaf (laterite-dev#532, laterite-dev#527).
 */
export declare function registryAncestorChain(code: string): Array<string>

/**
 * The bundled standard dictionary for `edition` as JSON — the
 * `{ags_edition, groups:[{code, contents, parent, headings:[…]}]}` shape the
 * browser and `laterite.registry.dictionary()` also render, from the ONE shared
 * `dict::dictionary_dto` builder (#294 F#6). `None`/`"auto"` → the fallback
 * edition; else 4.0.3|4.0.4|4.1|4.1.1|4.2. The TS `registry.dictionary()` parses
 * it. (The generated `GROUPS` stays the default union registry.)
 */
export declare function registryDictionaryJson(edition?: string | undefined | null): string

/**
 * The KEY heading names a group inherits from its DIRECT parent — the
 * intersection of its KEY headings with the parent's — sorted for determinism
 * (the TS facade wraps this in a Set). Empty for a root; raises for an unknown
 * code.
 *
 * The intersection is `laterite_ags4_core::registry::inherited_key_names`, the
 * same leaf function the Python wheel binds; Node used to re-implement the
 * KEY-intersection logic in TypeScript. Deleting that copy is the point of laterite-dev#532
 * (part of the laterite-dev#527 leaf-convergence arc).
 */
export declare function registryInheritedKeyNames(code: string): Array<string>

/**
 * `lat read --csv` for one group: the rendered string, from core's ONE CSV
 * writer (RFC-4180-ish quoting). Replaces `ts/cli.ts`'s hand-ported `csvRow`.
 */
export declare function renderReadCsv(headings: Array<string>, rows: Array<Array<string>>): string

/**
 * `lat read --json` for one group: the rendered string, from core's ONE JSON
 * writer. `ts/cli.ts` used to build this with `JSON.stringify(x, null, 2)`
 * while the binary used `serde_json` and Python used `json.dumps` — three
 * different JSON libraries kept byte-identical by hand-discipline, with no gate
 * on `read` output (laterite-dev#530).
 */
export declare function renderReadJson(headings: Array<string>, rows: Array<Array<string>>): string

/**
 * What THIS SURFACE resolves an encoding label to — the canonical `encoding_rs`
 * name (`"UTF-8"`, `"windows-1252"`, `"ISO-8859-15"`), or `null` if it refuses.
 *
 * Deliberately routed through this crate's OWN `resolve_encoding` wrapper, not the
 * parse leaf directly. That distinction is the whole point: the leaf was always
 * correct, and the bug lived in the wrapper *above* it (`…resolve_encoding(label)
 * .unwrap_or(UTF_8)`), which turned every unknown label into a silent UTF-8 decode.
 * A census that asked the leaf would have agreed with itself and seen nothing. This
 * reports what a Node caller actually gets, so a reintroduced fallback shows up as
 * `"cp1252x" -> "UTF-8"` and the surface census fails.
 */
export declare function resolveEncodingLabel(label?: string | undefined | null): string | null

/**
 * Validate an AGS4 file (`path`) or `text` against the AGS4 rules. `dict_version`
 * `None`/`"auto"` auto-detects from `TRAN_AGS`, else forces an edition. Returns
 * the `{ok:false}` failure report (not a throw) for un-validatable input.
 *
 * Severity tiers track importance (like a compiler): errors **and WARNINGs** are
 * returned by default (`includeWarnings` defaults to `true`); pass `false` for
 * errors-only. `includeFyi` (default `false`) adds the low-signal FYI tier.
 *
 * Those two decide what the report SHOWS. What it CONCLUDES is decided by
 * errors alone — `warningsAsErrors` (default `false`) is the separate dial that
 * makes warnings fatal too, the compiler's `-Werror`. FYIs never fail.
 */
export declare function runCheck(path?: string | undefined | null, text?: string | undefined | null, data?: Uint8Array | undefined | null, dictVersion?: string | undefined | null, includeWarnings?: boolean | undefined | null, includeFyi?: boolean | undefined | null, warningsAsErrors?: boolean | undefined | null, checkFiles?: boolean | undefined | null, encoding?: string | undefined | null, dictPath?: string | undefined | null, dictBytes?: Uint8Array | undefined | null, dictReplace?: boolean | undefined | null, cert?: Sidecar | undefined | null, strictCert?: boolean | undefined | null): ValidationReport

/**
 * The merge result. `bytes` is the reconciled AGS4 document; `warningsJson` and
 * `revisionsJson` are the advisory-notes and per-row-revision audits (arrays of
 * `{kind,group,heading,message}` / `{group,key,changed,winner_file}` — the
 * engine structs' canonical wire shape, byte-identical to PyO3's fragments)
 * that the TS `merge()` parses, renaming `winner_file` → `winnerFile` for its
 * own API (#542).
 * The transmission a file represents, as ONE napi object.
 *
 * Five REQUIRED headings crossed this boundary as five consecutive same-typed
 * `Option<String>` parameters, hand-flattened by `ts/index.ts` — a transposition
 * no compiler on either side could catch. Named fields end that.
 */
export interface TranInput {
  issue?: string
  date?: string
  producer?: string
  recipient?: string
  status?: string
  description?: string
  remarks?: string
}

/**
 * zstd-compress, then age-encrypt with `password` → `dest`. Compress-then-
 * encrypt is load-bearing: zstd needs low-entropy input; ciphertext is random.
 */
export declare function transportLock(src: string, dest: string, password: string, level?: number | undefined | null, logN?: number | undefined | null): PackStats

/**
 * zstd-compress, then age-encrypt `data` with `password` in memory → bytes —
 * no plaintext on disk. `level` is 1–22 (default 9).
 */
export declare function transportLockBytes(data: Uint8Array, password: string, level?: number | undefined | null, logN?: number | undefined | null): Buffer

/** zstd-compress `src` → `dest`. `level` is 1–22 (default 9, the AGS sweet spot). */
export declare function transportPack(src: string, dest: string, level?: number | undefined | null): PackStats

/** zstd-compress `data` in memory → bytes. `level` is 1–22 (default 9). */
export declare function transportPackBytes(data: Uint8Array, level?: number | undefined | null): Buffer

/**
 * age-decrypt with `password`, then zstd-decompress → `dest`. Wrong passphrase
 * / non-passphrase envelopes surface as an error.
 */
export declare function transportUnlock(src: string, dest: string, password: string): UnpackStats

/**
 * age-decrypt with `password`, then zstd-decompress `data` in memory → bytes.
 * Wrong passphrase / non-passphrase envelopes surface as an error.
 */
export declare function transportUnlockBytes(data: Uint8Array, password: string): Buffer

/** zstd-decompress `src` → `dest`. */
export declare function transportUnpack(src: string, dest: string): UnpackStats

/** zstd-decompress `data` in memory → bytes (the twin of `transportPackBytes`). */
export declare function transportUnpackBytes(data: Uint8Array): Buffer

/**
 * The `--on-type-clash` modes merge accepts, in declaration order —
 * `["error", "widen", "promote"]`.
 *
 * GENERATED, same as [`editions`]: the set is owned by `TypeClashMode::ALL` in
 * laterite-ags4-merge. Exposed so the JS launcher does not keep a hand-written
 * copy — it had two (the census `values` for `merge --on-type-clash`, and the
 * unknown-mode error message in `cli.ts`), and a fourth mode added to the enum
 * would have reached neither (laterite-dev#555).
 */
export declare function typeClashModes(): Array<string>

/** Result of `transportUnpack` / `transportUnlock`: output size, elapsed seconds. */
export interface UnpackStats {
  bytes: bigint
  elapsedS: number
}

/**
 * The validation report — the Node mirror of laterite-py's `run_check` dict.
 * `ok` is **false only for un-validatable input** (the TS `raiseFor` raises
 * then); rule *violations* come back in `findings` with `ok:true`. `Report`'s
 * `isValid` is the separate `count == 0`. `json`/`ndjson` are byte-identical
 * to `lat validate --json` / `--ndjson`.
 */
export interface ValidationReport {
  ok: boolean
  /**
   * Set (with `error`) only when `ok` is false — the failure kind the TS
   * `raiseFor` maps to an exception (`not_ags4`, `unsupported_edition`, …).
   */
  errorKind?: string
  error?: string
  /**
   * Mirrors the `lat` binary: 0 valid / 1 findings on success;
   * 3 not-found/io, 4 not-utf8/not-ags4/bad-edition, 5 bad-dict on failure.
   */
  exitCode: number
  file: string
  dictVersion: string
  resolution: string
  /** Every finding in the report, whatever its tier — what it SHOWS. */
  count: number
  /**
   * The verdict — what it CONCLUDES (#321). Not `count == 0`: a warning is
   * shown by default and does not fail, so a file can be `valid` with a
   * non-zero `count`. Always agrees with `exitCode == 0`.
   */
  valid: boolean
  /**
   * Per-tier counts, so a caller can act on the split without re-walking
   * `findings`. They sum to `count`.
   */
  errors: number
  warnings: number
  fyi: number
  /**
   * Did an `index` certificate stand in for the rule engine? Never "the file was not
   * checked": a world check (Rule 20's on-disk half) runs even on a certified read.
   */
  certified: boolean
  /**
   * If a certificate was offered and NOT used, the stable token for why (the core
   * `RevalidateReason::as_str`, e.g. `"dictionary_changed"`). `None` when no cert was
   * offered, or it was vouched.
   */
  revalidateReason?: string
  findings: Array<Finding>
  json: string
  ndjson: string
}

/**
 * The version of THIS package — the npm `laterite` you installed.
 *
 * Not the engine's. Since the tiers split (#202) those are two numbers, and this
 * crate is stamped with the product one precisely so this export keeps answering
 * the question a caller is actually asking. For the engine, see
 * [`engine_version`] and [`engine_fingerprint`].
 */
export declare function version(): string

/**
 * `.xlsx` workbook bytes → AGS4 bytes. `formatNumericColumns` (default true)
 * re-applies AGS4 numeric formatting to numeric-looking columns. The bytes twin
 * of `excelToAgs4`.
 */
export declare function xlsxBytesToAgs4(data: Uint8Array, formatNumericColumns?: boolean | undefined | null): ExcelBytesResult
