"""The edition set has ONE source, and every launcher accepts all of it.

`DictVersion::ALL` is generated by the reference leaf's `build.rs` from
`ags_dictionary.json`. That set was nevertheless hand-copied around nine times across
the tree — and the Rust CLI's copy was the sharpest trap: its rejection MESSAGE was
generated from the list while its match arms were not, so bundling `4.3` would have
shipped a `lat` that rejects `4.3` with a message advertising `4.3`. Nothing failed,
because nothing compared the two.

Most of these pass trivially today. They are written for the day the dictionary
bundles another edition: anything that reintroduces a hand-list goes red the moment
`registry_editions()` moves past it.
"""

from __future__ import annotations

import json
from pathlib import Path

import laterite
import pytest
from laterite import _cli
from laterite import _laterite_native as _native

REPO = Path(__file__).resolve().parents[3]
_DICT = (
    REPO / "rust-packages" / "laterite-ags4-reference" / "data" / "ags_dictionary.json"
)

_CLEAN = "\r\n".join(
    [
        '"GROUP","PROJ"',
        '"HEADING","PROJ_ID"',
        '"UNIT",""',
        '"TYPE","ID"',
        '"DATA","P1"',
        "",
    ]
)


def test_the_native_edition_list_is_the_dictionarys_own() -> None:
    """The bridge itself: what Rust hands Python IS ags_dictionary.json's `editions`."""
    assert (
        list(_native.registry_editions()) == json.loads(_DICT.read_text())["editions"]
    )


def test_the_fallback_is_the_dictionarys_own() -> None:
    assert (
        _native.registry_fallback_edition()
        == json.loads(_DICT.read_text())["fallback_edition"]
    )


def test_the_cli_offers_exactly_the_bundled_editions() -> None:
    """`--dict-version` choices are derived, not hand-listed.

    `_DICT_CHOICES` used to be a literal tuple. It is now `("auto", *editions)`, so
    this cannot drift — and if someone pastes the literal back, a newly bundled
    edition breaks it.
    """
    assert ("auto", *_native.registry_editions()) == _cli._DICT_CHOICES


@pytest.mark.parametrize("edition", _native.registry_editions())
def test_every_bundled_edition_is_accepted_by_the_library(edition: str) -> None:
    """Not "the name is in a list" — the engine must actually VALIDATE against it."""
    report = laterite.read(_CLEAN).validate(dict_version=edition).report
    assert report is not None


@pytest.mark.parametrize("edition", _native.registry_editions())
def test_every_bundled_edition_is_accepted_by_the_uvx_cli(
    edition: str, tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """End-to-end through the launcher's own argv path.

    Exit 5 is "bad arguments" — the code the CLI returns for an edition it does not
    know. That is the failure this whole change exists to prevent, so assert against
    it directly rather than against a parse tree.
    """
    f = tmp_path / "clean.ags"
    f.write_text(_CLEAN)
    code = _cli.main(["validate", str(f), "--dict-version", edition])
    capsys.readouterr()
    assert code != 5, (
        f"the uvx launcher rejected --dict-version {edition}, which the dictionary bundles"
    )


def test_an_unbundled_edition_is_still_rejected(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Deriving the list must not turn the parser into a pushover."""
    f = tmp_path / "clean.ags"
    f.write_text(_CLEAN)
    assert "9.9" not in _native.registry_editions()
    assert _cli.main(["validate", str(f), "--dict-version", "9.9"]) == 5
    capsys.readouterr()


def test_the_emit_path_accepts_every_bundled_edition() -> None:
    """`emit_typed.rs::parse_edition` was a SECOND hand-written edition parser, in the
    same crate as a correct one (`parse_dv`). It now asks the generated `from_edition`,
    and `auto` resolves to the generated FALLBACK rather than a hard-coded `4.1.1`."""
    import polars as pl

    frame = {"PROJ": pl.DataFrame({"PROJ_ID": ["P1"]})}
    for edition in _native.registry_editions():
        out = laterite.build_ags4(frame, dict_version=edition)
        assert out.bytes, f"build_ags4 produced nothing for edition {edition}"

    with pytest.raises(RuntimeError, match="unknown edition"):
        laterite.build_ags4(frame, dict_version="9.9")
