#!/usr/bin/env python
"""AGS-Wiki lint — link/mermaid/scaffold-invariant checks (read-only).

Run:  python ags-wiki/.bootstrap/lint.py
Exit 0 = clean. Used by the LINT workflow (AGS-WIKI.md §12).

Phase A (2026-07-09, wiki-reliability-hardening plan, output/wiki-
reliability-plan.md): added A1 (repo: dead-ref scan) + A2 (retired-
terms tripwire) + A9 (ext: allowlist) + A11 (historical/retired
exemption markers). A9/A11 are report-only diagnostics; A1/A2 started
report-only and GRADUATED to hard whole-vault checks (#75, 2026-07-26,
once the grandfathered backlog reached 0 — live content only, log.md/
index.md exempt, A11-marked mentions filtered). A12 (2026-08-13, the
week-33 shelf-read) resolves the frontmatter `location:` field on
`type: source` pages — a declared path A1's citation grammar cannot
see — and is HARD from the start (see its block for why it needed no
grandfathering). The hard checks that
drive the exit code are broken wikilinks / unbalanced mermaid / orphans /
crate-map completeness / crate-map edge-correctness / erDiagram group codes /
related-dangling / superseded-tombstone / owns-uniqueness / `location:`
resolution (A12); the orphan check counts
inbound links with index.md/log.md excluded (plan item D1, graduated to
hard-fail once the backlog reached 0 in #451). Two are the C5
mermaid-content checks (2026-07-10): the crate-map graph must name every
`rust-packages/Cargo.toml` workspace member, and every `erDiagram` entity
must be a documented group code (in the AGS4 dictionary OR carrying a wiki
group page — so AGS-L / concept groups aren't mis-flagged). The last three
are the Phase D governance gates (2026-07-10): D2 hard-fails a `related:`
target that resolves to no page (non-reciprocal edges stay advisory, and only
for non-hub targets — degree-based, #75 2026-07-26); D4
hard-fails a `status: superseded` page lacking `superseded_by:` (with every
target resolving) or a read-time tombstone callout; D7 hard-fails an `owns:`
topic slug claimed by more than one page (the one-owner-per-topic gate).

A5 — `--since <ref>` (default `origin/main`): diff-scoped ratchet, the
per-PR advisory mode. WITHOUT it (a plain whole-vault run — the nightly's
enforcing half), A1/A2 are HARD over live content: any dead `repo:` ref or
un-exempted retired-term hit fails the run (graduation above; the backlog
that was grandfathered here is now cleared). WITH it, an A1/A2 finding
fails the run *only* if it lands on a line `git diff --unified=0
<ref>...HEAD -- ags-wiki` shows as added/modified — i.e. only NEW rot
bites, so a contributor is never blocked over a page they never touched;
nothing pre-existing retroactively fails. `log.md` and
`index.md` are exempt from the ratchet entirely (both A1 and A2) — both
are machine-maintained, not hand-authored claims: log.md is append-only
history (a new entry describing a retired-term fix necessarily *names*
the term, retrospective by construction — proven the hard way: this
file's own log.md entry for this feature tripped A2 before the exemption
existed), and index.md is regenerated by reindex.py, whose D4
Retired/Superseded catalog names each tombstone page by a stem that IS a
retired package name (see RATCHET_EXEMPT_FILES).
`.github/workflows/wiki-lint.yml` runs this `--since` mode against the
PR's base branch as ADVISORY fast feedback (deliberately NOT a required
check — see that file's header for why); the whole-vault enforcement,
which opens the tracking issue on failure, is `nightly.yml`'s wiki-lint
job.
"""

from __future__ import annotations

import difflib
import json
import re
import subprocess
import sys
import tomllib
from collections import Counter
from pathlib import Path
from typing import TYPE_CHECKING

# The `repo:` citation grammar lives in refs.py so tools other than the linter
# can resolve a citation — importing lint.py to get at it is not an option, and
# re-deriving it locally is the drift this vault's checks exist to catch.
from refs import (
    REPO_REF,
    TRAILING_PUNCT,
    body_after_frontmatter,
    frontmatter_block,
    path_exists,
    resolve_ref,
)

if TYPE_CHECKING:
    from collections.abc import Sequence

WIKI = Path(__file__).resolve().parent.parent
REPO_ROOT = WIKI.parent
CLAUDE_MD = REPO_ROOT / "CLAUDE.md"
SKIP_DIRS = {".obsidian", ".bootstrap", "templates"}
TEMPLATES_DIR = WIKI / "templates"
# pages exempt from the no-orphan / related-reciprocity / frontmatter-schema
# checks by design: navigation hubs (not instances of a page class) and
# `_`-prefixed register pages (already exempt from orphan-checking above).
HUB_STEMS = {"index", "log", "start-here", "AGS-WIKI"}


# C5 (wiki-reliability plan): mermaid-content checks. Diagrams encode
# enumerable facts (crate names, group codes) by hand, and only the fence
# *balance* was ever checked — so crate-map.md's own graph had silently dropped
# three workspace crates (ags4-compliance / ags4-perf / laterite-ags4-diff).
def _workspace_crates() -> set[str]:
    """Every crate in the Rust workspace — the SSOT the crate-map graph must name."""
    ct = REPO_ROOT / "rust-packages" / "Cargo.toml"
    if not ct.exists():
        return set()
    return set(tomllib.loads(ct.read_text()).get("workspace", {}).get("members", []))


def _group_codes() -> set[str]:
    """A *documented* AGS group: in the AGS4 union dictionary OR carrying a wiki
    group page. The vault has pages for AGS-L / concept groups (TREL, CONL, TRIL,
    …) that are not in the shipped AGS4 union, so an erDiagram may legitimately
    name them — the check is 'documented somewhere', not 'in the dictionary'
    (which would mis-flag the concept groups)."""
    dj = (
        REPO_ROOT
        / "rust-packages"
        / "laterite-ags4-reference"
        / "data"
        / "ags_dictionary.json"
    )
    codes = set(json.loads(dj.read_text())["groups"]) if dj.exists() else set()
    return codes | {p.stem for p in (WIKI / "groups").glob("*.md")}


def _erd_entities(block: str) -> set[str]:
    """The 4-char group codes named as entities in an `erDiagram` block — the
    relationship endpoints (`A ||--o{ B`) and entity headers (`A {`), NOT the
    `<type> <heading>` attribute lines inside the `{ }` (those aren't groups)."""
    ents: set[str] = set()
    for line in block.splitlines():
        s = line.strip()
        m = re.match(r"([A-Z][A-Z0-9]{3})\s*\|\|[-o{}]*\s*([A-Z][A-Z0-9]{3})", s)
        if m:
            ents.update(m.groups())
            continue
        m = re.match(r"([A-Z][A-Z0-9]{3})\s*\{", s)
        if m:
            ents.add(m.group(1))
    return ents


# C5 long-term (wiki-reliability plan #10): edge-correctness for the crate-map
# graph. Node-completeness (every workspace crate is a node) is already gated
# above; this gates the *edges*. The graph is a curated `flowchart LR` layering
# view, NOT a strict dependency DAG (its arrow direction is deliberately loose —
# `types-->core` reads leaf→consumer, `core-->parse` reads consumer→leaf), and
# it may omit edges for readability — so completeness/direction can't be gated.
# What CAN: every edge it *draws* must connect two crates with a real Cargo
# coupling in *either* direction. A phantom edge between two uncoupled crates
# (a stale arrow left after a dependency was dropped) is caught; the diagram
# stays free to simplify.
def _crate_deps() -> dict[str, set[str]]:
    """crate name -> its workspace-member dependency names (all dep sections)."""
    rp = REPO_ROOT / "rust-packages"
    ct = rp / "Cargo.toml"
    if not ct.exists():
        return {}
    members = tomllib.loads(ct.read_text()).get("workspace", {}).get("members", [])
    out: dict[str, set[str]] = {}
    for m in members:
        mct = rp / m / "Cargo.toml"
        if not mct.exists():
            continue
        d = tomllib.loads(mct.read_text())
        nm = d.get("package", {}).get("name")
        if not nm:
            continue
        deps: set[str] = set()
        for sec in ("dependencies", "build-dependencies", "dev-dependencies"):
            deps |= set(d.get(sec, {}).keys())
        out[nm] = deps
    return out


def _crate_map_edges() -> list[tuple[str, str]]:
    """(name, name) for each `A --> B` in crate-map.md's graph, resolving node
    ids through their `id[crate-name]` / `id[crate-name<br/>alias]` labels."""
    if not CRATE_MAP.exists():
        return []
    block = "\n".join(
        re.findall(r"```mermaid\n(.*?)```", CRATE_MAP.read_text(), re.DOTALL)
    )
    id2name = {
        m.group(1): m.group(2)
        for m in re.finditer(r"(\w+)\[([a-z0-9-]+)(?:<br/>[^\]]*)?\]", block)
    }
    return [
        (id2name.get(a, a), id2name.get(b, b))
        for a, b in re.findall(r"(\w+)\s*-->\s*(\w+)", block)
    ]


# Reliquary self-check (wiki-reliability): the "Machine-checked register" table
# in design/reliquary.md must stay true to the tree, so the register can't rot
# into a list of claims nobody verifies. Each gated row carries a `path::token`
# Verify anchor; a `removed` relic's token must be ABSENT at that path, a still-
# inventoried one (spotted/keep/mitigated) must be PRESENT. So a relic can't be
# marked removed while its code lingers, nor silently vanish while still listed
# present. Rows with Verify `—` are display-only (the legacy narrative register
# above it is not machine-checked). Token match is a literal substring scoped to
# the one file — precise enough given a hand-picked declaration-fragment token.
_RELIQUARY = WIKI / "design" / "reliquary.md"
_RELIQUARY_PRESENT = {"spotted", "keep", "mitigated"}
_RELIQUARY_ABSENT = {"removed"}


def _machine_register_rows(txt: str) -> list[dict]:
    """Rows of the `## Machine-checked register` table: {symbol, verify, status}.
    Columns are Symbol | Verify | Axis | Status | Removed-in | Evidence."""
    rows: list[dict] = []
    in_section = False
    for line in txt.splitlines():
        if line.startswith("## "):
            in_section = "machine-checked register" in line.lower()
            continue
        if not in_section:
            continue
        s = line.strip()
        if not s.startswith("|"):
            continue
        cells = [re.sub(r"[`*]", "", c).strip() for c in s.strip("|").split("|")]
        if len(cells) < 4 or cells[0].lower() == "symbol":
            continue
        if set("".join(cells)) <= set("-: "):  # header separator row
            continue
        rows.append(
            {"symbol": cells[0], "verify": cells[1], "status": cells[3].lower()}
        )
    return rows


def _reliquary_violations() -> list[str]:
    if not _RELIQUARY.exists():
        return []
    out: list[str] = []
    for r in _machine_register_rows(_RELIQUARY.read_text(encoding="utf-8")):
        verify, status, sym = r["verify"], r["status"], r["symbol"]
        if verify in ("", "—", "-"):
            continue
        if "::" not in verify:
            out.append(f"`{sym}`: malformed Verify {verify!r} (want `path::token`)")
            continue
        rel, token = verify.split("::", 1)
        target = REPO_ROOT / rel
        present = target.exists() and token in target.read_text(
            encoding="utf-8", errors="replace"
        )
        if status in _RELIQUARY_ABSENT and present:
            out.append(
                f"`{sym}` marked {status} but token `{token}` still present in {rel}"
            )
        elif status in _RELIQUARY_PRESENT and not present:
            out.append(
                f"`{sym}` marked {status} but token `{token}` not found in {rel} (stale row)"
            )
        elif status not in _RELIQUARY_PRESENT | _RELIQUARY_ABSENT:
            out.append(f"`{sym}` has unknown status {status!r}")
    return out


WORKSPACE_CRATES = _workspace_crates()
GROUP_CODES = _group_codes()
CRATE_MAP = WIKI / "concepts" / "crate-map.md"
bad_erd: list[str] = []  # erDiagram entities that name an undocumented group
# --full: don't truncate the Phase A finding lists (default caps them for
# everyday terminal use; a full-backlog review — e.g. staging the A4 bulk
# repair — wants every line, not "… +N more").
FULL = "--full" in sys.argv
A_LIMIT = 10_000 if FULL else 20

# --since [<ref>] (default origin/main, see A5 in the module docstring).
# A bare `--since` (no value, or the next arg is itself a flag) defaults to
# origin/main — this repo's default branch — so a local `--since` invocation
# doesn't need the ref typed out; CI passes the base branch explicitly.
SINCE_REF: str | None = None
if "--since" in sys.argv:
    _si = sys.argv.index("--since")
    if _si + 1 < len(sys.argv) and not sys.argv[_si + 1].startswith("--"):
        SINCE_REF = sys.argv[_si + 1]
    else:
        SINCE_REF = "origin/main"

md = sorted(p for p in WIKI.rglob("*.md") if not (set(p.parts) & SKIP_DIRS))


def parse_added_ranges(since_ref: str) -> dict[str, set[int]]:
    """WIKI-relative posix path -> set of line numbers added/modified in
    `git diff --unified=0 <since_ref>...HEAD -- ags-wiki`. Powers A5: a
    debt-check finding only fails the run if its (file, line) is in this
    map — everything else is grandfathered. `--unified=0` means each hunk
    is exactly its changed lines (no context), so a hunk's `+start,count`
    maps directly onto `count` consecutive new-file line numbers starting
    at `start`, regardless of how they interleave with removed lines
    (removed lines don't consume new-file line numbers)."""
    try:
        out = subprocess.run(
            [
                "git",
                "-C",
                str(REPO_ROOT),
                "diff",
                "--unified=0",
                f"{since_ref}...HEAD",
                "--",
                "ags-wiki",
            ],
            capture_output=True,
            text=True,
            check=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        print(
            f"--since {since_ref!r}: git diff failed ({e}); can't ratchet, aborting.",
            file=sys.stderr,
        )
        sys.exit(2)
    ranges: dict[str, set[int]] = {}
    cur_file: str | None = None
    hunk_re = re.compile(r"^@@ -\d+(?:,\d+)? \+(\d+)(?:,(\d+))? @@")
    for line in out.stdout.splitlines():
        if line.startswith("+++ "):
            path = line[4:]
            if path == "/dev/null":
                cur_file = None
                continue
            stripped = path[2:] if path.startswith(("a/", "b/")) else path
            try:
                cur_file = Path(stripped).relative_to("ags-wiki").as_posix()
            except ValueError:
                cur_file = None  # touched file outside ags-wiki/ — not lint's concern
            continue
        m = hunk_re.match(line)
        if m and cur_file is not None:
            start = int(m.group(1))
            count = int(m.group(2)) if m.group(2) is not None else 1
            if count > 0:
                ranges.setdefault(cur_file, set()).update(range(start, start + count))
    return ranges


ADDED_RANGES: dict[str, set[int]] = parse_added_ranges(SINCE_REF) if SINCE_REF else {}


def in_added_range(rel: str, line: int) -> bool:
    return line in ADDED_RANGES.get(rel, set())


def net_removed_citations(since_ref: str) -> list[str]:
    """Tier-3 (#23): `repo:` citations REMOVED by this diff and not re-added
    elsewhere in it — a signal the diff de-grounded a claim (deleted the ref)
    rather than repointing it. Report-only: a legitimately-deleted page removes
    its refs too, so this flags for a human look, it doesn't fail the run.
    log.md/index.md exempt (machine-maintained, same as the ratchet)."""
    try:
        out = subprocess.run(
            [
                "git",
                "-C",
                str(REPO_ROOT),
                "diff",
                f"{since_ref}...HEAD",
                "--",
                "ags-wiki",
            ],
            capture_output=True,
            text=True,
            check=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return []
    added, removed = set(), []
    cur = None
    for line in out.stdout.splitlines():
        if line.startswith("+++ "):
            path = line[6:] if line[4:].startswith("b/") else line[4:]
            cur = path
            continue
        if line.startswith("+") and not line.startswith("+++"):
            added |= {m.group(0) for m in REPO_REF.finditer(line)}
        elif line.startswith("-") and not line.startswith("---"):
            if cur and Path(cur).name in {"log.md", "index.md"}:  # machine-maintained
                continue
            removed.extend((cur, m.group(0)) for m in REPO_REF.finditer(line))
    return [f"{f} -> {ref}" for f, ref in removed if ref not in added]


def strip_code(t: str) -> str:
    # drop fenced blocks then inline code so example [[links]] in
    # backticks (schema syntax docs) aren't treated as real links
    t = re.sub(r"```.*?```", "", t, flags=re.S)
    return re.sub(r"`[^`]*`", "", t)


# ---------------------------------------------------------------------------
# B1 — frontmatter schema, single-sourced from templates/ (never hand-
# duplicated here — the #31/D5 audit finding this plan explicitly guards
# against). Each `_template-<class>.md`'s own frontmatter block IS the
# required-key set for its `type:` — read it at lint-run time so a template
# edit (a field added/renamed) updates the check automatically, with no
# second copy to fall out of sync. Report-only: a page missing a key the
# template promises is real debt, but "well-formed per the vault's
# conventions" is being defined for the first time here (no #12-documented
# schema existed before Phase B) — see the AGS-WIKI.md §12 writeup for the
# judgment calls this makes.
# ---------------------------------------------------------------------------
def top_level_keys(fm: str) -> set[str]:
    # column-0 `key:` lines only — nested keys (e.g. `repo_refs:\n  root:`)
    # are indented and correctly excluded from the top-level required set.
    return set(re.findall(r"^([A-Za-z_][A-Za-z0-9_]*):", fm, re.M))


def line_at(text: str, pos: int) -> int:
    return text.count("\n", 0, pos) + 1


def fm_list(fm: str, key: str) -> list[str]:
    """A frontmatter `key:` value as a list of bare stems. Accepts both
    `key: [a, b/c]` and a single bare `key: a`; `key:` / `key: []` -> [].
    Path-qualified entries (`folder/stem`) reduce to the stem, matching the
    wikilink/related handling elsewhere in this file."""
    m = re.search(rf"^{re.escape(key)}:\s*(.*?)\s*$", fm, re.M)
    if not m:
        return []
    raw = m.group(1).strip()
    if raw.startswith("[") and raw.endswith("]"):
        raw = raw[1:-1]
    return [x.strip().split("/")[-1] for x in raw.split(",") if x.strip()]


# D4 (wiki-reliability plan): a superseded page must carry a read-time
# tombstone — a callout admonition (`> [!...]`) whose block text names the
# supersession/retirement — so a page for a deleted package can't sit indexed
# among live pages with no visible signal it's dead. Matches both in-vault
# styles: `> [!note] Retired package…` (single line) and the multi-line
# `> [!note]` / `> **Superseded … by [[…]]**` decision form.
_CALLOUT_BLOCK = re.compile(r"^> \[!\w+\].*(?:\n>.*)*", re.M)


def has_tombstone(body: str) -> bool:
    for m in _CALLOUT_BLOCK.finditer(body):
        if re.search(r"supersed|retired", m.group(0), re.I):
            return True
    return False


TEMPLATE_SCHEMA: dict[str, set[str]] = {}
for _tpath in sorted(TEMPLATES_DIR.glob("_template-*.md")):
    _tfm = frontmatter_block(_tpath.read_text(encoding="utf-8"))
    if _tfm is None:
        continue
    _tm = re.search(r"^type:\s*(\w+)", _tfm, re.M)
    if _tm:
        TEMPLATE_SCHEMA[_tm.group(1)] = top_level_keys(_tfm)

# B1 — status vocabulary per `type:`. AGS-WIKI.md §4 states the common
# stub->drafted->reviewed(->stale/contradicted) vocab plus 5 campaign-class
# overrides explicitly (insight/strategy/requirement/decision) but is
# SILENT on `experiment.status` (§4 documents `experiment.outcome`, not
# `.status`) — per §4's own rule ("controlled vocabularies are documented
# in each template"), the experiment template's inline comment
# (`planned | running | done`) is the documented source for that one, so
# it's included here rather than flagged as a gap. `source` has no override
# anywhere (template default is `stub`, same shape as the common classes) so
# it inherits COMMON. Two real gaps deliberately NOT papered over — see the
# report + AGS-WIKI.md §12: (a) `insight` status `refuted` is in live use
# (2 pages) but absent from both §4 and the template comment; (b) 3 retired
# `tools/*.md` pages use `superseded`, anticipating the not-yet-built D4
# tombstone convention. Both are left OUT of the vocab below so they surface
# as findings rather than being silently accepted.
# ---------------------------------------------------------------------------
_COMMON_STATUS = {"stub", "drafted", "reviewed", "stale", "contradicted"}
STATUS_VOCAB: dict[str, set[str]] = dict.fromkeys(
    (
        "rule",
        "group",
        "type",
        "observation",
        "tool",
        "concept",
        "edition",
        "comparison",
        "source",
    ),
    _COMMON_STATUS,
)
STATUS_VOCAB["insight"] = {"hypothesis", "probed", "confirmed", "ratified", "refuted"}
STATUS_VOCAB["strategy"] = {"proposed", "probed", "confirmed"}
STATUS_VOCAB["requirement"] = {
    "proposed",
    "accepted",
    "prototyped",
    "validated",
    "rejected",
}
STATUS_VOCAB["decision"] = {"proposed", "accepted", "superseded", "rejected"}
STATUS_VOCAB["experiment"] = {"planned", "running", "done"}
# `tool` additionally allows `superseded`: a retired-package page kept as a
# redirect-stub tombstone (tools/ags5-{ags4,db,models} — deleted in the F2c
# arc). Same terminal word `decision` already uses; the package was superseded
# by its Rust successor. Scoped to `tool` only — not the shared _COMMON_STATUS.
STATUS_VOCAB["tool"] = _COMMON_STATUS | {"superseded"}


# valid wikilink targets: every md basename + every root-level PDF basename
stems = {p.stem for p in md}
stems |= {p.name for p in WIKI.glob("*.pdf")}
stems |= {p.stem for p in WIKI.glob("*.pdf")}

LINK = re.compile(r"\[\[([^\]|#]+)(?:#[^\]|]+)?(?:\|[^\]]+)?\]\]")
RELATED_LINE = re.compile(r"^related:\s*\[(.*?)\]\s*$", re.M)
broken: list[str] = []
unbalanced: list[str] = []
not_stub: list[str] = []
# D1: the orphan check counts inbound wikilinks EXCLUDING links sourced from
# index.md/log.md (see ORPHAN_SOURCE_EXEMPT) — index.md auto-links nearly
# every page by design and log.md mentions pages in passing, so a naive
# whole-source count is structurally vacuous (it reported 0 orphans while 48
# pages were genuinely unreachable). #451 wired all 48, so this is now the
# HARD orphan check (graduated from report-only — plan item D1).
inbound_real: dict[str, int] = dict.fromkeys({p.stem for p in md}, 0)
ORPHAN_SOURCE_EXEMPT = {"index", "log"}
# CONTENT — the content-lifecycle classes the scaffold-stub check scopes to —
# is single-sourced with reindex.py in wiki-classes.json (D5), so the linter and
# the index generator can't disagree on the class list.
CONTENT = {
    c["dir"]
    for c in json.loads(
        (Path(__file__).resolve().parent / "wiki-classes.json").read_text(
            encoding="utf-8"
        )
    )["classes"]
    if c["content"]
}

# B1 — frontmatter-schema + status-vocab findings (report-only, see the
# TEMPLATE_SCHEMA/STATUS_VOCAB block above for the sourcing/judgment calls).
fm_missing: list[dict] = []  # required key(s) the template promises, absent
fm_no_type: list[str] = []
fm_unknown_type: list[str] = []
status_bad: list[dict] = []
# B2 — related: frontmatter, collected here so the reciprocity pass below
# (needs the WHOLE graph built first) can run after this loop completes.
related_map: dict[str, tuple[list[str], int]] = {}  # stem -> (targets, line#)
# D4 — status: superseded pages (tombstone + superseded_by gate) and D7 —
# owns: ownership claims (topic-uniqueness gate). Both collected in the page
# loop, gated after it (D7 needs the whole owns_map to spot a shared claim).
superseded_pages: list[dict] = []
owns_map: dict[str, list[str]] = {}  # topic slug -> claiming page stems

for p in md:
    txt = p.read_text(encoding="utf-8")
    rel = p.relative_to(WIKI).as_posix()
    # mermaid fences balanced
    if txt.count("```mermaid") and (txt.count("```") % 2 != 0):
        unbalanced.append(rel)
    # C5: erDiagram entities must be documented group codes (dict or a page)
    for block in re.findall(r"```mermaid\n(.*?)```", txt, re.DOTALL):
        if "erDiagram" not in block:
            continue
        bad_erd.extend(
            f"{rel} -> erDiagram names undocumented group [{ent}]"
            for ent in sorted(_erd_entities(block))
            if ent not in GROUP_CODES
        )
    # wikilink resolution + inbound tally (ignore links in code)
    # `\|` is Obsidian's table-safe alias separator → normalise to `|`
    for m in LINK.finditer(strip_code(txt).replace("\\|", "|")):
        tgt = m.group(1).strip().split("/")[-1]  # allow [[folder/stem|alias]]
        if tgt not in stems:
            broken.append(f"{rel} -> [[{m.group(1).strip()}]]")
        if p.stem not in ORPHAN_SOURCE_EXEMPT and tgt in inbound_real:
            inbound_real[tgt] += 1
    # scaffold-only: content pages must be status: stub
    cls = p.relative_to(WIKI).parts[0]
    if cls in CONTENT:
        fmm = re.search(r"^status:\s*(\w+)", txt, re.M)
        if not fmm or fmm.group(1) != "stub":
            not_stub.append(f"{rel} (status={fmm.group(1) if fmm else '?'})")

    # B1/B2/B3 — frontmatter/status/related checks skip navigation hubs and
    # `_`-prefixed register pages, same exemption as the orphan check (they
    # aren't instances of a template class, so the template schema/status
    # vocab don't apply to them).
    if p.stem in HUB_STEMS or p.stem.startswith("_"):
        continue
    fm = frontmatter_block(txt)
    if fm is None:
        fm_no_type.append(f"{rel} (no frontmatter block at all)")
        continue
    # D4/D7 — collected for the whole-vault gates below (before the type
    # checks, which `continue` on their own findings).
    sup = re.search(r"^status:\s*superseded\b", fm, re.M)
    if sup:
        superseded_pages.append(
            {
                "stem": p.stem,
                "file": rel,
                "line": line_at(txt, sup.start()),
                "targets": fm_list(fm, "superseded_by"),
                "tombstone": has_tombstone(body_after_frontmatter(txt)),
            }
        )
    for slug in fm_list(fm, "owns"):
        owns_map.setdefault(slug, []).append(p.stem)
    tm = re.search(r"^type:\s*(\S+)", fm, re.M)
    if not tm:
        fm_no_type.append(rel)
        continue
    typ = tm.group(1)
    if typ not in TEMPLATE_SCHEMA:
        fm_unknown_type.append(f"{rel} (type={typ})")
    else:
        missing = TEMPLATE_SCHEMA[typ] - top_level_keys(fm)
        if missing:
            fm_missing.append(
                {
                    "file": rel,
                    "line": line_at(txt, tm.start()),
                    "type": typ,
                    "missing": sorted(missing),
                }
            )
    sm = re.search(r"^status:\s*(\S+)", fm, re.M)
    if sm and typ in STATUS_VOCAB and sm.group(1) not in STATUS_VOCAB[typ]:
        status_bad.append(
            {
                "file": rel,
                "line": line_at(txt, sm.start()),
                "type": typ,
                "status": sm.group(1),
            }
        )
    rm = RELATED_LINE.search(fm)
    if rm:
        targets = [
            x.strip().split("/")[-1] for x in rm.group(1).split(",") if x.strip()
        ]
        related_map[p.stem] = (targets, line_at(txt, rm.start()))

# orphans (D1, HARD): content pages with zero inbound wikilinks under the
# index.md/log.md-excluded inbound_real tally. HUB_STEMS + `_`-register pages
# are exempt by design. A PR that adds an unreachable page fails the lint
# (graduated from report-only after #451 cleared the 48-page backlog to 0).
orphans_real = sorted(
    s
    for s, n in inbound_real.items()
    if n == 0 and s not in HUB_STEMS and not s.startswith("_")
)

# B2 — related: reciprocity + dangling targets, now that related_map covers
# every page. A dangling target (not a known stem) is reported once; a
# resolvable target that doesn't relate back is reported as non-reciprocal.
# Both sides of an edge landing on a HUB_STEMS/`_`-page are exempt — a hub
# is *expected* to be linked asymmetrically (everything points at
# start-here.md; start-here.md doesn't list everything back).
# Beyond the four hand-named HUB_STEMS, a page is a hub whenever *many* others
# name it in related: — a glossary/concept authority cited by dozens of pages
# (e.g. heading-status-vocabulary, 194 inbound) should not list them all back.
# Measured 2026-07-26 (#75): 86% of non-reciprocal edges point at a
# >=RECIPROCITY_HUB_MIN-inbound page and are asymmetric BY DESIGN; the residue —
# an edge to a low-inbound *peer* — is the real "someone forgot the back-link"
# signal. So hub-ness is degree-based here (self-maintaining, not a hand-list),
# and the reciprocity report covers only non-hub edges. The dangling-target HARD
# check below is unaffected — it fires on every unresolvable target regardless.
RECIPROCITY_HUB_MIN = 10
related_inbound: Counter = Counter(
    tgt
    for _s, (tgts, _l) in related_map.items()
    for tgt in tgts
    if tgt != _s and tgt in stems
)
related_dangling: list[dict] = []
related_asymmetric: list[dict] = []
related_edges_checked = 0
for src, (targets, src_line) in related_map.items():
    for tgt in targets:
        if tgt in HUB_STEMS or tgt.startswith("_") or tgt == src:
            continue
        if tgt not in stems:
            related_dangling.append({"file": f"{src}", "line": src_line, "target": tgt})
            continue
        if related_inbound[tgt] >= RECIPROCITY_HUB_MIN:
            continue  # degree-hub: asymmetric-by-design, not a missing back-link
        related_edges_checked += 1
        back_targets = related_map.get(tgt, ([], 0))[0]
        if src not in back_targets:
            related_asymmetric.append({"file": src, "line": src_line, "target": tgt})

# D2 (HARD): a `related:` target that resolves to no page is a dead edge —
# graduated from report-only to a hard check once the backlog hit 0 (same
# path the orphan check took in D1). Non-reciprocal edges stay advisory, and
# now cover only non-hub targets (degree-based, see RECIPROCITY_HUB_MIN above) —
# the hub-and-spoke bulk is asymmetric by design, so what remains is the small
# peer-to-peer residue worth a look — see the report-only block).
related_dangling_hard = [
    f"{d['file']}:{d['line']} -> related: [{d['target']}]" for d in related_dangling
]

# D4 (HARD): every `status: superseded` page must carry `superseded_by:` (≥1
# target that resolves to a real page) AND a read-time tombstone callout, so
# a retired-package/decision page can't masquerade as live in the vault.
superseded_incomplete: list[str] = []
superseded_dangling: list[str] = []
for sp in superseded_pages:
    problems = []
    if not sp["targets"]:
        problems.append("missing `superseded_by:` target")
    if not sp["tombstone"]:
        problems.append("missing tombstone callout (`> [!…]` naming the supersession)")
    if problems:
        superseded_incomplete.append(
            f"{sp['file']}:{sp['line']} -> {'; '.join(problems)}"
        )
    superseded_dangling.extend(
        f"{sp['file']}:{sp['line']} -> superseded_by [{t}] (no such page)"
        for t in sp["targets"]
        if t not in stems
    )

# D7 (HARD): `owns:` topic uniqueness — one authoritative page per topic slug.
# Coverage (every topic HAS an owner) isn't gated: there's no enumerated topic
# universe to check against, so this enforces the half that's mechanical —
# no two pages may both claim the same slug.
owns_conflicts = [
    f"topic '{slug}' claimed by {len(pgs)} pages: {sorted(pgs)}"
    for slug, pgs in sorted(owns_map.items())
    if len(pgs) > 1
]

ok = True


def section(name: str, items: Sequence[object], limit: int = 15) -> None:
    global ok
    print(f"{name}: {len(items)}")
    if items:
        ok = False
        for x in items[:limit]:
            print(f"  - {x}")
        if len(items) > limit:
            print(f"  … +{len(items) - limit} more")


def info_section(name: str, items: Sequence[object], limit: int = 25) -> None:
    # same rendering as section() but never touches `ok` — for Phase A
    # checks that are diagnostic-only until the A4 bulk repair lands.
    print(f"{name}: {len(items)}")
    if items:
        for x in items[:limit]:
            print(f"  - {x}")
        if len(items) > limit:
            print(f"  … +{len(items) - limit} more")


# ---------------------------------------------------------------------------
# A2 — retired-terms tripwire. Obvious, easily-extended seed list: append a
# bare string here when a name is retired (crate/package rename, dropped
# API). Hyphen/underscore are treated as identifier characters (not word
# boundaries) so e.g. "ags5-db" doesn't false-positive inside the *live*
# crate name "laterite-ags5-db" — a plain `\bags5-db\b` would (verified:
# 108 "laterite-ags5-db" mentions in-vault, 0 of them matched below).
# ---------------------------------------------------------------------------
RETIRED_TERMS = [
    "quack-rs",
    "validate_ags",
    "certify_ags",
    "ags5-models",
    "ags5-db",
    "ags5-ags4",
]
_TERM_BOUNDARY = r"(?<![A-Za-z0-9_-])({})(?![A-Za-z0-9_-])"
RETIRED_PATTERNS = [
    (t, re.compile(_TERM_BOUNDARY.format(re.escape(t)))) for t in RETIRED_TERMS
]


# ---------------------------------------------------------------------------
# A9 — `ext:<repo-id>:<path>` external-repo citation + its allowlist. A
# repo-id not on this list is itself reported — an `ext:` ref can't
# silently launder a citation to somewhere unvetted the way an unchecked
# escape hatch would. Seeded 2026-07-09 with the 3 external repos this
# vault actually cites (design/dec-duckdb-extension.md's post-#177
# laterite-duckdb split; tools/python-ags4.md + insights/o8-...'s
# python-ags4 GitLab mirror; duckdb/extension-ci-tools, upstream DuckDB's
# own CI submodule). `ext:` refs are exempt from A1's on-disk existence
# check by construction — REPO_REF only matches the literal `repo:`
# prefix, so an `ext:` ref never enters that scan at all.
# ---------------------------------------------------------------------------
EXT_ALLOWLIST = {
    "niko86/laterite-duckdb",
    "ags-python-library",
    "duckdb/extension-ci-tools",
}
EXT_REF = re.compile(r"(?<![A-Za-z0-9_-])ext:([^\s`()|]+)")


def parse_ext_ref(raw: str) -> tuple[str, str | None]:
    """(repo_id, path_or_None) — repo_id is everything up to the first
    ':' (itself may contain '/', e.g. 'niko86/laterite-duckdb'); anything
    after is the path within that external repo, if given."""
    if ":" in raw:
        repo_id, path = raw.split(":", 1)
        return repo_id, path
    return raw, None


# ---------------------------------------------------------------------------
# A11 — `<!-- historical -->` / `<!-- retired: TERM -->` exemption for the
# A2 retired-terms tripwire. Deliberately line-scoped, not page-scoped: a
# marker only exempts retired-term matches on its OWN line, so annotating
# one genuinely-historical sentence can't accidentally silence a live
# claim elsewhere on the same page. The generic form exempts every
# retired term on that line (for lines mentioning more than one); the
# specific form exempts only the named TERM, and TERM must be a real
# RETIRED_TERMS entry — an exemption citing an untracked term is either a
# typo or dead weight, either way reported as malformed rather than
# silently accepted. A marker that starts `<!-- historical`/`<!-- retired`
# but never closes isn't recognised as a marker at all (fails safe: the
# line stays flagged, not silently exempted).
# ---------------------------------------------------------------------------
HISTORICAL_ATTEMPT = re.compile(r"<!--\s*(?:historical|retired)\b[^>]*-->")
HISTORICAL_GENERIC = re.compile(r"<!--\s*historical\s*-->")
HISTORICAL_SPECIFIC = re.compile(r"<!--\s*retired:\s*([A-Za-z0-9_-]+)\s*-->")


# ---------------------------------------------------------------------------
# A1/A3 — repo: dead-ref scan, with a grammar that gets the citation forms
# right BEFORE anything here can fail the build:
#   repo:path/file.rs:352            (line suffix)
#   repo:.../mod.rs::run_all         (symbol suffix)
#   repo:OBSERVATIONS.md#o-33        (anchor suffix)
#   repo:rust-packages/*/build.rs    (glob — "exists" if it matches ≥1 path)
#   repo:.../{python,node,cli}/      (brace alternation — same ≥1-match rule)
# CRITICAL: this scans the RAW page text (`txt`, not `strip_code(txt)`).
# ~36% of repo: refs are wrapped in backticks in this vault; stripping code
# spans first — the way the wikilink check above does — would silently
# skip exactly the refs written in the citation grammar's own recommended
# form (AGS-WIKI.md §1). That blind spot is the whole reason this check
# exists, so it can't inherit strip_code()'s behaviour.
# ---------------------------------------------------------------------------
def anchor_problem(raw: str, resolved: str) -> str | None:
    """Tier-3 symbol/line-anchor validation (report-only) — for a `repo:` ref
    whose FILE exists, check its `:NN`/`:NN-MM` line suffix is in range and its
    `::symbol` suffix actually appears in the file. Skips globs/dirs (no single
    file to check) and `#anchor` (markdown, not validated here). Deliberately
    lenient: a symbol only has to appear as a word somewhere in the file, so a
    rename is flagged but a moved-within-file symbol is not (refactor noise)."""
    fp = REPO_ROOT / resolved
    if not fp.is_file():
        return None
    r = raw
    while r and r[-1] in TRAILING_PUNCT:
        r = r[:-1]
    m = re.search(r"::([A-Za-z_][A-Za-z0-9_]*)$", r)
    if m:
        try:
            text = fp.read_text(encoding="utf-8", errors="replace")
        except OSError:
            return None
        if re.search(rf"\b{re.escape(m.group(1))}\b", text) is None:
            return f"symbol '{m.group(1)}' not found in {resolved}"
        return None
    m = re.search(r":(\d+)(?:-(\d+))?$", r)
    if m:
        try:
            n = sum(1 for _ in fp.open("rb"))
        except OSError:
            return None
        hi = int(m.group(2) or m.group(1))
        if hi > n:
            return f"line {hi} out of range (file has {n} lines): {resolved}"
    return None


def git_last_date(path: str) -> str | None:
    """`git log -1 --format=%cs` (committer date, YYYY-MM-DD) for a repo path,
    or None if untracked / not a file. Powers the stale-risk freshness check."""
    fp = REPO_ROOT / path
    if not fp.is_file():
        return None
    try:
        out = subprocess.run(
            ["git", "-C", str(REPO_ROOT), "log", "-1", "--format=%cs", "--", path],
            capture_output=True,
            text=True,
            check=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None
    return out.stdout.strip() or None


def callout_block(txt: str, pos: int) -> str:
    """The contiguous `>`-quoted Obsidian callout containing byte `pos` (the
    `[!stale-risk]` match), or "" if `pos` isn't on a callout line.

    The `as-of DATE` promise vouches only for citations *inside its own callout*,
    so the freshness scan must be scoped to this block — never the whole file.
    Scanning the file flooded the report: log.md carries one such callout (plus,
    ironically, this convention quoted verbatim in a `- notes:` line) alongside
    hundreds of unrelated `repo:` refs across its history, each spuriously
    "stale". A prose mention that isn't a real `> ` callout yields "" and is
    ignored."""
    ls = txt.rfind("\n", 0, pos) + 1  # start of the line the match sits on
    if not txt.startswith(">", ls):  # not a callout line → not a callout
        return ""
    end = ls
    while end < len(txt):
        nl = txt.find("\n", end)
        stop = nl if nl != -1 else len(txt)
        if not txt.startswith(">", end):
            break
        end = stop + 1 if nl != -1 else stop
    return txt[ls:end]


def is_placeholder(raw: str) -> bool:
    # AGS-WIKI.md's own citation-grammar examples use literal "..." /
    # "…" as fill-in-the-blank markers (§1's "repo symbol" example, the
    # §9 log.md grammar line) — content-based, not a per-file exemption,
    # so a real dead ref elsewhere with an actual ellipsis-free path (e.g.
    # the ags5_dictionary.json rename below) still gets reported.
    return "..." in raw or "…" in raw


def _git_tracked_files() -> list[str]:
    try:
        out = subprocess.run(
            ["git", "-C", str(REPO_ROOT), "ls-files"],
            capture_output=True,
            text=True,
            check=True,
        )
        return [ln for ln in out.stdout.splitlines() if ln]
    except (subprocess.CalledProcessError, FileNotFoundError):
        return []


_TRACKED = _git_tracked_files()
_BASENAME_INDEX: dict[str, list[str]] = {}
for _f in _TRACKED:
    _BASENAME_INDEX.setdefault(Path(_f).name, []).append(_f)


def categorize_dead_ref(path_str: str) -> tuple[str, str]:
    """Best-effort bucket for a dead ref, so the report-only run is
    triageable rather than just a wall of red. Never authoritative —
    a human still repoints in A4."""
    base = Path(path_str).name
    # the single highest-blast-radius known issue (plan §4 P1): the AGS5
    # dict was renamed in-place (ags4-core keeps ags_dictionary.json) AND
    # the *actual* ags5_dictionary.json moved to ags5/ with the rest of
    # the decoupled strand — flag it explicitly rather than let the
    # generic heuristics below guess at just one half of that.
    if base == "ags5_dictionary.json" and "laterite-ags4-core" in path_str:
        return (
            "dict-rename",
            "this dir now has ags_dictionary.json (AGS4 union); the "
            "AGS5 dict itself lives at "
            "ags5/rust-packages/laterite-ags5-db/data/ags5_dictionary.json",
        )
    # #177 decoupled the AGS5 strand into ags5/, same relative shape
    if (REPO_ROOT / "ags5" / path_str).exists():
        return ("ags5/ move", f"ags5/{path_str}")
    # exact basename lives elsewhere in the tracked tree (rename/relocate).
    # Generic basenames (lib.rs × 15, Cargo.toml × 21, …) need ranking, not
    # just "first 3 in git ls-files order" — sort by whole-path similarity
    # so e.g. dead `rust-packages/ags4-wasm/src/lib.rs` (pre-rename name)
    # surfaces the real match `rust-packages/laterite-ags4-wasm/src/lib.rs`
    # ahead of unrelated lib.rs files.
    candidates = [c for c in _BASENAME_INDEX.get(base, []) if c != path_str]
    if candidates:
        candidates.sort(
            key=lambda c: difflib.SequenceMatcher(None, path_str, c).ratio(),
            reverse=True,
        )
        shown = "; ".join(candidates[:3])
        if len(candidates) > 3:
            shown += f" (+{len(candidates) - 3} more)"
        return ("moved-not-deleted", shown)
    # near-miss basename in the same directory → likely typo, not a move
    parent = str(Path(path_str).parent)
    siblings = {Path(c).name for c in _TRACKED if str(Path(c).parent) == parent}
    close = difflib.get_close_matches(base, siblings, n=1, cutoff=0.75)
    if close:
        return ("typo?", f"{parent}/{close[0]}")
    return ("genuinely gone", "")


# ---------------------------------------------------------------------------
# A12 — `location:` frontmatter resolution. A `type: source` page's `location:`
# is a declared path to the artifact that page is the authority for, and until
# now NOTHING in .bootstrap/ read the field at all. So five source pages sat
# pointing at `ags-wiki/AGS4-*.pdf` files the public-repo flip had removed, and
# A1 — which resolves every `repo:` citation in this vault against disk, and is
# hard — saw none of them, because a `location:` is not a citation: A1's grammar
# keys on the `repo:` prefix (refs.py REPO_REF) and a bare declared path has no
# prefix to key on. The field makes a path claim either way, so it gets its own
# resolution pass (week-33 shelf-read).
#
# Three value forms, per templates/_template-source.md:
#   repo:<path>              A1 already resolves it — same raw text, same
#                            grammar — so it is skipped here and a dead one is
#                            reported once rather than twice.
#   <repo-relative path>     must exist on disk (file or directory).
#   <name> — not vendored; …  an explicit "this artifact is NOT in this repo"
#                            declaration (the AGS-published spec PDFs, #304).
#                            Resolution would be wrong for it, but the
#                            declaration is itself checkable — and checking it
#                            is what stops the marker being a way to silence a
#                            dead path: the named file must genuinely be absent
#                            from the tree.
#
# No file-level exemptions: unlike A1/A2 there is nothing to exempt, since the
# machine-maintained log.md/index.md carry no frontmatter `location:` (and no
# generated page has any reason to). An empty `location:` makes no claim and is
# not a finding here — whether the key must be present at all is B1's business.
# ---------------------------------------------------------------------------
LOCATION_FIELD = re.compile(r"^location:\s*(.*?)\s*$", re.M)
NOT_VENDORED = "not vendored"

dead_refs: list[dict] = []
bad_locations: list[dict] = []  # A12
location_claims = 0
location_repo_claims = 0
ref_occurrences = 0
retired_hits: list[dict] = []
retired_counts: Counter = Counter()
exempted_counts: Counter = Counter()
ext_refs: list[str] = []
bad_ext_refs: list[str] = []
malformed_markers: list[str] = []
anchor_issues: list[str] = []  # Tier-3: :line/::symbol suffix on a LIVE ref
stale_risk_hits: list[str] = []  # verified_against: a cited file moved since as-of

for p in md:
    txt = p.read_text(encoding="utf-8")  # RAW — see module docstring/A1 note
    rel = p.relative_to(WIKI).as_posix()

    for m in REPO_REF.finditer(txt):
        ref_occurrences += 1
        raw = m.group(1)
        if is_placeholder(raw):
            continue
        exists, used = resolve_ref(raw)
        if exists:
            ap = anchor_problem(raw, used)
            if ap:
                anchor_issues.append(
                    f"{rel}:{line_at(txt, m.start())} -> repo:{raw}  ({ap})"
                )
            continue
        cat, detail = categorize_dead_ref(used)
        ln = line_at(txt, m.start())
        dead_refs.append(
            {
                "file": rel,
                "line": ln,
                "raw": raw,
                "resolved": used,
                "category": cat,
                "detail": detail,
            }
        )

    # A12 — the frontmatter `location:` claim (see the block above). Offsets
    # into the frontmatter map back to the page by +3: frontmatter_block()
    # returns txt[3:…], the text after the opening `---`.
    _fm = frontmatter_block(txt)
    _lm = LOCATION_FIELD.search(_fm) if _fm else None
    if _lm and (loc := _lm.group(1).strip().strip("\"'")):
        location_claims += 1
        ln = line_at(txt, 3 + _lm.start())
        if loc.startswith("repo:"):
            location_repo_claims += 1  # A1 resolved it in the scan above
        elif NOT_VENDORED in loc:
            # the claim is absence, so absence is what gets checked
            named = loc.split()[0]
            if named in _BASENAME_INDEX:
                bad_locations.append(
                    {
                        "file": rel,
                        "line": ln,
                        "msg": f"location: {loc!r} says '{NOT_VENDORED}', but "
                        f"{_BASENAME_INDEX[named][0]} is tracked in this repo",
                    }
                )
        elif not path_exists(loc):
            cat, detail = categorize_dead_ref(loc)
            bad_locations.append(
                {
                    "file": rel,
                    "line": ln,
                    "msg": f"location: {loc!r} — no such path  [{cat}]"
                    + (f" ({detail})" if detail else ""),
                }
            )

    # verified_against / staleness (Tier-3): a `> [!stale-risk] … as-of DATE`
    # callout promises "these numbers were true as of DATE". If a repo: file
    # cited on the same page has a git commit date AFTER that as-of date, the
    # snapshot may be stale — report it (advisory: a code touch doesn't always
    # invalidate a benchmark, but it's the signal to re-check). Reuses the
    # existing convention rather than adding a second date field.
    for sm in re.finditer(r"\[!stale-risk\][^\n]*?as-of\s*(\d{4}-\d{2}-\d{2})", txt):
        asof = sm.group(1)
        block = callout_block(txt, sm.start())  # scope to THIS callout, not the file
        for rm in REPO_REF.finditer(block):
            rraw = rm.group(1)
            if is_placeholder(rraw):
                continue
            ok_ref, rused = resolve_ref(rraw)
            if not ok_ref:
                continue
            d = git_last_date(rused)
            if d and d > asof:
                stale_risk_hits.append(
                    f"{rel} (as-of {asof}) -> repo:{rused} changed {d} "
                    f"(cited file moved after the snapshot)"
                )

    # A9 — ext: allowlist check (same trailing-punctuation tolerance as
    # resolve_ref, since ext: refs land in quoted frontmatter too)
    for m in EXT_REF.finditer(txt):
        raw = m.group(1)
        if is_placeholder(raw):
            continue
        clean = raw
        while clean and clean[-1] in TRAILING_PUNCT:
            clean = clean[:-1]
        repo_id, _ext_path = parse_ext_ref(clean)
        ln = line_at(txt, m.start())
        if repo_id in EXT_ALLOWLIST:
            ext_refs.append(f"{rel}:{ln} -> ext:{raw}")
        else:
            bad_ext_refs.append(
                f"{rel}:{ln} -> ext:{raw}  (repo-id '{repo_id}' not in EXT_ALLOWLIST)"
            )

    # A11 — build this page's line -> exempted-terms map before scanning
    # for retired terms, and flag any marker that LOOKS like an exemption
    # attempt but isn't well-formed.
    line_exemptions: dict[int, object] = {}  # int -> "ALL" | set[str]
    for lm in HISTORICAL_ATTEMPT.finditer(txt):
        ln = line_at(txt, lm.start())
        seg = lm.group(0)
        smatch = HISTORICAL_SPECIFIC.fullmatch(seg)
        if HISTORICAL_GENERIC.fullmatch(seg):
            line_exemptions[ln] = "ALL"
        elif smatch and smatch.group(1) in RETIRED_TERMS:
            existing = line_exemptions.get(ln)
            if existing == "ALL":
                pass
            elif isinstance(existing, set):
                existing.add(smatch.group(1))
            else:
                line_exemptions[ln] = {smatch.group(1)}
        else:
            bad_term = smatch.group(1) if smatch else None
            reason = (
                f"'{bad_term}' is not in RETIRED_TERMS"
                if bad_term
                else "not `historical` or `retired: <term>`"
            )
            malformed_markers.append(f"{rel}:{ln} -> {seg!r} ({reason})")

    for term, pat in RETIRED_PATTERNS:
        for m in pat.finditer(txt):
            ln = line_at(txt, m.start())
            exemption = line_exemptions.get(ln)
            if exemption == "ALL" or (isinstance(exemption, set) and term in exemption):
                exempted_counts[term] += 1
                continue
            start, end = max(0, m.start() - 30), min(len(txt), m.end() + 30)
            snippet = txt[start:end].replace("\n", " ")
            retired_counts[term] += 1
            retired_hits.append(
                {"file": rel, "line": ln, "term": term, "snippet": snippet}
            )

# B3 — fold CLAUDE.md into the SAME A1 (repo: dead-ref) + A2 (retired-terms)
# raw-text scans (per the plan's B3: "extend A1/A2 scope to CLAUDE.md" — the
# repo's own architecture doc cites paths and names retired terms too, and
# rots the same way a wiki page does; #9 in the plan's audit). No A9/A11
# here — `ext:` and `<!-- historical -->` are ags-wiki-only citation-grammar
# conventions CLAUDE.md doesn't use, so a CLAUDE.md retired-term hit is
# always reported, never exempted. NOTE (worth knowing when reading the A1
# count below): CLAUDE.md cites repo paths as bare backtick-wrapped strings,
# NOT the `repo:` grammar (verified 2026-07-09) — so this fold is a correct,
# live scan that currently finds 0 A1 candidates by construction, not proof
# CLAUDE.md's citations are healthy; it only starts finding something the
# day CLAUDE.md adopts (or drifts into) the `repo:` prefix.
if CLAUDE_MD.exists():
    _claude_txt = CLAUDE_MD.read_text(encoding="utf-8")
    _claude_label = "CLAUDE.md"
    for m in REPO_REF.finditer(_claude_txt):
        ref_occurrences += 1
        raw = m.group(1)
        if is_placeholder(raw):
            continue
        exists, used = resolve_ref(raw)
        if exists:
            continue
        cat, detail = categorize_dead_ref(used)
        dead_refs.append(
            {
                "file": _claude_label,
                "line": line_at(_claude_txt, m.start()),
                "raw": raw,
                "resolved": used,
                "category": cat,
                "detail": detail,
            }
        )
    for term, pat in RETIRED_PATTERNS:
        for m in pat.finditer(_claude_txt):
            ln = line_at(_claude_txt, m.start())
            start, end = max(0, m.start() - 30), min(len(_claude_txt), m.end() + 30)
            snippet = _claude_txt[start:end].replace("\n", " ")
            retired_counts[term] += 1
            retired_hits.append(
                {"file": _claude_label, "line": ln, "term": term, "snippet": snippet}
            )

dead_refs.sort(key=lambda d: (d["category"], d["file"], d["line"]))
dead_cat_counts = Counter(d["category"] for d in dead_refs)
dead_unique_paths = Counter(d["resolved"] for d in dead_refs)


# C5: crate-map.md's graph must name every workspace crate (whole-vault hard
# check, safe at baseline 0 — the three then-missing crates were added when this
# landed). Extra nodes (the dormant ags5 crates, the external duckdb ext, the
# `lat` binary alias) are fine; the check is completeness, not exclusivity.
missing_crates: list[str] = []
if CRATE_MAP.exists() and WORKSPACE_CRATES:
    _cgraph = "\n".join(
        re.findall(r"```mermaid\n(.*?)```", CRATE_MAP.read_text(), re.DOTALL)
    )
    missing_crates = [
        f"crate-map.md: workspace crate '{c}' is absent from the graph"
        for c in sorted(WORKSPACE_CRATES)
        if c not in _cgraph
    ]

# C6: every workspace crate has exactly ONE tool page rooted at its directory.
#
# Strictly stronger than C5 above, which asks only that the crate-map GRAPH names
# every crate. C5 stayed green when the 25th member landed, because a node
# labelled `laterite` was already in the graph — meaning the PyPI wheel. A graph
# label is prose; a `repo_refs.root` is a path, and a path cannot be satisfied by
# a coincidence of naming.
#
# It catches two failures a label check cannot:
#   * a crate with no page at all (what `rust-packages/laterite` was — published,
#     on its own version line, and undocumented, while a reader looking up
#     "laterite" landed confidently on the wheel's page instead)
#   * two pages claiming the same crate, which makes "the page for X" ambiguous
#     and lets the two drift apart unnoticed
_ROOTED = re.compile(r'^\s+root:\s*"repo:rust-packages/([A-Za-z0-9_-]+)/?"\s*$', re.M)
crate_page_problems: list[str] = []
if WORKSPACE_CRATES:
    _claims: dict[str, list[str]] = {}
    for _p in sorted((WIKI / "tools").glob("*.md")):
        _parts = _p.read_text(encoding="utf-8").split("---", 2)
        if len(_parts) < 3:
            continue
        for _m in _ROOTED.finditer(_parts[1]):
            _claims.setdefault(_m.group(1), []).append(_p.stem)
    # WORKSPACE_CRATES is the `members` list, i.e. DIRECTORY names — the same
    # thing `repo_refs.root` points at, so they compare directly.
    for _dir in sorted(WORKSPACE_CRATES):
        _pages = _claims.get(_dir, [])
        if not _pages:
            crate_page_problems.append(
                f"workspace crate '{_dir}' has no tool page rooted at "
                f"repo:rust-packages/{_dir}"
            )
        elif len(_pages) > 1:
            crate_page_problems.append(
                f"workspace crate '{_dir}' is claimed by {len(_pages)} pages: "
                f"{', '.join(sorted(_pages))}"
            )

# C6b: crate-map.md's spelled-out crate count matches the manifest.
#
# It said "twenty-four crates" against 25 members, in two places, while citing
# the very file that lists them. The count is not generated — a numeral spliced
# into hand-written prose reads worse than the prose does, and this page is the
# hand-curated keystone. Checking it costs nothing and keeps the voice.
#
# Only NUMBER words are considered, so "the QA crates" or "these crates" cannot
# trip it. A page that states no count at all is fine; the check is agreement,
# not obligation.
_NUMWORD = {
    "twenty": 20,
    "twenty-one": 21,
    "twenty-two": 22,
    "twenty-three": 23,
    "twenty-four": 24,
    "twenty-five": 25,
    "twenty-six": 26,
    "twenty-seven": 27,
    "twenty-eight": 28,
    "twenty-nine": 29,
    "thirty": 30,
    "thirty-one": 31,
    "thirty-two": 32,
    "thirty-three": 33,
    "thirty-four": 34,
    "thirty-five": 35,
}
bad_crate_count: list[str] = []
if CRATE_MAP.exists() and WORKSPACE_CRATES:
    _true = len(WORKSPACE_CRATES)
    _txt = CRATE_MAP.read_text(encoding="utf-8")
    for _m in re.finditer(r"\b([a-z]+(?:-[a-z]+)?|\d+) crates\b", _txt):
        _tok = _m.group(1)
        _n = int(_tok) if _tok.isdigit() else _NUMWORD.get(_tok)
        if _n is not None and _n != _true:
            _line = _txt[: _m.start()].count("\n") + 1
            bad_crate_count.append(
                f"crate-map.md:{_line}: says '{_tok} crates' but "
                f"repo:rust-packages/Cargo.toml lists {_true} members"
            )

# C5 long-term (#10): every crate-map edge connects two really-coupled crates.
CRATE_DEPS = _crate_deps()
bad_crate_edges: list[str] = []
if CRATE_DEPS:
    _cnames = set(CRATE_DEPS)
    for _a, _b in _crate_map_edges():
        if (
            _a in _cnames
            and _b in _cnames
            and _b not in CRATE_DEPS[_a]
            and _a not in CRATE_DEPS[_b]
        ):
            bad_crate_edges.append(
                f"crate-map.md: edge {_a}-->{_b} — neither crate depends on the "
                f"other (phantom edge; a real dependency was dropped?)"
            )

print(f"pages scanned: {len(md)}")
section("broken wikilinks", broken)  # hard
section("unbalanced mermaid fences", unbalanced)  # hard
section(
    "orphan pages (0 inbound wikilinks; index.md/log.md excluded)", orphans_real
)  # hard (D1)
section("crate-map graph missing a workspace crate", missing_crates)  # hard (C5)
section(
    "workspace crate with no tool page, or claimed by two", crate_page_problems
)  # hard (C6)
section(
    "crate-map states a crate count the manifest contradicts", bad_crate_count
)  # hard (C6b)
section(
    "crate-map edge names a non-dependency (phantom edge)", bad_crate_edges
)  # hard (C5 long-term)
section("erDiagram names an undocumented group code", bad_erd)  # hard (C5)
section("related: dangling targets (no such page)", related_dangling_hard)  # hard (D2)
section(
    "superseded page missing superseded_by/tombstone", superseded_incomplete
)  # hard (D4)
section(
    "superseded_by names a page that doesn't exist", superseded_dangling
)  # hard (D4)
section("owns: topic claimed by more than one page", owns_conflicts)  # hard (D7)
section("reliquary register out of sync with the tree", _reliquary_violations())  # hard
# Scaffold invariant is bootstrap-only: once the Ingest campaign runs,
# content pages legitimately advance stub→drafted→reviewed. Report the
# distribution informationally; do NOT fail the lint on it.
print(
    f"\nbootstrap content pages still status:stub: "
    f"{len(not_stub)} advanced past stub (informational, not a failure)"
)

if SINCE_REF:
    print(
        f"\n--- Phase A (--since {SINCE_REF}: A1/A2 are diff-scoped — a "
        f"finding only fails the run if it's on a line added/modified "
        f"since {SINCE_REF}; everything else below is grandfathered and "
        f"report-only, same as a plain run) ---"
    )
else:
    print(
        "\n--- Phase A (whole-vault: A1 dead refs + A2 retired-term hits are "
        "HARD — see the gate at the end of Phase A; the per-category "
        "breakdowns below are diagnostic detail) ---"
    )
print(
    f"\nrepo: refs scanned (raw text, {ref_occurrences} occurrences, "
    f"{len(dead_unique_paths)} unique dead paths):"
)
print(f"dead repo: refs: {len(dead_refs)}")
if dead_refs:
    log_n = sum(1 for d in dead_refs if d["file"] == "log.md")
    print(
        f"  {log_n} of those are in log.md (append-only history — this "
        f"repo's convention is to leave historical log entries accurate-"
        f"as-of-when-written, not retro-repoint them; A4 bulk repair "
        f"should target the other {len(dead_refs) - log_n} in live "
        f"content pages first)"
    )
    print("  category breakdown:")
    for cat, n in dead_cat_counts.most_common():
        print(f"    {cat}: {n}")
    print("  top offending unique paths (blast radius):")
    for path_val, n in dead_unique_paths.most_common(10):
        if n > 1:
            print(f"    {n}x  {path_val}")
    # per-category, not one flat cut — a flat top-N would bury the smaller
    # "genuinely gone"/"typo?" buckets under the 191x dict-rename repeat
    for cat, _ in dead_cat_counts.most_common():
        cat_findings = [
            f"{d['file']}:{d['line']} -> repo:{d['raw']}"
            + (f"  ({d['detail']})" if d["detail"] else "")
            for d in dead_refs
            if d["category"] == cat
        ]
        info_section(f"  [{cat}] findings", cat_findings, limit=A_LIMIT)

print(
    f"\n`location:` claims scanned (A12): {location_claims} "
    f"({location_repo_claims} of them `repo:` — resolved by A1 above), "
    f"{len(bad_locations)} unresolved"
)

print(
    f"\nretired-term hits: {len(retired_hits)} (seed list: {', '.join(RETIRED_TERMS)})"
)
if retired_hits:
    # log.md (append-only history) + index.md (generated Retired/Superseded
    # catalog naming tombstone pages) are ratchet-exempt — see
    # RATCHET_EXEMPT_FILES; count them out of "live content".
    gen_n = sum(1 for h in retired_hits if h["file"] in {"log.md", "index.md"})
    print(
        f"  {gen_n} of those are in machine-maintained log.md/index.md "
        f"(ratchet-exempt); {len(retired_hits) - gen_n} in live content"
    )
    print("  per-term counts:")
    for term, n in retired_counts.most_common():
        print(f"    {term}: {n}")
    info_section(
        "  findings",
        [
            f'{h["file"]}:{h["line"]} -> "{h["term"]}" … {h["snippet"]}'
            for h in retired_hits
        ],
        limit=A_LIMIT,
    )
total_exempted = sum(exempted_counts.values())
if total_exempted:
    print(
        f"  ({total_exempted} additional hit(s) exempted via <!-- historical -->/"
        f"<!-- retired: TERM --> — see A11 below)"
    )

# A9 — ext: allowlist. Valid refs are counted but not printed one-by-one
# (they're expected/fine); only allowlist misses are worth a look.
print(
    f"\next: refs (A9): {len(ext_refs)} valid (repo-id on the allowlist: "
    f"{', '.join(sorted(EXT_ALLOWLIST))})"
)
info_section("  NOT on the allowlist", bad_ext_refs, limit=A_LIMIT)

# A11 — historical/retired exemption markers. Report how much of A2's
# noise they're absorbing, and any marker that doesn't parse.
print(
    f"\n<!-- historical --> / <!-- retired: TERM --> markers (A11): "
    f"{total_exempted} retired-term hit(s) exempted, "
    f"{len(malformed_markers)} malformed marker(s)"
)
info_section("  malformed markers", malformed_markers, limit=A_LIMIT)

# Tier-3 (wiki-reliability plan deferred list): symbol/line-anchor validation +
# verified_against/staleness — both report-only (refactor noise / advisory), like
# A1/A2 before the ratchet. A `--since` run does NOT ratchet these yet.
print(
    f"\nrepo: anchor issues (Tier-3, :line out of range / ::symbol not found "
    f"on a LIVE ref): {len(anchor_issues)}"
)
info_section("  findings", anchor_issues, limit=A_LIMIT)
_stale_uniq = sorted(set(stale_risk_hits))
print(
    f"\nstale-risk freshness (Tier-3, a `[!stale-risk] as-of DATE` page cites a "
    f"file changed after that date): {len(_stale_uniq)}"
)
info_section("  findings", _stale_uniq, limit=A_LIMIT)

# A5 — the ratchet itself: of the A1/A2 findings collected above, which
# ones sit on a line this diff actually added/modified? Two files are exempt
# from BOTH here, for the same underlying reason — they're machine-maintained,
# not hand-authored prose making a live claim:
#   • log.md (append-only history) — a log entry that *describes* retiring a
#     term necessarily names it, so without this a wiki session literally
#     can't log its own A2/A11 work without tripping the ratchet on its own
#     append. Every log entry is retrospective by construction.
#   • index.md (regenerated by reindex.py, never hand-edited — §8) — the
#     Retired/Superseded catalog section (D4) names each tombstone page by its
#     stem, and those stems ARE retired package names (`ags5-db` etc.). A
#     generated catalog row pointing at a retired-package tombstone page is the
#     catalog doing its job, not stale-live rot; and A11 `<!-- historical -->`
#     markers can't help (they'd be wiped on the next regenerate).
# Both get a blanket file-level exemption rather than needing per-line markers.
RATCHET_EXEMPT_FILES = {"log.md", "index.md"}
if SINCE_REF:
    ratchet_dead = [
        d
        for d in dead_refs
        if d["file"] not in RATCHET_EXEMPT_FILES
        and in_added_range(d["file"], d["line"])
    ]
    ratchet_retired = [
        h
        for h in retired_hits
        if h["file"] not in RATCHET_EXEMPT_FILES
        and in_added_range(h["file"], h["line"])
    ]
    print(
        f"\n--since {SINCE_REF}: ratchet result (NEW findings only — "
        f"everything above is grandfathered)"
    )
    section(
        "  NEW dead repo: refs (introduced by this diff)",
        [
            f"{d['file']}:{d['line']} -> repo:{d['raw']}"
            + (f"  ({d['detail']})" if d["detail"] else "")
            for d in ratchet_dead
        ],
        limit=A_LIMIT,
    )
    section(
        "  NEW retired-term hits (introduced by this diff)",
        [
            f'{h["file"]}:{h["line"]} -> "{h["term"]}" … {h["snippet"]}'
            for h in ratchet_retired
        ],
        limit=A_LIMIT,
    )
    section(
        "  NEW unresolvable `location:` fields (introduced by this diff)",
        [
            f"{d['file']}:{d['line']} -> {d['msg']}"
            for d in bad_locations
            if in_added_range(d["file"], d["line"])
        ],
        limit=A_LIMIT,
    )
    # Tier-3 (#23) net-citation-removal — report-only (never touches `ok`):
    # citations this diff deleted without re-adding, a de-grounding signal.
    info_section(
        "  repo: citations removed by this diff (not re-added — "
        "verify they were repointed, not just dropped)",
        net_removed_citations(SINCE_REF),
        limit=A_LIMIT,
    )
else:
    # A4 graduation (#75, 2026-07): the grandfathered backlog is cleared, so a
    # whole-vault run (the nightly's ENFORCING half — no `--since`) now treats
    # A1/A2 as HARD checks: any live-content dead `repo:` ref or un-exempted
    # retired-term hit fails the run, exactly like D1/D2/D4/D7 above. That is
    # the point of clearing the backlog. Exemptions are unchanged — the
    # machine-maintained log.md/index.md (RATCHET_EXEMPT_FILES) never count,
    # and A2's `<!-- historical -->`/`<!-- retired: TERM -->` markers already
    # filter retired_hits before collection. The per-PR `--since` run stays
    # advisory (grandfather semantics), so a contributor is never blocked by a
    # page they never touched.
    section(
        "\nA1 dead repo: refs — live content (HARD; log.md/index.md exempt)",
        [
            f"{d['file']}:{d['line']} -> repo:{d['raw']}"
            + (f"  ({d['detail']})" if d["detail"] else "")
            for d in dead_refs
            if d["file"] not in RATCHET_EXEMPT_FILES
        ],
        limit=A_LIMIT,
    )
    section(
        "A2 retired-term hits — live content (HARD; log.md/index.md exempt)",
        [
            f'{h["file"]}:{h["line"]} -> "{h["term"]}" … {h["snippet"]}'
            for h in retired_hits
            if h["file"] not in RATCHET_EXEMPT_FILES
        ],
        limit=A_LIMIT,
    )
    # A12 is HARD from the day it lands, not report-only-then-graduated like
    # A1/A2 — same rule, met differently: the backlog it had to clear was one
    # page (sources/repo-authorities/ags-library-xlsx.md, a pre-flip `reports/`
    # path), repointed in the change that added this check, so it starts at 0.
    section(
        "A12 `location:` fields that don't resolve (HARD)",
        [f"{d['file']}:{d['line']} -> {d['msg']}" for d in bad_locations],
        limit=A_LIMIT,
    )

# ---------------------------------------------------------------------------
# Phase B: frontmatter-schema + status-vocab (B1), related: reciprocity (B2), and the
# orphan-check fix (D1) — ALL report-only, same cadence as Phase A: print
# findings, never touch `ok`. wiki-lint gates every PR, so nothing here may
# newly redden one until a follow-up unit repairs the backlog and flips it
# (mirrors how A1/A2 were introduced report-only first, then earmarked for
# A5's ratchet).
# ---------------------------------------------------------------------------
print("\n--- Phase B (report-only — does not affect exit code) ---")

print(f"\nfrontmatter: missing `type:` field: {len(fm_no_type)}")
info_section("  findings", fm_no_type, limit=A_LIMIT)
print(
    f"\nfrontmatter: unrecognised `type:` value (no matching template): {len(fm_unknown_type)}"
)
info_section("  findings", fm_unknown_type, limit=A_LIMIT)
print(
    f"\nfrontmatter: missing required key(s) per templates/_template-<type>.md: "
    f"{len(fm_missing)}"
)
info_section(
    "  findings",
    [
        f"{d['file']}:{d['line']} (type={d['type']}) missing {d['missing']}"
        for d in fm_missing
    ],
    limit=A_LIMIT,
)

print(
    f"\nstatus: value outside the documented vocab for its `type:`: {len(status_bad)}"
)
info_section(
    "  findings",
    [
        f"{d['file']}:{d['line']} (type={d['type']}) status={d['status']!r} "
        f"not in {sorted(STATUS_VOCAB[d['type']])}"
        for d in status_bad
    ],
    limit=A_LIMIT,
)

# related: dangling targets is now a HARD check (D2), reported up top with the
# other hard checks — not here. Only the advisory non-reciprocity survives in
# the report-only block.
_related_pct = (
    100 * len(related_asymmetric) / related_edges_checked
    if related_edges_checked
    else 0
)
print(
    f"\nrelated: non-reciprocal edges (non-hub targets only, <{RECIPROCITY_HUB_MIN} "
    f"inbound): {len(related_asymmetric)} of {related_edges_checked} checked "
    f"({_related_pct:.0f}%)"
)
info_section(
    "  findings (A relates to B, B doesn't relate back to A; hub targets exempt)",
    [f"{d['file']}:{d['line']} -> {d['target']}" for d in related_asymmetric],
    limit=A_LIMIT,
)

print(
    "\ngenerator faithfulness (B2): ags-wiki/index.md == render() is "
    "enforced by `reindex.py --check`, not by lint.py — the wiki-lint "
    "workflow runs it (and the gen_*.py --check gates) as separate steps."
)

if SINCE_REF:
    ratchet_fm = [d for d in fm_missing if in_added_range(d["file"], d["line"])]
    ratchet_status = [d for d in status_bad if in_added_range(d["file"], d["line"])]
    ratchet_rel_asym = [
        d for d in related_asymmetric if in_added_range(d["file"], d["line"])
    ]
    print(
        f"\n--since {SINCE_REF}: Phase B ratchet preview (NEW findings "
        f"only, informational — the frontmatter/status/non-reciprocity "
        f"checks stay report-only; orphans (D1), related-dangling (D2), "
        f"superseded-tombstone (D4) and owns-uniqueness (D7) are HARD "
        f"whole-vault checks above, so none are ratchet-scoped)"
    )
    info_section(
        "  NEW frontmatter-missing-key findings",
        [
            f"{d['file']}:{d['line']} (type={d['type']}) missing {d['missing']}"
            for d in ratchet_fm
        ],
        limit=A_LIMIT,
    )
    info_section(
        "  NEW status-vocab findings",
        [
            f"{d['file']}:{d['line']} (type={d['type']}) status={d['status']!r}"
            for d in ratchet_status
        ],
        limit=A_LIMIT,
    )
    info_section(
        "  NEW related: non-reciprocal findings",
        [f"{d['file']}:{d['line']} -> {d['target']}" for d in ratchet_rel_asym],
        limit=A_LIMIT,
    )

print("\nLINT", "CLEAN" if ok else "FAIL")
sys.exit(0 if ok else 1)
