#!/usr/bin/env python3
"""Fail when a doc references a file that isn't there.

Cheap, stdlib-only, and it exists because a session-by-session read cannot keep
up. A one-off audit on 2026-08-03 found four dead references in seconds, two of
them on PUBLISHED crates.io pages where a version's README is frozen forever.
The audit should not have been a session; it should have been this.

TWO RESOLUTION RULES, and the difference is the whole point.

  * A doc in the repo is read from a checkout, so a reference resolves if it
    exists relative to the doc, or to the repo root.

  * A PUBLISHED crate's README is read on crates.io, where the only files that
    exist are the ones inside that crate's package. `[x](../../OBSERVATIONS.md)`
    and `[x](OBSERVATIONS.md)` both resolve fine in a checkout and both 404 for
    the person deciding whether to `cargo add` your crate.

That second rule is what the one-off audit initially missed: a first pass that
fell back to the repo root reported the validator's README as clean, while the
live 0.9.0 page carried three dead `OBSERVATIONS.md` links and two dead
`README-cli` links. Published READMEs are therefore checked STRICTLY — no
repo-root fallback — and links must be absolute URLs to escape the package.

Not checked here, deliberately: URL liveness (network, flaky, and the docs job's
mkdocs strict build already link-gates the site), and anchors.

AND ONE MORE, WHICH THIS TOOL NOW SAYS OUT LOUD. A backticked token counts as a
path only if it contains a `/`, or `read()` and `pandas` would be dead
references. The cost is that a bare filename in prose — `compat.py` — is a
citation nothing here can resolve, and for months nothing said so: the gate went
green having never looked, and engaged only once that citation grew a slash
(#460). So every run now reports how many tokens the rule dropped, pass or fail.
The rule is unchanged; only its silence is. Whether to widen recall to suffixed
bare filenames is a separate judgement, to be made on what that report shows.
Gated by tests/test_check_doc_refs.py.

  check_doc_refs.py            report dead references
  check_doc_refs.py --check    same, but exit 1 if any (the CI gate)
  check_doc_refs.py --skipped  also list the tokens the `/` rule dropped

Run: `uv run --no-project python tools/check_doc_refs.py --check` (stdlib only).
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import tomllib
from pathlib import Path
from typing import NamedTuple

ROOT = Path(__file__).resolve().parent.parent

#: Docs read from a checkout: resolve doc-relative, then repo-relative.
REPO_DOCS = [
    "README.md",
    "CLAUDE.md",
    "CONTRIBUTING.md",
    "RELEASING.md",
    "COMPAT.md",
    "tools/README.md",
]

#: A backticked path-shaped token, and a Markdown link target.
PATH_RE = re.compile(
    r"`([A-Za-z0-9_./-]+\.(?:py|sh|rs|toml|json|ts|mjs|yml|yaml|md|ps1))`"
)
LINK_RE = re.compile(r"\[[^\]]*\]\(([^)#][^)]*)\)")

#: Prefixes that are never a local file.
EXTERNAL = ("http://", "https://", "mailto:", "#", "<")


def _gitignored(paths: list[str]) -> set[str]:
    """The subset of `paths` git is configured to ignore.

    A doc may legitimately name a BUILD ARTIFACT — `RELEASING.md` explains that
    `web/src/wasm/package.json` is gitignored and regenerated by wasm-pack, which
    is exactly the kind of thing a release runbook must mention. Such a path is
    present or absent depending on whether the reader has run a build, so
    treating "absent" as dead makes this gate's verdict depend on local build
    state: green on a machine that has built wasm, red in CI which has not. That
    is the same non-determinism `web/vitest.config.ts` documents for coverage,
    and it is how this check first went red on its own PR.

    Ignored == generated == not this gate's business.
    """
    if not paths:
        return set()
    r = subprocess.run(
        ["git", "check-ignore", "--stdin"],
        input="\n".join(paths),
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    return {line.strip() for line in r.stdout.splitlines() if line.strip()}


def _targets(text: str) -> tuple[set[str], set[str]]:
    """A doc's references, split into (resolvable, dropped for want of a `/`).

    The second half is the point. Both are produced in one walk of the same
    matches so they cannot drift apart into a filter whose complement nobody
    computes — which is exactly how the blind spot lasted.

    Markdown links are unfiltered, because a link target is path-shaped by
    definition; nothing is ever dropped on that side.
    """
    checked: set[str] = set()
    skipped: set[str] = set()
    for m in PATH_RE.findall(text):
        (checked if "/" in m else skipped).add(m)
    checked |= set(LINK_RE.findall(text))
    resolvable = {
        t.split("#")[0].strip() for t in checked if t and not t.startswith(EXTERNAL)
    }
    return resolvable, skipped


def _published_crates() -> list[Path]:
    """Crates without `publish = false` — the ones whose README becomes a public,
    permanent page the moment a version goes up."""
    out = []
    for man in sorted((ROOT / "rust-packages").glob("*/Cargo.toml")):
        pkg = tomllib.load(man.open("rb")).get("package", {})
        if pkg.get("publish") is not False:
            out.append(man.parent)
    return out


class Scan(NamedTuple):
    """What the gate found, beside what it never looked at.

    Two fields rather than a bare list of problems, so a caller cannot report
    the verdict without having been handed the scope it was reached under.
    """

    problems: list[str]
    #: (doc, token) for every backticked reference the `/` rule dropped.
    skipped: list[tuple[str, str]]


def scan() -> Scan:
    problems: list[str] = []
    skipped: list[tuple[str, str]] = []

    pending: list[tuple[str, str]] = []
    for rel in REPO_DOCS:
        doc = ROOT / rel
        if not doc.exists():
            continue
        resolvable, bare = _targets(doc.read_text(errors="replace"))
        skipped += [(rel, t) for t in sorted(bare)]
        for t in sorted(resolvable):
            if (doc.parent / t).exists() or (ROOT / t).exists():
                continue
            pending.append((rel, t))
    ignored = _gitignored([t for _, t in pending])
    problems.extend(
        f"{rel}: `{t}` does not exist" for rel, t in pending if t not in ignored
    )

    for crate in _published_crates():
        rd = crate / "README.md"
        if not rd.exists():
            problems.append(
                f"{crate.name}: PUBLISHED with no README — its crates.io page will be bare"
            )
            continue
        resolvable, bare = _targets(rd.read_text(errors="replace"))
        skipped += [(f"{crate.name}/README.md", t) for t in sorted(bare)]
        missing = [t for t in sorted(resolvable) if not (crate / t).exists()]
        # Strict: only what ships inside the package exists on crates.io.
        ignored = _gitignored(missing)
        problems.extend(
            f"{crate.name}/README.md: `{t}` is not in the published package — "
            f"dead on crates.io (use an absolute github.com URL)"
            for t in missing
            if t not in ignored
        )

    return Scan(problems, skipped)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check", action="store_true", help="exit 1 if any reference is dead"
    )
    ap.add_argument(
        "--skipped",
        action="store_true",
        help="list the backticked tokens dropped for want of a `/`",
    )
    args = ap.parse_args()

    result = scan()
    for p in result.problems:
        print(f"  {p}")
    if args.skipped:
        for doc, t in result.skipped:
            print(f"  skipped {doc}: `{t}`")

    # Unconditional, and above the verdict: a count printed only when it is
    # non-zero, or only on the failure path, is a scope the reader of a green
    # run still never sees.
    docs = len({doc for doc, _ in result.skipped})
    hint = "" if args.skipped or not result.skipped else " (--skipped lists them)"
    print(
        f"check_doc_refs: skipped {len(result.skipped)} slash-free backticked "
        f"token(s) in {docs} doc(s); a bare filename is not path-shaped, so "
        f"nothing resolved it{hint}"
    )

    if not result.problems:
        print("check_doc_refs: every referenced path exists")
        return
    print(f"check_doc_refs: {len(result.problems)} dead reference(s)")
    if args.check:
        sys.exit(1)


if __name__ == "__main__":
    main()
