#!/usr/bin/env bash
#
# Run python-ags4's own test suite against laterite.compat (the
# Rust-backed drop-in). Stage 1 of the python-ags4 parity arc — the
# pytest output is the baseline failure-list Stage 2 closes.
#
# python-ags4's wheel doesn't ship its tests/, so we clone the GitLab
# repo into a sibling directory and shim `python_ags4` to point at
# `laterite.compat` via a generated conftest.py that pytest discovers
# at test-collection time.
#
# Usage:
#     ./tools/run_python_ags4_tests.sh           # run all tests
#     ./tools/run_python_ags4_tests.sh test_ags4.py -k AGS4_to_dict
#                                                 # standard pytest args after $0
#
# Prerequisites:
#   - python-ags4 source cloned to `../ags-python-library/` (sibling
#     of this repo). Clone with:
#         git clone https://gitlab.com/ags-data-format-wg/ags-python-library \
#             ../ags-python-library
#   - `uv` on PATH; project's .venv synced (`uv sync`).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PY_AGS4_ROOT="$(cd "$REPO_ROOT/../ags-python-library" 2>/dev/null && pwd || true)"

if [ -z "$PY_AGS4_ROOT" ] || [ ! -d "$PY_AGS4_ROOT/tests" ]; then
    cat >&2 <<'EOF'
python-ags4 source tree not found at ../ags-python-library.

Clone it next to this repo:
    git clone https://gitlab.com/ags-data-format-wg/ags-python-library \
        ../ags-python-library

Then re-run this script.
EOF
    exit 2
fi

# Write the shim conftest.py into the cloned tests/ dir. Idempotent —
# we overwrite each run so it stays in sync with the latest shim
# strategy. The file is gitignored on their side via name (we don't
# add to their .gitignore; the file is intentionally local).
SHIM_PATH="$PY_AGS4_ROOT/tests/conftest_laterite_shim.py"
cat > "$SHIM_PATH" <<'PYEOF'
"""Auto-generated by laterite/tools/run_python_ags4_tests.sh.

Shims python_ags4 to laterite.compat so python-ags4's own tests run
against the laterite Rust-backed implementation. Loaded by pytest via
the conftest.py in this directory.

Two binding paths matter:
- `import python_ags4` → resolves via sys.modules.
- `from python_ags4 import AGS4` → resolves via attribute access on
  the python_ags4 module object (NOT sys.modules). So we wrap
  laterite.compat in a synthetic module-like namespace that exposes
  AGS4 / check / utils as attributes pointing back to itself.
"""

import sys
import types
from pathlib import Path

import laterite.compat as _compat


# Build a synthetic top-level `python_ags4` module so attribute
# lookups (`python_ags4.AGS4`) resolve. Re-export every public name
# from laterite.compat onto it, plus the sub-module attrs the tests
# expect to reach via `from python_ags4 import <name>`.
_py_ags4 = types.ModuleType("python_ags4")
# Mirror laterite.compat's honest identity string — PEP-440 local
# version showing both packages. See `_compat.__version__` for the
# rationale; this just propagates it via the shim so tests doing
# `from python_ags4 import __version__` see the same value.
_py_ags4.__version__ = getattr(_compat, "__version__", "laterite-compat")

# Re-export laterite.compat names.
for _name in dir(_compat):
    if not _name.startswith("_"):
        setattr(_py_ags4, _name, getattr(_compat, _name))

# Sub-namespaces: tests do `from python_ags4 import AGS4` etc., where
# AGS4 is itself a module. Point them all at laterite.compat (so e.g.
# AGS4.AGS4_to_dataframe resolves) — gaps surface as AttributeError
# at call time, which pytest reports as a clean test failure.
_py_ags4.AGS4 = _compat
_py_ags4.check = _compat
_py_ags4.utils = _compat

# python_ags4.data exposes TEST_DATA — a path to test_data.ags
# shipped in their repo. We rebuild it as a synthetic module so
# `from python_ags4.data import TEST_DATA` resolves.
_data_mod = types.ModuleType("python_ags4.data")
# Their package layout: ../python_ags4/data/test_data.ags relative
# to this shim (which lives in ../tests/).
_repo_root = Path(__file__).resolve().parent.parent
_data_mod.TEST_DATA = _repo_root / "python_ags4" / "data" / "test_data.ags"
_data_mod.DATA_DIR = _data_mod.TEST_DATA.parent
def _load_test_data(*args, **kwargs):
    return _compat.AGS4_to_dataframe(_data_mod.TEST_DATA, *args, **kwargs)
_data_mod.load_test_data = _load_test_data
_py_ags4.data = _data_mod

# python_ags4.ags4_cli — Click command surface. laterite has no
# CLI mirror; leaving as the bare compat module means imports
# succeed but command calls produce AttributeError. test_cli.py
# will fail loud — fine for Stage 1 inventory.
_py_ags4.ags4_cli = _compat

# Register so `import python_ags4` and `python_ags4.AGS4` etc.
# both work.
sys.modules["python_ags4"] = _py_ags4
sys.modules["python_ags4.AGS4"] = _compat
sys.modules["python_ags4.check"] = _compat
sys.modules["python_ags4.utils"] = _compat
sys.modules["python_ags4.data"] = _data_mod
sys.modules["python_ags4.ags4_cli"] = _compat
PYEOF

# Drop a conftest.py next to the shim if one doesn't already exist
# (their repo doesn't ship one).
CONFTEST="$PY_AGS4_ROOT/tests/conftest.py"
# Always (re)write the companion conftest.py so the shim load path
# stays in sync with whatever this script generates above.
cat > "$CONFTEST" <<'PYEOF'
# Auto-generated companion to conftest_laterite_shim.py.
# Loads the laterite shim before any test imports python_ags4.
import os, sys

sys.path.insert(0, os.path.dirname(__file__))
import conftest_laterite_shim  # noqa: F401
PYEOF

# Switch CWD to python-ags4 root — their tests use relative paths
# like `tests/test_files/*.ags`. uv run resolves the .venv that lives
# in laterite (where laterite is editable-installed) via the
# --project flag.
cd "$PY_AGS4_ROOT"
# test_cli.py is out of scope: laterite has no `ags4_cli` Click
# command mirror (we ship a different CLI, `lat`).
# Ignoring at the runner level keeps the failure-list focused on
# actual compat surface gaps.
exec uv run --project "$REPO_ROOT" --no-sync pytest tests \
    --ignore=tests/test_cli.py -v --no-header "$@"
